
g++  -fno-PIE -c  -DIN_GCC_FRONTEND -g -O0 -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variad
ic-macros -Wno-overlength-strings -fno-common  -DHAVE_CONFIG_H -I. -Irust -I../../gccrs/gcc -I../../gccrs/gcc/rust -I../../gccrs/gcc/../include -I../../gccrs/gcc/../libcpp/include -I../../gccrs/gcc/../libcody  -I../../gccrs/gcc/../libdecnumber -I.
./../gccrs/gcc/../libdecnumber/bid -I../libdecnumber -I../../gccrs/gcc/../libbacktrace   -o rust/rust-hir-full-test.o -MT rust/rust-hir-full-test.o -MMD -MP -MF rust/.deps/rust-hir-full-test.TPo -std=c++11 -Wno-unused-parameter -Werror=overloaded-
virtual -I ../../gccrs/gcc/rust -I ../../gccrs/gcc/rust/lex -I ../../gccrs/gcc/rust/parse -I ../../gccrs/gcc/rust/ast -I ../../gccrs/gcc/rust/analysis -I ../../gccrs/gcc/rust/backend -I ../../gccrs/gcc/rust/expand -I ../../gccrs/gcc/rust/hir/tree 
-I ../../gccrs/gcc/rust/hir -I ../../gccrs/gcc/rust/resolve -I ../../gccrs/gcc/rust/util -I ../../gccrs/gcc/rust/typecheck -I ../../gccrs/gcc/rust/lint ../../gccrs/gcc/rust/hir/tree/rust-hir-full-test.cc                                            
In file included from ../../gccrs/gcc/rust/ast/rust-ast-full.h:24,                                                                                                                                                                                     
                 from ../../gccrs/gcc/rust/hir/tree/rust-hir-full-test.cc:19:                                                                                                                                                                          
../../gccrs/gcc/rust/ast/rust-item.h: In constructor ‘Rust::AST::StructField::StructField(Rust::Identifier, std::unique_ptr<Rust::AST::Type>, Rust::AST::Visibility, Location, std::vector<Rust::AST::Attribute>)’:                                    
../../gccrs/gcc/rust/ast/rust-item.h:1846:10: warning: ‘Rust::AST::StructField::node_id’ will be initialized after [-Wreorder]
 1846 |   NodeId node_id;                                                                                                                                                                                                                              
      |          ^~~~~~~                                                                                                                                                                                                                               
../../gccrs/gcc/rust/ast/rust-item.h:1844:12: warning:   ‘Location Rust::AST::StructField::locus’ [-Wreorder]                                                                                                                                          
 1844 |   Location locus;                                                                                                                                                                                                                              
      |            ^~~~~                                                                                                                                                                                                                               
../../gccrs/gcc/rust/ast/rust-item.h:1855:3: warning:   when initialized here [-Wreorder]                                                                                                                                                              
 1855 |   StructField (Identifier field_name, std::unique_ptr<Type> field_type,                                                                                                                                                                        
      |   ^~~~~~~~~~~                                                                                                                                                                                                                                  
../../gccrs/gcc/rust/ast/rust-item.h: In copy constructor ‘Rust::AST::StructField::StructField(const Rust::AST::StructField&)’:                                                                                                                        
../../gccrs/gcc/rust/ast/rust-item.h:1846:10: warning: ‘Rust::AST::StructField::node_id’ will be initialized after [-Wreorder]                                                                                                                         
 1846 |   NodeId node_id;                                                                                                                                                                                                                              
      |          ^~~~~~~                                                                                                                                                                                                                               
../../gccrs/gcc/rust/ast/rust-item.h:1844:12: warning:   ‘Location Rust::AST::StructField::locus’ [-Wreorder]                                                                                                                                          
 1844 |   Location locus;                                                                                                                                                                                                                              
      |            ^~~~~                                                                                                                                                                                                                               
../../gccrs/gcc/rust/ast/rust-item.h:1864:3: warning:   when initialized here [-Wreorder]                                                                                                                                                              
 1864 |   StructField (StructField const &other)                                       
