plain
   Compiling ammonia v3.2.0
   Compiling mdbook v0.4.21
   Compiling error_index_generator v0.0.0 (/checkout/src/tools/error_index_generator)
    Finished release [optimized] target(s) in 51.05s
extra info: "/checkout/src/tools/error_index_generator" Ok("/checkout/obj")
Rustbook (x86_64-unknown-linux-gnu) - reference
Rustbook (x86_64-unknown-linux-gnu) - rustdoc
Rustbook (x86_64-unknown-linux-gnu) - rust-by-example
Generating lint docs (x86_64-unknown-linux-gnu)
---
Rustbook (x86_64-unknown-linux-gnu) - embedded-book
Rustbook (x86_64-unknown-linux-gnu) - edition-guide
Building stage0 tool linkchecker (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.15s
edition-guide/rust-2018/path-changes.html:210: broken link - `std/index.html`
edition-guide/rust-2018/path-changes.html:212: broken link - `core/index.html`
edition-guide/rust-2018/path-changes.html:216: broken link - `proc_macro/index.html`
edition-guide/rust-2018/path-changes.html:220: broken link - `alloc/index.html`
edition-guide/rust-2018/path-changes.html:223: broken link - `test/index.html`
edition-guide/rust-2018/path-changes.html:223: broken link - `book/appendix-07-nightly-rust.html`
edition-guide/print.html:551: broken link - `std/index.html`
edition-guide/print.html:553: broken link - `core/index.html`
edition-guide/print.html:557: broken link - `proc_macro/index.html`
edition-guide/print.html:561: broken link - `alloc/index.html`
edition-guide/print.html:564: broken link - `test/index.html`
edition-guide/print.html:564: broken link - `book/appendix-07-nightly-rust.html`
reference/expressions.html:332: broken link - `std/boxed/struct.Box.html`
reference/type-layout.html:157: broken link - `std/mem/fn.align_of_val.html`
reference/type-layout.html:161: broken link - `std/mem/fn.size_of_val.html`
reference/type-layout.html:163: broken link - `std/marker/trait.Sized.html`
reference/type-layout.html:164: broken link - `std/mem/fn.size_of.html`
reference/type-layout.html:164: broken link - `std/mem/fn.align_of.html`
reference/type-layout.html:164: broken link - `std/marker/trait.Sized.html`
reference/type-layout.html:336: broken link - `std/alloc/struct.Layout.html`
reference/linkage.html:152: broken link - `book/ch19-01-unsafe-rust.html`
reference/runtime.html:149: broken link - `core/panic/struct.PanicInfo.html`
reference/runtime.html:184: broken link - `book/ch09-01-unrecoverable-errors-with-panic.html`
reference/runtime.html:186: broken link - `std/panic/fn.set_hook.html`
reference/runtime.html:189: broken link - `alloc/alloc/trait.GlobalAlloc.html`
reference/inline-assembly.html:145: broken link - `core/arch/macro.asm.html`
reference/inline-assembly.html:145: broken link - `core/arch/macro.global_asm.html`
reference/inline-assembly.html:197: broken link - `std/fmt/index.html`
reference/types/pointer.html:182: broken link - `core/ptr/macro.addr_of.html`
reference/types/pointer.html:182: broken link - `core/ptr/macro.addr_of_mut.html`
reference/types/array.html:166: broken link - `std/vec/struct.Vec.html`
reference/types/closure.html:247: broken link - `std/ops/trait.FnOnce.html`
reference/types/closure.html:253: broken link - `std/ops/trait.FnMut.html`
reference/types/closure.html:257: broken link - `std/ops/trait.Fn.html`
reference/types/closure.html:261: broken link - `std/ops/trait.Fn.html`
reference/types/closure.html:261: broken link - `std/ops/trait.FnMut.html`
reference/types/boolean.html:173: broken link - `std/primitive.bool.html`
reference/types/function-item.html:186: broken link - `std/ops/trait.Fn.html`
reference/types/function-item.html:186: broken link - `std/ops/trait.FnMut.html`
reference/types/function-item.html:186: broken link - `std/ops/trait.FnOnce.html`
reference/items/unions.html:206: broken link - `std/mem/fn.transmute.html`
reference/items/enumerations.html:198: broken link - `std/mem/fn.discriminant.html`
reference/names/preludes.html:149: broken link - `std/boxed/struct.Box.html`
reference/names/preludes.html:163: broken link - `std/prelude/rust_2015/index.html`
reference/names/preludes.html:163: broken link - `core/prelude/rust_2015/index.html`
reference/names/preludes.html:164: broken link - `std/prelude/rust_2018/index.html`
reference/names/preludes.html:164: broken link - `core/prelude/rust_2018/index.html`
reference/names/preludes.html:165: broken link - `std/prelude/rust_2021/index.html`
reference/names/preludes.html:165: broken link - `core/prelude/rust_2021/index.html`
reference/names/preludes.html:170: broken link - `std/prelude/rust_2015/index.html`
reference/names/preludes.html:170: broken link - `std/prelude/rust_2018/index.html`
reference/names/preludes.html:170: broken link - `std/prelude/v1/index.html`
reference/names/preludes.html:171: broken link - `core/prelude/rust_2015/index.html`
reference/names/preludes.html:171: broken link - `core/prelude/rust_2018/index.html`
reference/names/preludes.html:171: broken link - `core/prelude/v1/index.html`
reference/names/preludes.html:177: broken link - `core/index.html`
reference/names/preludes.html:177: broken link - `std/index.html`
reference/names/preludes.html:187: broken link - `alloc/index.html`
reference/names/preludes.html:188: broken link - `test/index.html`
reference/names/preludes.html:206: broken link - `std/index.html`
reference/names/preludes.html:208: broken link - `core/index.html`
reference/names/preludes.html:208: broken link - `std/index.html`
reference/names/preludes.html:211: broken link - `std/index.html`
reference/names/preludes.html:215: broken link - `core/index.html`
reference/names/preludes.html:215: broken link - `std/index.html`
reference/print.html:161: broken link - `std/index.html`
reference/print.html:168: broken link - `book/index.html`
reference/print.html:169: broken link - `std/index.html`
reference/print.html:1777: broken link - `std/macro.compile_error.html`
reference/print.html:1780: broken link - `proc_macro/index.html`
reference/print.html:1782: broken link - `proc_macro/struct.TokenStream.html`
reference/print.html:1808: broken link - `proc_macro/struct.TokenStream.html`
reference/print.html:1809: broken link - `proc_macro/struct.TokenStream.html`
reference/print.html:1843: broken link - `proc_macro/struct.TokenStream.html`
reference/print.html:1844: broken link - `proc_macro/struct.TokenStream.html`
reference/print.html:1846: broken link - `proc_macro/struct.TokenStream.html`
reference/print.html:1903: broken link - `proc_macro/struct.TokenStream.html`
reference/print.html:1906: broken link - `proc_macro/struct.TokenStream.html`
reference/print.html:1906: broken link - `proc_macro/struct.TokenStream.html`
reference/print.html:1907: broken link - `proc_macro/struct.TokenStream.html`
reference/print.html:1921: broken link - `proc_macro/struct.TokenStream.html`
reference/print.html:1968: broken link - `proc_macro/enum.TokenTree.html`
reference/print.html:2016: broken link - `proc_macro/struct.Group.html`
reference/print.html:2017: broken link - `proc_macro/enum.Delimiter.html`
reference/print.html:2030: broken link - `proc_macro/struct.Group.html`
reference/print.html:2031: broken link - `proc_macro/enum.Delimiter.html`
reference/print.html:2127: broken link - `std/process/trait.Termination.html`
reference/print.html:2139: broken link - `std/process/trait.Termination.html`
reference/print.html:2143: broken link - `std/process/struct.ExitCode.html`
reference/print.html:2163: broken link - `std/primitive.char.html`
reference/print.html:2359: broken link - `std/macro.debug_assert.html`
reference/print.html:3393: broken link - `std/mem/fn.discriminant.html`
reference/print.html:3561: broken link - `std/mem/fn.transmute.html`
reference/print.html:5463: broken link - `unstable-book/index.html`
reference/print.html:5481: broken link - `std/process/trait.Termination.html`
reference/print.html:5494: broken link - `std/process/trait.Termination.html`
reference/print.html:5494: broken link - `std/process/struct.ExitCode.html`
reference/print.html:5557: broken link - `std/cmp/trait.PartialEq.html`
reference/print.html:5557: broken link - `std/clone/trait.Clone.html`
reference/print.html:6048: broken link - `std/arch/macro.is_x86_feature_detected.html`
reference/print.html:6048: broken link - `std/arch/macro.is_aarch64_feature_detected.html`
reference/print.html:6066: broken link - `core/panic/struct.Location.html`
reference/print.html:6069: broken link - `core/panic/struct.Location.html`
reference/print.html:6079: broken link - `core/panic/struct.Location.html`
reference/print.html:6080: broken link - `core/intrinsics/fn.caller_location.html`
reference/print.html:6639: broken link - `std/boxed/struct.Box.html`
reference/print.html:6827: broken link - `core/primitive.u128.html`
reference/print.html:6874: broken link - `core/primitive.f32.html`
reference/print.html:6874: broken link - `core/primitive.f64.html`
reference/print.html:6882: broken link - `core/primitive.f32.html`
reference/print.html:6882: broken link - `core/primitive.f64.html`
reference/print.html:6882: broken link - `core/primitive.f32.html`
reference/print.html:6882: broken link - `core/primitive.f64.html`
reference/print.html:6996: broken link - `std/ops/trait.Fn.html`
reference/print.html:6996: broken link - `std/future/trait.Future.html`
reference/print.html:7147: broken link - `std/ptr/macro.addr_of.html`
reference/print.html:7147: broken link - `std/ptr/macro.addr_of_mut.html`
reference/print.html:7760: broken link - `std/ops/trait.Index.html`
reference/print.html:7760: broken link - `std/ops/trait.IndexMut.html`
reference/print.html:7941: broken link - `std/ops/trait.Fn.html`
reference/print.html:7941: broken link - `std/ops/trait.FnMut.html`
reference/print.html:7941: broken link - `std/ops/trait.FnOnce.html`
reference/print.html:7965: broken link - `std/default/trait.Default.html`
reference/print.html:7965: broken link - `std/mem/fn.size_of.html`
reference/print.html:8071: broken link - `std/iter/trait.IntoIterator.html`
reference/print.html:8760: broken link - `std/future/trait.IntoFuture.html`
reference/print.html:8764: broken link - `std/future/trait.IntoFuture.html`
reference/print.html:8765: broken link - `std/future/trait.Future.html`
reference/print.html:8766: broken link - `std/pin/struct.Pin.html`
reference/print.html:8767: broken link - `std/future/trait.Future.html`
reference/print.html:8768: broken link - `std/task/enum.Poll.html`
reference/print.html:8769: broken link - `std/task/enum.Poll.html`
reference/print.html:8769: broken link - `std/task/enum.Poll.html`
reference/print.html:8775: broken link - `std/task/struct.Context.html`
reference/print.html:9793: broken link - `std/primitive.bool.html`
reference/print.html:9977: broken link - `std/vec/struct.Vec.html`
reference/print.html:10096: broken link - `std/ops/trait.Fn.html`
reference/print.html:10096: broken link - `std/ops/trait.FnMut.html`
reference/print.html:10096: broken link - `std/ops/trait.FnOnce.html`
reference/print.html:10201: broken link - `std/ops/trait.FnOnce.html`
reference/print.html:10207: broken link - `std/ops/trait.FnMut.html`
reference/print.html:10211: broken link - `std/ops/trait.Fn.html`
reference/print.html:10215: broken link - `std/ops/trait.Fn.html`
reference/print.html:10215: broken link - `std/ops/trait.FnMut.html`
reference/print.html:10294: broken link - `core/ptr/macro.addr_of.html`
reference/print.html:10294: broken link - `core/ptr/macro.addr_of_mut.html`
reference/print.html:10604: broken link - `std/mem/fn.align_of_val.html`
reference/print.html:10608: broken link - `std/mem/fn.size_of_val.html`
reference/print.html:10610: broken link - `std/marker/trait.Sized.html`
reference/print.html:10611: broken link - `std/mem/fn.size_of.html`
reference/print.html:10611: broken link - `std/mem/fn.align_of.html`
reference/print.html:10611: broken link - `std/marker/trait.Sized.html`
reference/print.html:10783: broken link - `std/alloc/struct.Layout.html`
reference/print.html:11085: broken link - `std/cell/struct.UnsafeCell.html`
reference/print.html:11092: broken link - `std/cell/struct.RefCell.html`
reference/print.html:11094: broken link - `std/sync/atomic/index.html`
reference/print.html:11521: broken link - `std/marker/trait.Unsize.html`
reference/print.html:11521: broken link - `std/ops/trait.CoerceUnsized.html`
reference/print.html:11634: broken link - `std/ops/trait.Drop.html`
reference/print.html:11650: broken link - `std/ptr/fn.drop_in_place.html`
reference/print.html:11953: broken link - `std/mem/fn.forget.html`
reference/print.html:11954: broken link - `std/mem/struct.ManuallyDrop.html`
reference/print.html:11957: broken link - `std/mem/fn.forget.html`
reference/print.html:12162: broken link - `std/index.html`
reference/print.html:12166: broken link - `std/boxed/struct.Box.html`
reference/print.html:12177: broken link - `std/rc/struct.Rc.html`
reference/print.html:12179: broken link - `std/sync/struct.Arc.html`
reference/print.html:12181: broken link - `std/pin/struct.Pin.html`
reference/print.html:12183: broken link - `std/cell/struct.UnsafeCell.html`
reference/print.html:12188: broken link - `std/marker/struct.PhantomData.html`
reference/print.html:12192: broken link - `std/ops/index.html`
reference/print.html:12192: broken link - `std/cmp/index.html`
reference/print.html:12195: broken link - `std/ops/trait.Deref.html`
reference/print.html:12195: broken link - `std/ops/trait.DerefMut.html`
reference/print.html:12198: broken link - `std/ops/trait.Drop.html`
reference/print.html:12201: broken link - `std/marker/trait.Copy.html`
reference/print.html:12214: broken link - `std/clone/trait.Clone.html`
reference/print.html:12222: broken link - `std/marker/trait.Send.html`
reference/print.html:12225: broken link - `std/marker/trait.Sync.html`
reference/print.html:12229: broken link - `std/process/trait.Termination.html`
reference/print.html:12231: broken link - `std/marker/trait.Send.html`
reference/print.html:12231: broken link - `std/marker/trait.Sync.html`
reference/print.html:12231: broken link - `std/marker/trait.Unpin.html`
reference/print.html:12231: broken link - `std/panic/trait.UnwindSafe.html`
reference/print.html:12231: broken link - `std/panic/trait.RefUnwindSafe.html`
reference/print.html:12260: broken link - `std/marker/trait.Sized.html`
reference/print.html:12471: broken link - `std/boxed/struct.Box.html`
reference/print.html:12485: broken link - `std/prelude/rust_2015/index.html`
reference/print.html:12485: broken link - `core/prelude/rust_2015/index.html`
reference/print.html:12486: broken link - `std/prelude/rust_2018/index.html`
reference/print.html:12486: broken link - `core/prelude/rust_2018/index.html`
reference/print.html:12487: broken link - `std/prelude/rust_2021/index.html`
reference/print.html:12487: broken link - `core/prelude/rust_2021/index.html`
reference/print.html:12492: broken link - `std/prelude/rust_2015/index.html`
reference/print.html:12492: broken link - `std/prelude/rust_2018/index.html`
reference/print.html:12492: broken link - `std/prelude/v1/index.html`
reference/print.html:12493: broken link - `core/prelude/rust_2015/index.html`
reference/print.html:12493: broken link - `core/prelude/rust_2018/index.html`
reference/print.html:12493: broken link - `core/prelude/v1/index.html`
reference/print.html:12499: broken link - `core/index.html`
reference/print.html:12499: broken link - `std/index.html`
reference/print.html:12509: broken link - `alloc/index.html`
reference/print.html:12510: broken link - `test/index.html`
reference/print.html:12528: broken link - `std/index.html`
reference/print.html:12530: broken link - `core/index.html`
reference/print.html:12530: broken link - `std/index.html`
reference/print.html:12533: broken link - `std/index.html`
reference/print.html:12537: broken link - `core/index.html`
reference/print.html:12537: broken link - `std/index.html`
reference/print.html:13209: broken link - `book/ch19-01-unsafe-rust.html`
reference/print.html:13402: broken link - `core/arch/macro.asm.html`
reference/print.html:13402: broken link - `core/arch/macro.global_asm.html`
reference/print.html:13454: broken link - `std/fmt/index.html`
reference/print.html:14093: broken link - `std/cell/struct.UnsafeCell.html`
reference/print.html:14096: broken link - `std/cell/struct.UnsafeCell.html`
reference/print.html:14140: broken link - `core/ptr/struct.NonNull.html`
reference/print.html:14140: broken link - `core/num/index.html`
reference/print.html:14403: broken link - `core/panic/struct.PanicInfo.html`
reference/print.html:14438: broken link - `book/ch09-01-unrecoverable-errors-with-panic.html`
reference/print.html:14440: broken link - `std/panic/fn.set_hook.html`
reference/print.html:14443: broken link - `alloc/alloc/trait.GlobalAlloc.html`
reference/procedural-macros.html:174: broken link - `std/macro.compile_error.html`
reference/procedural-macros.html:177: broken link - `proc_macro/index.html`
reference/procedural-macros.html:179: broken link - `proc_macro/struct.TokenStream.html`
reference/procedural-macros.html:205: broken link - `proc_macro/struct.TokenStream.html`
reference/procedural-macros.html:206: broken link - `proc_macro/struct.TokenStream.html`
reference/procedural-macros.html:240: broken link - `proc_macro/struct.TokenStream.html`
reference/procedural-macros.html:241: broken link - `proc_macro/struct.TokenStream.html`
reference/procedural-macros.html:243: broken link - `proc_macro/struct.TokenStream.html`
reference/procedural-macros.html:300: broken link - `proc_macro/struct.TokenStream.html`
reference/procedural-macros.html:303: broken link - `proc_macro/struct.TokenStream.html`
reference/procedural-macros.html:303: broken link - `proc_macro/struct.TokenStream.html`
reference/procedural-macros.html:304: broken link - `proc_macro/struct.TokenStream.html`
reference/procedural-macros.html:318: broken link - `proc_macro/struct.TokenStream.html`
reference/procedural-macros.html:365: broken link - `proc_macro/enum.TokenTree.html`
reference/procedural-macros.html:413: broken link - `proc_macro/struct.Group.html`
reference/procedural-macros.html:414: broken link - `proc_macro/enum.Delimiter.html`
reference/procedural-macros.html:427: broken link - `proc_macro/struct.Group.html`
reference/procedural-macros.html:428: broken link - `proc_macro/enum.Delimiter.html`
reference/attributes/testing.html:152: broken link - `std/process/trait.Termination.html`
reference/attributes/testing.html:165: broken link - `std/process/trait.Termination.html`
reference/attributes/testing.html:165: broken link - `std/process/struct.ExitCode.html`
reference/attributes/derive.html:149: broken link - `std/cmp/trait.PartialEq.html`
reference/attributes/derive.html:149: broken link - `std/clone/trait.Clone.html`
reference/attributes/codegen.html:311: broken link - `std/arch/macro.is_x86_feature_detected.html`
reference/attributes/codegen.html:311: broken link - `std/arch/macro.is_aarch64_feature_detected.html`
reference/attributes/codegen.html:329: broken link - `core/panic/struct.Location.html`
reference/attributes/codegen.html:332: broken link - `core/panic/struct.Location.html`
reference/attributes/codegen.html:342: broken link - `core/panic/struct.Location.html`
reference/attributes/codegen.html:343: broken link - `core/intrinsics/fn.caller_location.html`
reference/crates-and-source-files.html:235: broken link - `std/process/trait.Termination.html`
reference/crates-and-source-files.html:247: broken link - `std/process/trait.Termination.html`
reference/crates-and-source-files.html:251: broken link - `std/process/struct.ExitCode.html`
reference/crates-and-source-files.html:271: broken link - `std/primitive.char.html`
reference/index.html:160: broken link - `std/index.html`
reference/index.html:167: broken link - `book/index.html`
reference/index.html:168: broken link - `std/index.html`
reference/attributes.html:448: broken link - `unstable-book/index.html`
reference/special-types-and-traits.html:145: broken link - `std/index.html`
reference/special-types-and-traits.html:149: broken link - `std/boxed/struct.Box.html`
reference/special-types-and-traits.html:160: broken link - `std/rc/struct.Rc.html`
reference/special-types-and-traits.html:162: broken link - `std/sync/struct.Arc.html`
reference/special-types-and-traits.html:164: broken link - `std/pin/struct.Pin.html`
reference/special-types-and-traits.html:166: broken link - `std/cell/struct.UnsafeCell.html`
reference/special-types-and-traits.html:171: broken link - `std/marker/struct.PhantomData.html`
reference/special-types-and-traits.html:175: broken link - `std/ops/index.html`
reference/special-types-and-traits.html:175: broken link - `std/cmp/index.html`
reference/special-types-and-traits.html:178: broken link - `std/ops/trait.Deref.html`
reference/special-types-and-traits.html:178: broken link - `std/ops/trait.DerefMut.html`
reference/special-types-and-traits.html:181: broken link - `std/ops/trait.Drop.html`
reference/special-types-and-traits.html:184: broken link - `std/marker/trait.Copy.html`
reference/special-types-and-traits.html:197: broken link - `std/clone/trait.Clone.html`
reference/special-types-and-traits.html:205: broken link - `std/marker/trait.Send.html`
reference/special-types-and-traits.html:208: broken link - `std/marker/trait.Sync.html`
reference/special-types-and-traits.html:212: broken link - `std/process/trait.Termination.html`
reference/special-types-and-traits.html:214: broken link - `std/marker/trait.Send.html`
reference/special-types-and-traits.html:214: broken link - `std/marker/trait.Sync.html`
reference/special-types-and-traits.html:214: broken link - `std/marker/trait.Unpin.html`
reference/special-types-and-traits.html:214: broken link - `std/panic/trait.UnwindSafe.html`
reference/special-types-and-traits.html:214: broken link - `std/panic/trait.RefUnwindSafe.html`
reference/special-types-and-traits.html:243: broken link - `std/marker/trait.Sized.html`
reference/type-coercions.html:315: broken link - `std/marker/trait.Unsize.html`
reference/type-coercions.html:315: broken link - `std/ops/trait.CoerceUnsized.html`
reference/interior-mutability.html:150: broken link - `std/cell/struct.UnsafeCell.html`
reference/interior-mutability.html:157: broken link - `std/cell/struct.RefCell.html`
reference/interior-mutability.html:159: broken link - `std/sync/atomic/index.html`
reference/behavior-considered-undefined.html:168: broken link - `std/cell/struct.UnsafeCell.html`
reference/behavior-considered-undefined.html:171: broken link - `std/cell/struct.UnsafeCell.html`
reference/behavior-considered-undefined.html:215: broken link - `core/ptr/struct.NonNull.html`
reference/behavior-considered-undefined.html:215: broken link - `core/num/index.html`
reference/expressions/operator-expr.html:221: broken link - `std/ptr/macro.addr_of.html`
reference/expressions/operator-expr.html:221: broken link - `std/ptr/macro.addr_of_mut.html`
reference/expressions/literal-expr.html:245: broken link - `core/primitive.u128.html`
reference/expressions/literal-expr.html:292: broken link - `core/primitive.f32.html`
reference/expressions/literal-expr.html:292: broken link - `core/primitive.f64.html`
reference/expressions/literal-expr.html:300: broken link - `core/primitive.f32.html`
reference/expressions/literal-expr.html:300: broken link - `core/primitive.f64.html`
reference/expressions/literal-expr.html:300: broken link - `core/primitive.f32.html`
reference/expressions/literal-expr.html:300: broken link - `core/primitive.f64.html`
reference/expressions/array-expr.html:212: broken link - `std/ops/trait.Index.html`
reference/expressions/array-expr.html:212: broken link - `std/ops/trait.IndexMut.html`
reference/expressions/call-expr.html:155: broken link - `std/ops/trait.Fn.html`
reference/expressions/call-expr.html:155: broken link - `std/ops/trait.FnMut.html`
reference/expressions/call-expr.html:155: broken link - `std/ops/trait.FnOnce.html`
reference/expressions/call-expr.html:179: broken link - `std/default/trait.Default.html`
reference/expressions/call-expr.html:179: broken link - `std/mem/fn.size_of.html`
reference/expressions/await-expr.html:153: broken link - `std/future/trait.IntoFuture.html`
reference/expressions/await-expr.html:157: broken link - `std/future/trait.IntoFuture.html`
reference/expressions/await-expr.html:158: broken link - `std/future/trait.Future.html`
reference/expressions/await-expr.html:159: broken link - `std/pin/struct.Pin.html`
reference/expressions/await-expr.html:160: broken link - `std/future/trait.Future.html`
reference/expressions/await-expr.html:161: broken link - `std/task/enum.Poll.html`
reference/expressions/await-expr.html:162: broken link - `std/task/enum.Poll.html`
reference/expressions/await-expr.html:162: broken link - `std/task/enum.Poll.html`
reference/expressions/await-expr.html:168: broken link - `std/task/struct.Context.html`
reference/expressions/method-call-expr.html:206: broken link - `std/iter/trait.IntoIterator.html`
reference/expressions/block-expr.html:223: broken link - `std/ops/trait.Fn.html`
reference/expressions/block-expr.html:223: broken link - `std/future/trait.Future.html`
reference/destructors.html:152: broken link - `std/ops/trait.Drop.html`
reference/destructors.html:168: broken link - `std/ptr/fn.drop_in_place.html`
reference/destructors.html:471: broken link - `std/mem/fn.forget.html`
reference/destructors.html:472: broken link - `std/mem/struct.ManuallyDrop.html`
reference/destructors.html:475: broken link - `std/mem/fn.forget.html`
reference/conditional-compilation.html:315: broken link - `std/macro.debug_assert.html`
reference/introduction.html:160: broken link - `std/index.html`
reference/introduction.html:167: broken link - `book/index.html`
reference/introduction.html:168: broken link - `std/index.html`
cargo/reference/features.html:180: broken link - `std/macro.cfg.html`
cargo/reference/features.html:196: broken link - `std/primitive.char.html`
cargo/reference/features.html:529: broken link - `unstable-book/language-features/doc-cfg.html`
cargo/reference/resolver.html:254: broken link - `std/any/trait.Any.html`
cargo/reference/registries.html:314: broken link - `std/primitive.char.html`
cargo/reference/profiles.html:212: broken link - `book/appendix-07-nightly-rust.html`
cargo/reference/profiles.html:234: broken link - `std/macro.debug_assert.html`
cargo/reference/build-scripts.html:346: broken link - `std/macro.env.html`
cargo/reference/build-script-examples.html:245: broken link - `std/macro.include.html`
cargo/reference/build-script-examples.html:246: broken link - `std/macro.concat.html`
cargo/reference/build-script-examples.html:246: broken link - `std/macro.env.html`
cargo/reference/build-script-examples.html:536: broken link - `std/macro.cfg.html`
cargo/reference/manifest.html:226: broken link - `std/primitive.char.html`
cargo/reference/unstable.html:151: broken link - `book/appendix-07-nightly-rust.html`
cargo/reference/features-examples.html:185: broken link - `std/prelude/index.html`
cargo/reference/features-examples.html:230: broken link - `book/appendix-07-nightly-rust.html`
cargo/reference/features-examples.html:233: broken link - `std/marker/trait.Unsize.html`
cargo/reference/features-examples.html:236: broken link - `unstable-book/index.html`
cargo/reference/cargo-targets.html:255: broken link - `std/macro.env.html`
cargo/reference/cargo-targets.html:273: broken link - `unstable-book/library-features/test.html`
cargo/reference/cargo-targets.html:275: broken link - `book/appendix-07-nightly-rust.html`
cargo/reference/cargo-targets.html:345: broken link - `book/ch19-06-macros.html`
cargo/reference/semver.html:392: broken link - `std/default/trait.Default.html`
cargo/reference/semver.html:424: broken link - `std/default/trait.Default.html`
cargo/reference/environment-variables.html:312: broken link - `std/macro.env.html`
cargo/print.html:508: broken link - `book/ch07-00-managing-growing-projects-with-packages-crates-and-modules.html`
cargo/print.html:620: broken link - `book/ch11-00-testing.html`
cargo/print.html:1662: broken link - `std/primitive.char.html`
cargo/print.html:2185: broken link - `std/macro.env.html`
cargo/print.html:2203: broken link - `unstable-book/library-features/test.html`
cargo/print.html:2205: broken link - `book/appendix-07-nightly-rust.html`
cargo/print.html:2275: broken link - `book/ch19-06-macros.html`
cargo/print.html:2551: broken link - `std/macro.cfg.html`
cargo/print.html:2567: broken link - `std/primitive.char.html`
cargo/print.html:2900: broken link - `unstable-book/language-features/doc-cfg.html`
cargo/print.html:2950: broken link - `std/prelude/index.html`
cargo/print.html:2995: broken link - `book/appendix-07-nightly-rust.html`
cargo/print.html:2998: broken link - `std/marker/trait.Unsize.html`
cargo/print.html:3001: broken link - `unstable-book/index.html`
cargo/print.html:3076: broken link - `book/appendix-07-nightly-rust.html`
cargo/print.html:3098: broken link - `std/macro.debug_assert.html`
cargo/print.html:4478: broken link - `std/macro.env.html`
cargo/print.html:4816: broken link - `std/macro.env.html`
cargo/print.html:5075: broken link - `std/macro.include.html`
cargo/print.html:5076: broken link - `std/macro.concat.html`
cargo/print.html:5076: broken link - `std/macro.env.html`
cargo/print.html:5366: broken link - `std/macro.cfg.html`
cargo/print.html:6140: broken link - `std/primitive.char.html`
cargo/print.html:6664: broken link - `std/any/trait.Any.html`
cargo/print.html:7213: broken link - `std/default/trait.Default.html`
cargo/print.html:7245: broken link - `std/default/trait.Default.html`
cargo/print.html:8246: broken link - `book/appendix-07-nightly-rust.html`
cargo/guide/project-layout.html:199: broken link - `book/ch07-00-managing-growing-projects-with-packages-crates-and-modules.html`
cargo/guide/tests.html:176: broken link - `book/ch11-00-testing.html`
nomicon/other-reprs.html:211: broken link - `std/cell/struct.UnsafeCell.html`
nomicon/other-reprs.html:212: broken link - `std/cell/struct.UnsafeCell.html`
nomicon/exotic-sizes.html:158: broken link - `std/primitive.slice.html`
nomicon/exotic-sizes.html:158: broken link - `std/primitive.str.html`
nomicon/exotic-sizes.html:235: broken link - `std/alloc/trait.GlobalAlloc.html`
nomicon/dot-operator.html:155: broken link - `book/ch19-03-advanced-traits.html`
nomicon/dot-operator.html:180: broken link - `std/ops/trait.Index.html`
nomicon/dot-operator.html:240: broken link - `std/clone/trait.Clone.html`
nomicon/what-unsafe-does.html:186: broken link - `std/ptr/struct.NonNull.html`
nomicon/print.html:160: broken link - `book/index.html`
nomicon/print.html:162: broken link - `book/index.html`
nomicon/print.html:247: broken link - `std/primitive.slice.html`
nomicon/print.html:249: broken link - `std/marker/trait.Send.html`
nomicon/print.html:253: broken link - `std/primitive.slice.html`
nomicon/print.html:255: broken link - `std/mem/fn.transmute.html`
nomicon/print.html:257: broken link - `std/primitive.pointer.html`
nomicon/print.html:258: broken link - `std/primitive.pointer.html`
nomicon/print.html:266: broken link - `std/marker/trait.Send.html`
nomicon/print.html:268: broken link - `std/marker/trait.Sync.html`
nomicon/print.html:270: broken link - `std/alloc/trait.GlobalAlloc.html`
nomicon/print.html:282: broken link - `std/cmp/trait.PartialOrd.html`
nomicon/print.html:282: broken link - `std/cmp/trait.Ord.html`
nomicon/print.html:285: broken link - `std/collections/struct.BTreeMap.html`
nomicon/print.html:400: broken link - `std/ptr/struct.NonNull.html`
nomicon/print.html:718: broken link - `std/primitive.slice.html`
nomicon/print.html:718: broken link - `std/primitive.str.html`
nomicon/print.html:795: broken link - `std/alloc/trait.GlobalAlloc.html`
nomicon/print.html:920: broken link - `std/cell/struct.UnsafeCell.html`
nomicon/print.html:921: broken link - `std/cell/struct.UnsafeCell.html`
nomicon/print.html:2411: broken link - `std/mem/struct.ManuallyDrop.html`
nomicon/print.html:2974: broken link - `book/ch19-03-advanced-traits.html`
nomicon/print.html:2999: broken link - `std/ops/trait.Index.html`
nomicon/print.html:3059: broken link - `std/clone/trait.Clone.html`
nomicon/print.html:3099: broken link - `std/mem/fn.transmute.html`
nomicon/print.html:3143: broken link - `std/mem/fn.transmute_copy.html`
nomicon/print.html:3343: broken link - `core/mem/union.MaybeUninit.html`
nomicon/print.html:3386: broken link - `core/mem/union.MaybeUninit.html`
nomicon/print.html:3423: broken link - `core/ptr/index.html`
nomicon/print.html:3425: broken link - `core/ptr/fn.write.html`
nomicon/print.html:3425: broken link - `std/ptr/fn.copy.html`
nomicon/print.html:3425: broken link - `std/ptr/fn.copy_nonoverlapping.html`
nomicon/print.html:3464: broken link - `core/ptr/macro.addr_of_mut.html`
nomicon/print.html:4755: broken link - `std/ptr/struct.NonNull.html`
nomicon/print.html:4809: broken link - `alloc/alloc/fn.alloc.html`
nomicon/print.html:4809: broken link - `alloc/alloc/fn.realloc.html`
nomicon/print.html:4810: broken link - `alloc/alloc/fn.dealloc.html`
nomicon/print.html:4811: broken link - `alloc/alloc/index.html`
nomicon/print.html:4812: broken link - `std/alloc/struct.Global.html`
nomicon/print.html:4814: broken link - `alloc/alloc/fn.handle_alloc_error.html`
nomicon/print.html:6773: broken link - `std/ops/trait.Drop.html`
nomicon/print.html:7246: broken link - `std/panic/fn.catch_unwind.html`
nomicon/print.html:7262: broken link - `std/panic/fn.catch_unwind.html`
nomicon/print.html:7263: broken link - `std/panic/fn.catch_unwind.html`
nomicon/print.html:7338: broken link - `core/panic/struct.PanicInfo.html`
nomicon/vec/vec-layout.html:174: broken link - `std/ptr/struct.NonNull.html`
nomicon/vec/vec-alloc.html:179: broken link - `alloc/alloc/fn.alloc.html`
nomicon/vec/vec-alloc.html:179: broken link - `alloc/alloc/fn.realloc.html`
nomicon/vec/vec-alloc.html:180: broken link - `alloc/alloc/fn.dealloc.html`
nomicon/vec/vec-alloc.html:181: broken link - `alloc/alloc/index.html`
nomicon/vec/vec-alloc.html:182: broken link - `std/alloc/struct.Global.html`
nomicon/vec/vec-alloc.html:184: broken link - `alloc/alloc/fn.handle_alloc_error.html`
nomicon/panic-handler.html:147: broken link - `core/panic/struct.PanicInfo.html`
nomicon/index.html:159: broken link - `book/index.html`
nomicon/index.html:161: broken link - `book/index.html`
nomicon/safe-unsafe-meaning.html:165: broken link - `std/primitive.slice.html`
nomicon/safe-unsafe-meaning.html:167: broken link - `std/marker/trait.Send.html`
nomicon/safe-unsafe-meaning.html:171: broken link - `std/primitive.slice.html`
nomicon/safe-unsafe-meaning.html:173: broken link - `std/mem/fn.transmute.html`
nomicon/safe-unsafe-meaning.html:175: broken link - `std/primitive.pointer.html`
nomicon/safe-unsafe-meaning.html:176: broken link - `std/primitive.pointer.html`
nomicon/safe-unsafe-meaning.html:184: broken link - `std/marker/trait.Send.html`
nomicon/safe-unsafe-meaning.html:186: broken link - `std/marker/trait.Sync.html`
nomicon/safe-unsafe-meaning.html:188: broken link - `std/alloc/trait.GlobalAlloc.html`
nomicon/safe-unsafe-meaning.html:200: broken link - `std/cmp/trait.PartialOrd.html`
nomicon/safe-unsafe-meaning.html:200: broken link - `std/cmp/trait.Ord.html`
nomicon/safe-unsafe-meaning.html:203: broken link - `std/collections/struct.BTreeMap.html`
nomicon/transmutes.html:150: broken link - `std/mem/fn.transmute.html`
nomicon/transmutes.html:194: broken link - `std/mem/fn.transmute_copy.html`
nomicon/ffi.html:347: broken link - `std/ops/trait.Drop.html`
nomicon/ffi.html:820: broken link - `std/panic/fn.catch_unwind.html`
nomicon/ffi.html:836: broken link - `std/panic/fn.catch_unwind.html`
nomicon/ffi.html:837: broken link - `std/panic/fn.catch_unwind.html`
nomicon/unchecked-uninit.html:152: broken link - `core/mem/union.MaybeUninit.html`
nomicon/unchecked-uninit.html:195: broken link - `core/mem/union.MaybeUninit.html`
nomicon/unchecked-uninit.html:232: broken link - `core/ptr/index.html`
nomicon/unchecked-uninit.html:234: broken link - `core/ptr/fn.write.html`
nomicon/unchecked-uninit.html:234: broken link - `std/ptr/fn.copy.html`
nomicon/unchecked-uninit.html:234: broken link - `std/ptr/fn.copy_nonoverlapping.html`
nomicon/unchecked-uninit.html:273: broken link - `core/ptr/macro.addr_of_mut.html`
nomicon/dropck.html:429: broken link - `std/mem/struct.ManuallyDrop.html`
nomicon/intro.html:159: broken link - `book/index.html`
nomicon/intro.html:161: broken link - `book/index.html`
404.html:16: absolute path - /favicon.svg
404.html:17: absolute path - /favicon.png
404.html:18: absolute path - /css/variables.css
404.html:19: absolute path - /css/general.css
404.html:20: absolute path - /css/chrome.css
404.html:21: absolute path - /css/print.css
404.html:23: absolute path - /FontAwesome/css/font-awesome.css
404.html:24: absolute path - /fonts/fonts.css
404.html:26: absolute path - /highlight.css
404.html:27: absolute path - /tomorrow-night.css
404.html:28: absolute path - /ayu-highlight.css
404.html:31: absolute path - /extra.css
404.html:82: absolute path - /error-index.html
404.html:82: absolute path - /error_codes/E0001.html
404.html:82: absolute path - /error_codes/E0002.html
404.html:82: absolute path - /error_codes/E0004.html
404.html:82: absolute path - /error_codes/E0005.html
404.html:82: absolute path - /error_codes/E0007.html
404.html:82: absolute path - /error_codes/E0009.html
404.html:82: absolute path - /error_codes/E0010.html
404.html:82: absolute path - /error_codes/E0013.html
404.html:82: absolute path - /error_codes/E0014.html
404.html:82: absolute path - /error_codes/E0015.html
