
       │     let a: Block = Block::from_slice(&haystack[i..]);                                                                                                                                                                                                                                                              ▒
       │       mov       %r15,%rdx                                                                                                                                                                                                                                                                                          ▒
       │       mov       %rdi,%rbp                                                                                                                                                                                                                                                                                          ▒
       │     → call      core::core_simd::vector::Simd<T,_>::from_slice                                                                                                                                                                                                                                                     ▒
       │     <core::ops::range::RangeFrom<usize> as core::slice::index::SliceIndex<[T]>>::index:                                                                                                                                                                                                                            ▒
       │     if self.start > slice.len() {                                                                                                                                                                                                                                                                                  ▒
       │       lea       (%r12,%rbx,1),%rdi                                                                                                                                                                                                                                                                                 ▒
       │       dec       %rdi                                                                                                                                                                                                                                                                                               ▒
       │       cmp       %r13,%rdi                                                                                                                                                                                                                                                                                          ▒
  0.45 │     ↓ ja        3b0                                                                                                                                                                                                                                                                                                ▒
       │     core::str::pattern::simd_contains::{{closure}}:                                                                                                                                                                                                                                                                ▒
       │       movaps    0x10(%rsp),%xmm0                                                                                                                                                                                                                                                                                   ▒
  0.45 │       movaps    %xmm0,0x30(%rsp)                                                                                                                                                                                                                                                                                   ▒
  0.83 │       mov       0x58(%rsp),%rax                                                                                                                                                                                                                                                                                    ▒
       │     <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::get_unchecked:                                                                                                                                                                                                                        ▒
       │     ptr::slice_from_raw_parts(slice.as_ptr().add(self.start), self.end - self.start)                                                                                                                                                                                                                               ▒
       │       lea       (%rax,%rbx,1),%rsi                                                                                                                                                                                                                                                                                 ▒
 10.08 │       mov       0x50(%rsp),%rax                                                                                                                                                                                                                                                                                    ▒
       │     core::str::pattern::simd_contains::{{closure}}:                                                                                                                                                                                                                                                                ▒
       │     let b: Block = Block::from_slice(&haystack[(i + needle.len() - 1)..]);                                                                                                                                                                                                                                         ▒
       │       lea       (%rax,%r15,1),%rdx                                                                                                                                                                                                                                                                                 ▒
       │       mov       %rbp,%rdi                                                                                                                                                                                                                                                                                          ▒
       │     → call      core::core_simd::vector::Simd<T,_>::from_slice                                                                                                                                                                                                                                                     ▒
       │       movdqa    0x10(%rsp),%xmm0                                                                                                 
