plain
[RUSTC-TIMING] rustc_mir_transform test:false 86.394
[RUSTC-TIMING] rustc_borrowck test:false 82.379
   Compiling rustc_driver v0.0.0 (/checkout/compiler/rustc_driver)
[RUSTC-TIMING] rustc_driver test:false 10.014
error: linking with `arm-unknown-linux-gnueabi-gcc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/x-tools/arm-unknown-linux-gnueabi/bin" VSLANG="1033" "arm-unknown-linux-gnueabi-gcc" "/tmp/rustc6DLsQh/symbols.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/rustc_main-5d0ba4ea822e621c.rustc_main.fa4589f2cc83994f-cgu.0.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/rustc_main-5d0ba4ea822e621c.rustc_main.fa4589f2cc83994f-cgu.1.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/rustc_main-5d0ba4ea822e621c.rustc_main.fa4589f2cc83994f-cgu.2.rcgu.o" "-Wl,--as-needed" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/build/psm-1cb89056517de487/out" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/build/rustc_llvm-c4346f299d2840ac/out" "-L" "/checkout/obj/build/arm-unknown-linux-gnueabi/llvm/build/lib" "-L" "/x-tools/arm-unknown-linux-gnueabi/lib/gcc/arm-unknown-linux-gnueabi/8.3.0/../../../../arm-unknown-linux-gnueabi/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/arm-unknown-linux-gnueabi/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps" "-lrustc_driver-286dfbb3088fff45" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/arm-unknown-linux-gnueabi/lib" "-lstd-36f31bfb7a99faa2" "-Wl,-Bstatic" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/arm-unknown-linux-gnueabi/lib/libcompiler_builtins-ad59952643663a11.rlib" "-Wl,-Bdynamic" "-latomic" "-ldl" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/arm-unknown-linux-gnueabi/lib" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/rustc_main-5d0ba4ea822e621c" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-Wl,-z,origin" "-Wl,-rpath,$ORIGIN/../lib"
  = note: /x-tools/arm-unknown-linux-gnueabi/lib/gcc/arm-unknown-linux-gnueabi/8.3.0/../../../../arm-unknown-linux-gnueabi/bin/ld: /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/librustc_driver-286dfbb3088fff45.so: undefined reference to `std::io::error::Error::_new'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
[RUSTC-TIMING] rustc_main test:false 0.115
error: could not compile `rustc-main` due to previous error
Build completed unsuccessfully in 0:11:37
