
rustc: i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib/libstd
error: linking with `gcc` failed: exit code: 1
note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-Wl,--large-address-aware" "C:\\Src\\rust\\i686-pc-windows-gnu\\stage0\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\dllcrt2.o" "C:\\Src\\rust\\i686-pc-windows-gnu\\stage0\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\Src\\rust\\i686-pc-windows-gnu\\stage0\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib\\std-db5a760f.0.o" "-o" "i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib\\std-db5a760f.dll" "i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib\\std-db5a760f.metadata.o" "-nodefaultlibs" "-L" "i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib" "-L" "i686-pc-windows-gnu/rt" "-L" "C:\\Src\\rust\\i686-pc-windows-gnu\\llvm\\Debug+Asserts/lib" "-L" "C:\\Src\\rust\\i686-pc-windows-gnu\\stage0\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-l" "backtrace" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-l" "gcc_eh" "-l" "gcc_eh" "-l" "ws2_32" "-l" "userenv" "-l" "shell32" "-l" "advapi32" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\libcollections-db5a760f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\liballoc-db5a760f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\librustc_unicode-db5a760f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\librand-db5a760f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\liballoc_system-db5a760f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\liblibc-db5a760f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "C:\\Software\\msys32\\tmp\\rustc.dYIIShVa6jRu\\libcore-db5a760f.rlib" "-Wl,--no-whole-archive" "-shared" "-l" "compiler-rt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\Src\\rust\\i686-pc-windows-gnu\\stage0\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\rsend.o"
note: gcc.exe: error: C:\Src\rust\i686-pc-windows-gnu\stage0\lib\rustlib\i686-pc-windows-gnu\lib\dllcrt2.o: No such file or directory
error: aborting due to previous error
/c/Src/rust/mk/target.mk:186: recipe for target 'i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib/stamp.std' failed
make: *** [i686-pc-windows-gnu/stage0/lib/rustlib/i686-pc-windows-gnu/lib/stamp.std]
 Error 101
