
mergerollup josephDunne:trait_item_macros 34213 nrc
mergerollup jseyfried:refactor_ast_stmt 34316 eddyb
mergerollup jseyfried:thin_vec 34339 petrochenkov,Manishearth
mergerollup petrochenkov:astqpath 34368 Manishearth
mergerollup cgswords:tstream 34385 nrc
mergerollup jonathandturner:move_liberror 34403 alexcrichton
