
...
Core was generated by `./rustc -V'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fc2fb8c3478 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fc2fafff700 (LWP 20981))]
(gdb) thread apply all bt full

Thread 2 (Thread 0x7fc2fc969a00 (LWP 20980)):
#0  0x00007fc2fc55c6dd in pthread_join (threadid=140475411461888, thread_return=0x0) at pthread_join.c:90
        __tid = 20981
        _buffer = {__routine = 0x7fc2fc55c600 <cleanup>, __arg = 0x7fc2fafffd28, __canceltype = 0, __prev = 0x0}
        oldtype = 0
        pd = 0x7fc2fafff700
        self = 0x7fc2fc969a00
        result = 0
#1  0x0000559ed40df62d in run::hd7b71f248f200162ANc ()
No symbol table info available.
#2  0x0000559ed410686a in main::h5db63d7a27c2fc7cV1d ()
No symbol table info available.
#3  0x0000559ed6061945 in sys_common::unwind::try::try_fn::h15027524469598381028 ()
No symbol table info available.
#4  0x0000559ed6059bdc in __rust_try ()
No symbol table info available.
#5  0x0000559ed60613cf in rt::lang_start::h5aff6b64d0427d3aSVy ()
No symbol table info available.
#6  0x00007fc2fb8b0610 in __libc_start_main (main=0x559ed40deca0 <main>, argc=2, argv=0x7ffccee5af48, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffccee5af38) at libc-start.c:291
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -6565025173535672052, 94140650875680, 140723779645248, 0, 0, -1143798050367948532, 
                -1127022066127030004}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x559ed609ec00 <__libc_csu_init>, 0x7ffccee5af48}, data = {
              prev = 0x0, cleanup = 0x0, canceltype = -703992832}}}
        not_first_call = <optimized out>
#7  0x0000559ed40deb49 in _start ()
No symbol table info available.

Thread 1 (Thread 0x7fc2fafff700 (LWP 20981)):
#0  0x00007fc2fb8c3478 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 20980
        selftid = 20981
#1  0x00007fc2fb8c48fa in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x10, sa_sigaction = 0x10}, sa_mask = {__val = {140475394828912, 94140697673072, 
              140475436130416, 0, 0, 0, 0, 0, 140475438275144, 140475411458944, 140475438124648, 78, 140475421379305, 78, 140475411454352, 2}}, 
          sa_flags = 4023, sa_restorer = 0x1}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000559ed607a262 in je_arena_dalloc_junk_small ()
No locals.
#3  0x0000559ed607c0ce in je_arena_dalloc_bin_locked ()
No locals.
#4  0x0000559ed6090585 in tcache_destroy ()
No locals.
#5  0x0000559ed6090e22 in je_tcache_cleanup ()
No locals.
#6  0x0000559ed609382d in je_tsd_cleanup ()
No locals.
#7  0x00007fc2fc55a529 in __nptl_deallocate_tsd () at pthread_create.c:176
        data = <optimized out>
        level2 = 0x7fc2fafffa10
        idx = <optimized out>
        round = 0
        cnt = 0
#8  0x00007fc2fc55b608 in __nptl_deallocate_tsd () at pthread_create.c:327
No locals.
#9  start_thread (arg=0x7fc2fafff700) at pthread_create.c:347
        pd = 0x7fc2fafff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140475411461888, 1142212746245880076, 0, 140723779642159, 3, 140475411853392, 
                -1127024092031436532, -1127011669632698100}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, 
              cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#10 0x00007fc2fb978eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
