
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-L" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/test/run-make/relocation-model.stage2-armv7-unknown-linux-gnueabihf/foo.0.o" "-o" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/test/run-make/relocation-model.stage2-armv7-unknown-linux-gnueabihf/foo" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/test/run-make/relocation-model.stage2-armv7-unknown-linux-gnueabihf" "-L" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libstd-e8edd0fd.rlib" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libcollections-e8edd0fd.rlib" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libpanic_unwind-e8edd0fd.rlib" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/librustc_unicode-e8edd0fd.rlib" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libunwind-e8edd0fd.rlib" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/librand-e8edd0fd.rlib" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/liballoc-e8edd0fd.rlib" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/liballoc_jemalloc-e8edd0fd.rlib" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/liblibc-e8edd0fd.rlib" "/home/infinity0/rust/armv7-unknown-linux-gnueabihf/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libcore-e8edd0fd.rlib" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util" "-Wl,-z,relro" "-l" "compiler-rt"
note: /usr/bin/ld: /home/infinity0/rust/armv7-unknown-linux-gnueabihf/test/run-make/relocation-model.stage2-armv7-unknown-linux-gnueabihf/foo.0.o: relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/home/infinity0/rust/armv7-unknown-linux-gnueabihf/test/run-make/relocation-model.stage2-armv7-unknown-linux-gnueabihf/foo.0.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

error: aborting due to previous error
make[3]: *** [others] Error 101
