rust
// `main` scope
//      vvvvvvv
pub mod foo_mod {
    // `main` scope
    //     vvv
    pub fn bar() {
        // I want this to be in `foo_mod!` scope
        baz();
    }

    // Perhaps I want this private to `foo_mod!` but
    // `pub` because it's used by... other modules generated by `foo_mod!`,
    // or something else silly.
    pub fn baz() { ... }
}
