plain
[00:48:55] ............................................................................ii......................
[00:49:42] ........................................i....................................................i.ii...
[00:49:53] ............................test [run-pass] run-pass/saturating-float-casts.rs has been running for over 60 seconds
[00:50:21] ........................................................................
[00:50:40] .iiiiiii............................................................................................
[00:51:18] ....................................................................................................
[00:51:34] .........................................................................
[00:51:34] test result: ok. 2954 passed; 0 failed; 19 ignored; 0 measured; 0 filtered out
[00:51:34] 
---
[00:52:30] ...........i........................................................................................
[00:52:36] ....................................................................................................
[00:52:45] ....................................................................................................
[00:52:53] ....................................................................................................
[00:53:02] ..F.................................................................................................
[00:53:22] ...i................................................................................................
[00:53:30] .......i..ii........................................................................................
[00:53:38] ....................................................................................................
[00:53:46] ....................................................................................................
---
[00:54:28] 
[00:54:28] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:488:22
[00:54:28] 
[00:54:28] 
[00:54:28] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/compile-fail" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:54:28] 
[00:54:28] 
[00:54:28./obj/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib
75028 ./obj/build/x86_64-unknown-linux-gnu/stage0-tools/release
---
60840 ./src/llvm-emscripten/lib
56092 ./obj/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin
55348 ./obj/build/x86_64-unknown-linux-gnu/stage0-rustc/release
53744 ./obj/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/incremental/syntax-284je5yviillk
53740 ./obj/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/incremental/syntax-284je5yviillk/s-f0jqq56h6t-1v9tvdt-1g01ezlirjn0e
48604 ./obj/build/x86_64-unknown-linux-gnu/stage0/bin
47832 ./obj/build/x86_64-unknown-linux-gnu/stage0-std
46904 ./src/test
46820 ./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps
