plain
Resolving deltas: 100% (607334/607334), completed with 4807 local objects.
---
[00:00:46] configure: rust.quiet-tests     := True
---
[00:41:22] ..........................................................................i.........................
[00:41:29] .................i..................................................................................
---
[00:42:09] .............................................................................................i......
[00:42:16] .................................................................i..................................
---
[00:43:14] .............................................i......................................................
---
[00:47:18] .............................i......................................................................
[00:47:34] ..............................................................i.....................................
[00:47:50] ...............................................i....................................................
[00:48:10] ....................................................................................................
[00:48:32] ....................................................................................................
[00:48:53] ....................................................................................................
[00:49:19] .i...............................................................................................i..
[00:49:46] ................................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:49:57] ....................
[00:50:28] ....................................................................................................
[00:51:03] ..............................................................ii....................................
[00:51:53] .........................i....................................................i.ii..................
[00:52:33] ...............................F......................................................iiiiiii.......
---
[00:54:09] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/run-pass/svh-add-nothing.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass" "--target=x86_64-unknown-linux-gnu" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/svh-add-nothing.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/svh-add-nothing.stage2-x86_64-unknown-linux-gnu.aux"
---
[00:54:09] error[E0460]: found possibly newer version of crate `a` which `b` depends on
[00:54:09]   --> /checkout/src/test/run-pass/svh-add-nothing.rs:19:1
[00:54:09]    |
[00:54:09] 19 | extern crate b;
[00:54:09]    | ^^^^^^^^^^^^^^^
[00:54:09]    |
[00:54:09]    = note: perhaps that crate needs to be recompiled?
[00:54:09]    = note: the following crate versions were found:
[00:54:09]            crate `a`: /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/svh-add-nothing.stage2-x86_64-unknown-linux-gnu.aux/liba.so
[00:54:09]            crate `b`: /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/svh-add-nothing.stage2-x86_64-unknown-linux-gnu.aux/libb.so
---
[00:54:09] thread '[run-pass] run-pass/svh-add-nothing.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2901:9
---
$ dmesg | grep -i kill
[   12.944780] init: failsafe main process (1094) killed by TERM signal
