plain
[00:00:49] configure: rust.quiet-tests     := True
---
[00:46:40] ...............................................................................i....................
[00:46:46] ......................i.............................................................................
---
[00:47:28] ..i...........................................................................i.....................
---
[00:47:50] travis_fold:start:test_ui_nll
travis_time:start:test_ui_nll
Check compiletest suite=ui mode=ui compare_mode=nll (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:47:51]
[00:47:51] running 1324 tests
[00:47:57] ....................................F..........................................i....................
[00:48:05] ......................i...................F....F..F..F..............................................
[00:48:09] ....................................................................................................
[00:48:14] ......................F.............................................................................
[00:48:19] ....................................................................................................
[00:48:25] ....................................................................................................
[00:48:32] ....................................................................................................
[00:48:39] ..............................F.....................................................................
[00:48:46] ....................................................................................................
[00:48:54] ..i...........................................................................i.....................
[00:49:00] ......................................................................................FF............
[00:49:10] ....................F..F............................................................................
[00:49:21] ....................................................................................................
[00:49:37] ........................
[00:49:37] failures:
[00:49:37]
[00:49:37] ---- [ui (nll)] ui/borrowck/issue-45983.rs stdout ----
[00:49:37]  diff of stderr:
[00:49:37]
[00:49:37] 16 LL |     give_any(|y| x = Some(y));
[00:49:37] 17    |                  ^^^^^^^^^^^ cannot mutate
[00:49:37] 18    |
[00:49:37] -    = note: Value not mutable causing this error: `x`
[00:49:37] +    = note: the value which is causing this path not to be mutable is...: `x`
[00:49:37] 20
[00:49:37] 21 error[E0596]: cannot borrow immutable item `x` as mutable
[00:49:37] 22   --> $DIR/issue-45983.rs:17:14
[00:49:37]
[00:49:37]
[00:49:37] The actual stderr differed from the expected stderr.
[00:49:37] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/issue-45983.stderr
[00:49:37] To update references, run this command from build directory:
[00:49:37] /checkout/src/test/ui/update-references.sh '/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui' 'borrowck/issue-45983.rs'
[00:49:37]
[00:49:37] error: 1 errors occurred comparing output.
[00:49:37] status: exit code: 101
[00:49:37] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/borrowck/issue-45983.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/issue-45983.stage2-x86_64-unknown-linux-gnu" "-Znll" "-Zborrowck=mir" "-Ztwo-phase-borrows" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/issue-45983.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
---
[00:49:37] {"message":"not reporting region error due to -Znll","code":null,"level":"warning","spans":[{"file_name":"/checkout/src/test/ui/borrowck/issue-45983.rs","byte_start":585,"byte_end":586,"line_start":17,"line_end":17,"column_start":27,"column_end":28,"is_primary":true,"text":[{"text":"    give_any(|y| x = Some(y));","highlight_start":27,"highlight_end":28}],"label":null,"suggested_replacement":null,"expansion":null}],"children":[],"rendered":"warning: not reporting region error due to -Znll\n  --> /checkout/src/test/ui/borrowck/issue-45983.rs:17:27\n   |\nLL |     give_any(|y| x = Some(y));\n   |                           ^\n\n"}
[00:49:37] {"message":"free region `` does not outlive free region `'_#2r`","code":null,"level":"error","spans":[{"file_name":"/checkout/src/test/ui/borrowck/issue-45983.rs","byte_start":585,"byte_end":586,"line_start":17,"line_end":17,"column_start":27,"column_end":28,"is_primary":true,"text":[{"text":"    give_any(|y| x = Some(y));","highlight_start":27,"highlight_end":28}],"label":null,"suggested_replacement":null,"expansion":null}],"children":[],"rendered":"error: free region `` does not outlive free region `'_#2r`\n  --> /checkout/src/test/ui/borrowck/issue-45983.rs:17:27\n   |\nLL |     give_any(|y| x = Some(y));\n   |                           ^\n\n"}
[00:49:37] {"message":"cannot assign to immutable item `x`","code":{"code":"E0594","explanation":null},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/borrowck/issue-45983.rs","byte_start":576,"byte_end":587,"line_start":17,"line_end":17,"column_start":18,"column_end":29,"is_primary":true,"text":[{"text":"    give_any(|y| x = Some(y));","highlight_start":18,"highlight_end":29}],"label":"cannot mutate","suggested_replacement":null,"expansion":null}],"children":[{"message":"the value which is causing this path not to be mutable is...: `x`","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"error[E0594]: cannot assign to immutable item `x`\n  --> /checkout/src/test/ui/borrowck/issue-45983.rs:17:18\n   |\nLL |     give_any(|y| x = Some(y));\n   |                  ^^^^^^^^^^^ cannot mutate\n   |\n   = note: the value which is causing this path not to be mutable is...: `x`\n\n"}
[00:49:37] {"message":"cannot borrow immutable item `x` as mutable","code":{"code":"E0596","explanation":"\nThis error occurs because you tried to mutably borrow a non-mutable variable.\n\nExample of erroneous code:\n\n