plain
[00:00:47] configure: rust.quiet-tests     := True
---
[00:44:50] .................................................................................i..................
[00:44:56] ........................i...........................................................................
---
[00:45:37] ........................i...........................................................................
[00:45:43] i...................................................................................................
[00:45:50] ..............ii....................................................................................
---
[00:46:35] .............................................i......................................................
---
[00:50:27] ..............................i.....................................................................
[00:50:41] ...............................................................i....................................
[00:50:56] .................................................i..................................................
[00:51:16] ....................................................................................................
[00:51:38] ....................................................................................................
[00:51:59] ....................................................................................................
[00:52:24] .......i............................................................................................
[00:52:52] ...i...................................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:52:59] .............
[00:53:31] ....................................................................................................
[00:54:02] .....................................................................ii.............................
[00:54:53] ................................i....................................................i.ii...test [run-pass] run-pass/saturating-float-casts.rs has been running for over 60 seconds
[00:54:56] ........
[00:55:38] .............................................................................................iiiiiii
---
[00:57:51] ...................i............................................................ii.iii..............
[00:57:59] ....................................................................................................
[00:58:06] ........i..............................i............................................................
[00:58:14] ....................................................................................................
[00:58:20] ..........i.........................................................................................
[00:58:28] ....................................................................................................
[00:58:38] ....................................................................................................
[00:58:48] ....................................................................................................
[00:58:58] ....................................................................................................
[00:59:12] ....................................................................................................
[00:59:20] ...i................................................................................................
[00:59:29] .......i..ii........................................................................................
[00:59:39] ....................................................................................................
[00:59:48] ....................................................................................................
[00:59:58] .........................................................................i..........................
[01:00:08] ...................i................................................................................
---
[01:00:42] ............................i.......................................................................
[01:00:43] .....................................................F..............i...............................
[01:00:44] ................i...........................................F...........
[01:00:44] failures:
[01:00:44]
[01:00:44] ---- [parse-fail] parse-fail/lex-bad-numeric-literals.rs stdout ----
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/lex-bad-numeric-literals.rs:15: expected error not found: octal float literal is not supported
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/lex-bad-numeric-literals.rs:25: expected error not found: hexadecimal float literal is not supported
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/lex-bad-numeric-literals.rs:26: expected error not found: int literal is too large
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/lex-bad-numeric-literals.rs:27: expected error not found: int literal is too large
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/lex-bad-numeric-literals.rs:28: expected error not found: no valid digits
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/lex-bad-numeric-literals.rs:29: expected error not found: no valid digits
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/lex-bad-numeric-literals.rs:30: expected error not found: no valid digits
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/lex-bad-numeric-literals.rs:31: expected error not found: no valid digits
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/lex-bad-numeric-literals.rs:32: expected error not found: no valid digits
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/lex-bad-numeric-literals.rs:33: expected error not found: octal float literal is not supported
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/lex-bad-numeric-literals.rs:34: expected error not found: octal float literal is not supported
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/lex-bad-numeric-literals.rs:35: expected error not found: binary float literal is not supported
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/lex-bad-numeric-literals.rs:36: expected error not found: binary float literal is not supported
[01:00:44]
[01:00:44] error: 0 unexpected errors found, 13 expected errors not found
[01:00:44] status: exit code: 101
[01:00:44] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/parse-fail/lex-bad-numeric-literals.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/parse-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "jsoed"
[01:00:44]     }
[01:00:44] ]
[01:00:44]
[01:00:44] thread '[parse-fail] parse-fail/lex-bad-numeric-literals.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:1254:13
[01:00:44] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:00:44]
[01:00:44] ---- [parse-fail] parse-fail/unicode-chars.rs stdout ----
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/unicode-chars.rs:14: unexpected help message: '14:14: 14:15: Unicode character ';' (Greek Question Mark) looks like ';' (Semicolon), but it is not'
[01:00:44]
[01:00:44] error: /checkout/src/test/parse-fail/unicode-chars.rs:14: expected help message not found: unicode character ';' (Greek Question Mark) looks like ';' (Semicolon), but it's not
[01:00:44]
[01:00:44] error: 1 unexpected errors found, 1 expected errors not found
[01:00:44] status: exit code: 101
[01:00:44] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/parse-fail/unicode-chars.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/parse-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/parse-fail/unicode-chars.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Z" "parse-only" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/parse-fail/unicode-chars.stage2-x86_64-unknown-linux-gnu.aux"
[01:00:44] unexpected errors (from JSON output): [
[01:00:44]     Error {
[01:00:44]         line_num: 14,
[ei3hhuv/s-f05hjrxqjv-lta4um-3ssff2uugm5rt
109936 ./obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu
109932 ./obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release
106040 ./obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps
102812 ./obj/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends
102508 ./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental/core-31lccp6wy7orz
102504 ./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental/core-31lccp6wy7orz/s-f05imq1viy-1b9jmn-bcs1sclq83s
100744 ./obj/build/bootstrap/debug/incremental/bootstrap-zki88qpb4pjm
100740 ./obj/build/bootstrap/debug/incremental/bootstrap-zki88qpb4pjm/s-f05ip9ov4z-wrkc4m-2fm8hlvdg42qh
---
55760 ./obj/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/incremental/syntax-33oa6nnkk1g08/s-f05iogumvd-1h40n44-2ne0q77addm7i
