plain
Resolving deltas: 100% (616833/616833), completed with 4913 local objects.
---
[00:00:44] configure: rust.quiet-tests     := True
---
[00:40:35] .................................................................................i..................
[00:40:41] ........................i...........................................................................
---
[00:41:20] ......................i...........................................................................i.
[00:41:26] ....................................................................................................
[00:41:32] ............ii......................................................................................
[00:41:39] .............................................................................................i......
---
[00:42:13] .............................................i......................................................
---
[00:45:47] ..............................i.....................................................................
[00:46:00] ...............................................................i....................................
[00:46:14] ..................................................i.................................................
[00:46:32] ....................................................................................................
[00:46:51] ....................................................................................................
[00:47:11] ....................................................................................................
[00:47:34] .......i............................................................................................
[00:48:05] ...i.............................................................................................test [run-pass] run-pass/mir_heavy_promoted.rs has been running for over 60 seconds
[00:48:06] ...
[00:48:35] ....................................................................................................
[00:49:04] .....................................................................ii.............................
[00:49:53] ................................i....................................................i.ii...........
[00:49:56] ....test [run-pass] run-pass/saturating-float-casts.rs has been running for over 60 seconds
[00:50:32] .........................................................................................iiiiiii
---
[00:52:41] ....................i............................................................ii.iii.............
[00:52:48] ....................................................................................................
[00:52:55] .........i..............................i...........................................................
[00:53:02] ....................................................................................................
[00:53:08] ...........i........................................................................................
[00:53:16] ....................................................................................................
[00:53:25] ....................................................................................................
[00:53:35] ....................................................................................................
[00:53:44] .....F......................................................................................F.......
[00:53:56] ....................................................................................................
[00:54:04] ....i...............................................................................................
[00:54:12] ........i..ii.......................................................................................
[00:54:22] ....................................................................................................
[00:54:30] ....................................................................................................
[00:54:39] ..........................................................................i.........................
[00:54:49] ....................i...............................................................................
---
[00:55:18] error: /checkout/src/test/compile-fail/issue-43105.rs:13: unexpected error: '13:17: 13:22: calls in constants are limited to constant functions, tuple structs and tuple variants [E0015]'
[00:55:18]
[00:55:18] error: /checkout/src/test/compile-fail/issue-43105.rs:13: expected error not found: calls in constants are limited to constant functions, struct and enum constructors
[00:55:18]
[00:55:18] error: 1 unexpected errors found, 1 expected errors not found
[00:55:18] status: exit code: 101
[00:55:18] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/issue-43105.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/issue-43105.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/issue-43105.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[00:55:18] unexpected errors (from JSON output): [
[00:55:18]     Error {
[00:55:18]         line_num: 13,
[00:55:18]         kind: Some(
[00:55:18]             Error
[00:55:18]         ),
[00:55:18]     pile-fail/issue32829.rs:45: expected error not found: calls in statics are limited to constant functions, struct and enum
[00:55:18]
[00:55:18] error: /checkout/src/test/compile-fail/issue32829.rs:69: expected error not found: calls in statics are limited to constant functions, struct and enum
[00:55:18]
[00:55:18] error: 3 unexpected errors found, 3 expected errors not found
[00:55:18] status: exit code: 101
[00:55:18] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/issue32829.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/issue32829.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/issue32829.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[00:55:18] unexpected errors (from JSON output): [
[00:55:18]     Error {
[00:55:18]         line_num: 21,
[00:55:18]         kind: Some(
[00:55:18]             Error
[00:55:18]         ),
[00:55:18]         msg: "21:9: 21:18: calls in constants are limited to constant functions, tuple structs and tuple variants [E0015]"
---
[00:55:18]         msg: "45:9: 45:18: calls in statics are limited to constant functions, tuple structs and tuple variants [E0015]"
---
[00:55:18]         msg: "69:9: 69:18: calls in statics are limited to constant functions, tuple structs and tuple variants [E0015]"
---
[00:55:18]         msg: "calls in constants are limited to constant functions, struct and enum"
---
[00:55:18]         msg: "calls in statics are limited to constant functions, struct and enum"
---
[00:55:18]         msg: "calls in statics are limited to constant functions, struct and enum"
---
[00:55:18] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/compile-fail" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:55:18] expected success, got: exit code: 101
[00:55:18]
[00:55:18]
[00:55:18] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:55:18] Build completed unsuccessfully in 0:15:48
[00:55:18] Makefile:58: recipe for target 'check' failed
[00:55:18] make: *** [check] Error 1
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
