plain
[00:44:13] .......................................................i............................................
[00:44:17] ...........................................................................ii.......................
[00:44:23] ....................................................................................................
[00:44:29] .....................................................................................i..............
[00:44:32] ...iiiiiiiii...................................................
[00:44:32] 
[00:44:32] travis_fold:start:test_ui_nll
travis_time:start:test_ui_nll
Check compiletest suite=ui mode=ui compare_mode=nll (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
---
[00:45:20] .......................................................i............................................
[00:45:24] ...........................................................................ii.......................
[00:45:30] ....................................................................................................
[00:45:35] .....................................................................................i..............
[00:45:38] ...iiiiiiiii...................................................
[00:45:38] 
[00:45:38]  finished in 65.792
[00:45:38] travis_fold:end:test_ui_nll

---
[00:54:14] .......................i............................................................................
[00:54:18] ..............................................................................................i.....
[00:54:22] ....................................................................................................
[00:54:28] ....................................................................................................
[00:54:33] ......................................F.............................................................
[00:54:44] ....................................................................................................
[00:54:51] ....................................................................................................
[00:54:56] ...i................................................................................................
[00:55:02] ..i..ii.............................................................................................
---
[00:55:36] ---- [compile-fail] compile-fail/issue-30240-b.rs stdout ----
[00:55:36] 
[00:55:36] error: compile-fail test compiled successfully!
[00:55:36] status: exit code: 0
[00:55:36] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/issue-30240-b.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/issue-30240-b/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/issue-30240-b/auxiliary" "-A" "unused"
[00:55:36] ------------------------------------------
[00:55:36] 
[00:55:36] ------------------------------------------
[00:55:36] stderr:
---
[00:55:36] 
[00:55:36] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:498:22
[00:55:36] 
[00:55:36] 
[00:55:36] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/compile-fail" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:55:36] 
[00:55:36] 
[00:55:36] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:55:36] Build completed unsuccessfully in 0:13:40
[00:55:36] Build completed unsuccessfully in 0:13:40
[00:55:36] Makefile:58: recipe for target 'check' failed
[00:55:36] make: *** [check] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:0538472e
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
