plain
[00:00:00] +src/ci/init_repo.sh . /home/travis/rustsrc
[00:00:00] travis_fold:start:init_repo
travis_time:start:059c8820
rm 'src/llvm'
[00:00:00] Attempting with retry: sh -c rm -f download-src-llvm.tar.gz &&         curl -sSL -o download-src-llvm.tar.gz https://github.com/rust-lang/llvm/archive/9ad4b7e8d7d1618fc9686aa8d3d0b4de3b7a6f36.tar.gz
[00:00:00] Attempting with retry: sh -c rm -f download-src-doc-book.tar.gz &&         curl -sSL -o download-src-doc-book.tar.gz https://github.com/rust-lang/book/archive/36d65d00164d1750f6fa7f8b0f52dabc3fea500b.tar.gz
[00:00:00] rm 'src/doc/rust-by-example'
[00:00:00] Attempting with retry: sh -c rm -f download-src-doc-rust-by-example.tar.gz &&         curl -sSL -o download-src-doc-rust-by-example.tar.gz https://github.com/rust-lang/rust-by-example/archive/eebda16e4b45f2eed4310cf7b9872cc752278163.tar.gz
[00:00:00] rm 'src/llvm-emscripten'
---
[00:43:06] ....................................................................................................
[00:43:09] ....................................................................................................
[00:43:12] ....................................................................................................
[00:43:15] ....................................................................................................
[00:43:20] ..................................................F.................................................
[00:43:28] ....................................................................................................
[00:43:33] ............................................................................i.......................
[00:43:38] .....................................................i..............................................
[00:43:42] .........................................................................ii.........................
[00:43:42] .........................................................................ii.........................
[00:43:48] ....................................................................................................
[00:43:54] ...................................................................................i................
ss `--test-args impl-trait/impl-generic-mismatch.rs`
[00:43:56] error: 1 errors occurred comparing output.
[00:43:56] status: exit code: 101
[00:43:56] status: exit code: 101
[00:43:56] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/impl-trait/impl-generic-mismatch.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/impl-generic-mismatch/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/impl-generic-mismatch/auxiliary" "-A" "unused"
[00:43:56] ------------------------------------------
[00:43:56] 
[00:43:56] ------------------------------------------
[00:43:56] stderr:
[00:43:56] stderr:
[00:43:56] ------------------------------------------
[00:43:56] {"message":"method `foo` has incompatible signature for trait","code":{"code":"E0643","explanation":"\nThis error indicates that there is a mismatch between generic parameters and\nimpl Trait parameters in a trait declaration versus its impl.\n\n