plain
[00:45:09] ......................................................................i.............................
[00:45:13] ....................................................................................................
[00:45:19] ....................................................................................................
[00:45:25] ....................................................................................................
[00:45:29] ..i.................iiiiiiiii...................................................
[00:45:29] 
[00:45:29] travis_fold:start:test_ui_nll
travis_time:start:test_ui_nll
Check compiletest suite=ui mode=ui compare_mode=nll (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
---
[00:46:17] ......................................................................i.............................
[00:46:22] ....................................................................................................
[00:46:27] ....................................................................................................
[00:46:32] ....................................................................................................
[00:46:36] ..i.................iiiiiiiii...................................................
[00:46:36] 
[00:46:36]  finished in 67.009
[00:46:36] travis_fold:end:test_ui_nll

---
travis_time:start:test_run-pass
Check compiletest suite=run-pass mode=run-pass (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:46:36] 
[00:46:36] running 3017 tests
[00:46:50] .............F......................................................................................
[00:47:19] ....................................................................................................
[00:47:32] ....................................................................................................
[00:47:44] ....................................................................................................
[00:48:03] ....................................................................................................
---
[00:54:57] 
[00:54:57] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:498:22
[00:54:57] 
[00:54:57] 
[00:54:57] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/run-pass" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "run-pass" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:54:57] 
[00:54:57] 
[00:54:57] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:54:57] Build completed unsuccessfully in 0:12:00
[00:54:57] Build completed unsuccessfully in 0:12:00
[00:54:57] Makefile:58: recipe for target 'check' failed
[00:54:57] make: *** [check] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:0d807eb0
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
