plain
[00:55:16] ....................................................................................................
[00:55:22] ......................................................................................i.............
[00:55:28] ...............................................ii.iii...............................................
[00:55:33] ..............................................................................i.....................
[00:55:38] .......................i.............................F..............................................
[00:55:47] ....................................................................................................
[00:55:53] ....................................................................................................
[00:55:58] ....................................................................................................
[00:56:05] ....................................................................................................
[00:56:05] ....................................................................................................
[00:56:11] ....................................................................................................
[00:56:18] ....................................................................................................
[00:56:24] ...i................................................................................................
[00:56:30] ..i..ii.............................................................................................
[00:56:38] ....................................................................................................
[00:56:44] ........F...........................................................................................
[00:56:53] ..............................i.....................................................................
[00:56:59] ....................................................................................................
[00:57:03] ....................................................................................................
[00:57:07] ....................................................................................................
[00:57:07] ....................................................................................................
[00:57:09] ..........................
[00:57:09] failures:
[00:57:09] 
[00:57:09] ---- [compile-fail] compile-fail/impl-trait/where-allowed.rs stdout ----
[00:57:09] 
[00:57:09] error: compiler panicked
[00:57:09] status: exit code: 101
[00:57:09] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/impl-trait/where-allowed.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/impl-trait/where-allowed/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/impl-trait/where-allowed/auxiliary" "-A" "unused"
[00:57:09] ------------------------------------------
[00:57:09] 
[00:57:09] ------------------------------------------
[00:57:09] stderr:
[00:57:09] stderr:
[00:57:09] ------------------------------------------
[00:57:09] {"message":"nested `impl Trait` is not allowed","code":{"code":"E0666","explanation":null},"level":"error","spans":[{"file_name":"/checkout/src/test/compile-fail/impl-trait/where-allowed.rs","byte_start":2268,"byte_end":2287,"line_start":60,"line_end":60,"column_start":43,"column_end":62,"is_primary":false,"text":[{"text":"fn in_impl_Fn_parameter_in_parameters(_: &impl Fn(impl Debug)) { panic!() }","highlight_start":43,"highlight_end":62}],"label":"outer `impl Trait`","suggested_replacement":null,"suggestion_applicability":null,"expansion":null},{"file_name":"/checkout/src/test/compile-fail/impl-trait/where-allowed.rs","byte_start":2276,"byte_end":2286,"line_start":60,"line_end":60,"column_start":51,"column_end":61,"is_primary":true,"text":[{"text":"fn in_impl_Fn_parameter_in_parameters(_: &impl Fn(impl Debug)) { panic!() }","highlight_start":51,"highlight_end":61}],"label":"nested `impl Trait` here","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error[E0666]: nested `impl Trait` is not allowed\n  --> /checkout/src/test/compile-fail/impl-trait/where-allowed.rs:60:51\n   |\nLL | fn in_impl_Fn_parameter_in_parameters(_: &impl Fn(impl Debug)) { panic!() }\n   |                                           --------^^^^^^^^^^-\n   |                                           |       |\n   |                                           |       nested `impl Trait` here\n   |                                           outer `impl Trait`\n\n"}
[00:57:09] {"message":"nested `impl Trait` is not allowed","code":{"code":"E0666","explanation":null},"level":"error","spans":[{"file_name":"/checkout/src/test/compile-fail/impl-trait/where-allowed.rs","byte_start":2682,"byte_end":2701,"line_start":69,"line_end":69,"column_start":49,"column_end":68,"is_primary":false,"text":[{"text":"fn in_impl_Fn_parameter_in_return() -> &'static impl Fn(impl Debug) { panic!() }","highlight_start":49,"highlight_end":68}],"label":"outer `impl Trait`","suggested_replacement":null,"suggestion_applicability":null,"expansion":null},{"file_name":"/checkout/src/test/compile-fail/impl-trait/where-allowed.rs","byte_start":2690,"byte_end":2700,"line_start":69,"line_end":69,"column_start":57,"column_end":67,"is_primary":true,"text":[{"text":"fn in_impl_Fn_parameter_in_return() -> &'static impl Fn(impl Debug) { panic!() }","highlight_start":57,"highlight_end":67}],"label":"nested `impl Trait` here","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error[E0666]: nested `impl Trait` is not allowed\n  --> /checkout/src/test/compile-fail/impl-trait/where-allowed.rs:69:57\n   |\nLL | fn in_impl_Fn_parameter_in_return() -> &'static impl Fn(impl Debug) { panic!() }\n   |                                                 --------^^^^^^^^^^-\n   |                                                 |       |\n   |                                                 |       nested `impl Trait` here\n   |                                                 outer `impl Trait`\n\n"}
[00:57:09] {"message":"`impl Trait` not allowed outside of function and inherent method return types","code":{"code":"E0562","explanation":"\nAbstract return types (written `impl Trait` for some trait `Trait`) are only\nallowed as function return types.\n\nErroneous code example:\n\n