plain
[00:43:04] ....................................................................................................
[00:43:09] i........................................................................i..........................
[00:43:11] ....................................................................................................
[00:43:14] ....................................................................................................
[00:43:16] ...F................................................................................................
[00:43:21] ....................................................................................................
[00:43:24] ....................................................................................................
[00:43:27] ..........................................................................i.........................
[00:43:29] .............................................................................i......................
---
[00:43:43] ....................................................................................................
[00:43:47] ....................................................................................................
[00:43:50] .......................................i............................................................
[00:43:53] .............................i......................................................................
[00:43:57] .........................................F..........................................................
[00:44:04] ................................................i...................................................
[00:44:06] ..................................i....
[00:44:06] failures:
[00:44:06] 
[00:44:06] 
[00:44:06] ---- [ui] ui/error-codes/E0423.rs stdout ----
[00:44:06] diff of stderr:
[00:44:06] 
[00:44:06] 30    |
[00:44:06] 31 LL |     if let S { x: _x, y: 2 } = S { x: 1, y: 2 } { println!("Ok"); }
[00:44:06] 32    |                                ^ did you mean `(S { /* fields */ })`?
[00:44:06] + help: possible better candidate is found in another module, you can import it into scope
[00:44:06] +    |
[00:44:06] + LL | use std::time::S;
[00:44:06] 33 
[00:44:06] 33 
[00:44:06] 34 error[E0423]: expected value, found struct `T`
[00:44:06] 35   --> $DIR/E0423.rs:25:8
[00:44:06] 
[00:44:06] The actual stderr differed from the expected stderr.
[00:44:06] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/error-codes/E0423/E0423.stderr
[00:44:06] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/error-codes/E0423/E0423.stderr
[00:44:06] To update references, rerun the tests and pass the `--bless` flag
[00:44:06] To only update this specific test, also pass `--test-args error-codes/E0423.rs`
[00:44:06] error: 1 errors occurred comparing output.
[00:44:06] status: exit code: 1
[00:44:06] status: exit code: 1
[00:44:06] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/error-codes/E0423.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/error-codes/E0423/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/error-codes/E0423/auxiliary" "-A" "unused"
[00:44:06] ------------------------------------------
[00:44:06] 
[00:44:06] ------------------------------------------
[00:44:06] stderr:
[00:44:06] stderr:
[00:44:06] ------------------------------------------
[00:44:06] {"message":"expected type, found `1`","code":null,"level":"error","spans":[{"file_name":"/checkout/src/test/ui/error-codes/E0423.rs","byte_start":670,"byte_end":671,"line_start":22,"line_end":22,"column_start":39,"column_end":40,"is_primary":true,"text":[{"text":"    if let S { x: _x, y: 2 } = S { x: 1, y: 2 } { println!(\"Ok\"); }","highlight_start":39,"highlight_end":40}],"label":"expecting a type here because of type ascription","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: expected type, found `1`\n  --> /checkout/src/test/ui/error-codes/E0423.rs:22:39\n   |\nLL |     if let S { x: _x, y: 2 } = S { x: 1, y: 2 } { println!(\"Ok\"); }\n   |                                       ^ expecting a type here because of type ascription\n\n"}
[00:44:06] {"message":"expected expression, found `==`","code":null,"level":"error","spans":[{"file_name":"/checkout/src/test/ui/error-codes/E0423. as a\nfunction:\n\n