plain
[00:47:22] ....................................................................................................
[00:47:25] ....................................................................................................
[00:47:28] ....................................................................................................
[00:47:32] ....................................................................................................
[00:47:35] ..................................................F.................................................
[00:47:42] ............................................i.......................................................
[00:47:45] ...................................i................................................................
[00:47:49] ....................................................................................................
[00:47:53] ....................................................................................................
[00:47:53] ....................................................................................................
[00:47:57] .....................................................i..............................................
tage2/bin/rustc" "/checkout/src/test/ui/issue-51116.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issue-51116/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issue-51116/auxiliary" "-A" "unused"
[00:47:59] ------------------------------------------
[00:47:59] 
[00:47:59] ------------------------------------------
[00:47:59] stderr:
[00:47:59] stderr:
[00:47:59] ------------------------------------------
[00:47:59] {"message":"type annotations needed","code":{"code":"E0282","explanation":"\nThis error indicates that type inference did not result in one unique possible\ntype, and extra information is required. In most cases this can be provided\nby adding a type annotation. Sometimes you need to specify a generic type\nparameter manually.\n\nA common example is the `collect` method on `Iterator`. It has a generic type\nparameter with a `FromIterator` bound, which for a `char` iterator is\nimplemented by `Vec` and `String` among others. Consider the following snippet\nthat reverses the characters of a string:\n\n