plain
[01:10:08] travis_fold:end:stage0-linkchecker

[01:10:08] travis_time:end:stage0-linkchecker:start=1532180932500084864,finish=1532180935123349805,duration=2623264941

[01:10:08] std/char/struct.ToUppercase.html:72: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:08] std/char/struct.ToUppercase.html:88: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:08] std/char/struct.DecodeUtf16Error.html:27: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:08] std/char/struct.EscapeDefault.html:74: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:08] std/char/struct.EscapeDefault.html:90: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:08] std/char/struct.ToLowercase.html:72: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:08] std/char/struct.ToLowercase.html:88: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:08] std/char/struct.DecodeUtf16.html:69: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:08] std/char/struct.DecodeUtf8.html:72: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:08] std/char/struct.CharTryFromError.html:26: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:09] std/char/struct.EscapeUnicode.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:09] std/char/struct.EscapeUnicode.html:91: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:09] std/char/struct.ParseCharError.html:26: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:09] std/char/struct.EscapeDebug.html:74: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:09] std/char/struct.EscapeDebug.html:90: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:10] std/num/struct.Wrapping.html:4677: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:10] std/num/struct.NonZeroU32.html:50: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:10] std/num/struct.NonZeroU8.html:50: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:10] std/num/struct.NonZeroU16.html:50: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:10] std/num/struct.NonZeroUsize.html:50: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:10] std/num/struct.NonZeroU128.html:50: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:10] std/num/struct.ParseFloatError.html:28: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:10] std/num/struct.ParseIntError.html:32: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:10] std/num/struct.NonZeroU64.html:50: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:10] std/num/struct.TryFromIntError.html:1: broken link fragment `#impl-From` pointing to `std/num/struct.TryFromIntError.html`
[01:10:10] std/num/struct.TryFromIntError.html:24: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:10] std/future/struct.FutureObj.html:1: broken link fragment `#impl-From` pointing to `std/future/struct.FutureObj.html`
[01:10:10] std/future/struct.LocalFutureObj.html:1: broken link fragment `#impl-From` pointing to `std/future/struct.LocalFutureObj.html`
[01:10:11] std/io/struct.IntoInnerError.html:1: broken link fragment `#impl-From` pointing to `std/io/struct.IntoInnerError.html`
[01:10:11] std/io/struct.IntoInnerError.html:88: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:11] std/io/enum.CharsError.html:36: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:11] std/io/struct.Error.html:1: broken link fragment `#impl-From` pointing to `std/io/struct.Error.html`
[01:10:11] std/io/struct.Error.html:202: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:11] std/io/struct.Lines.html:69: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/io/enum.ErrorKind.html:1: broken link fragment `#impl-From` pointing to `std/io/enum.ErrorKind.html`
[01:10:11] std/io/struct.Split.html:70: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/io/struct.Chars.html:72: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/io/struct.Bytes.html:69: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/string/struct.FromUtf8Error.html:78: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:11] std/string/enum.ParseError.html:33: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:11] std/string/struct.FromUtf16Error.html:28: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:11] std/string/struct.Drain.html:74: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.RepeatWith.html:72: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Flatten.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Peekable.html:105: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Scan.html:72: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Once.html:76: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Skip.html:78: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Fuse.html:142: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.TakeWhile.html:72: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Cloned.html:78: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Rev.html:78: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Chain.html:76: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Map.html:111: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Repeat.html:74: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.FilterMap.html:76: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.StepBy.html:74: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Enumerate.html:83: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.SkipWhile.html:72: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Filter.html:76: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Inspect.html:79: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Take.html:74: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.FlatMap.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Empty.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Zip.html:78: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:11] std/iter/struct.Cycle.html:72: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:12] std/ptr/struct.NonNull.html:1: broken link fragment `#impl-From` pointing to `std/ptr/struct.NonNull.html`
[01:10:12] std/sync/enum.TryLockError.html:1: broken link fragment `#impl-From` pointing to `std/sync/enum.TryLockError.html`
[01:10:12] std/sync/enum.TryLockError.html:29: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:12] std/sync/struct.Arc.html:1: broken link fragment `#impl-From` pointing to `std/sync/struct.Arc.html`
[01:10:12] std/sync/struct.Arc.html:1: broken link fragment `#impl-Borrow` pointing to `std/sync/struct.Arc.html`
[01:10:12] std/sync/struct.Arc.html:411: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:12] std/sync/struct.MutexGuard.html:27: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:12] std/sync/struct.Mutex.html:1: broken link fragment `#impl-From` pointing to `std/sync/struct.Mutex.html`
[01:10:12] std/sync/atomic/struct.AtomicI64.html:1: broken link fragment `#impl-From` pointing to `std/sync/atomic/struct.AtomicI64.html`
[01:10:12] std/sync/atomic/struct.AtomicU8.html:1: broken link fragment `#impl-From` pointing to `std/sync/atomic/struct.AtomicU8.html`
[01:10:12] std/sync/atomic/struct.AtomicI32.html:1: broken link fragment `#impl-From` pointing to `std/sync/atomic/struct.AtomicI32.html`
[01:10:12] std/sync/atomic/struct.AtomicU16.html:1: broken link fragment `#impl-From` pointing to `std/sync/atomic/struct.AtomicU16.html`
[01:10:12] std/sync/atomic/struct.AtomicPtr.html:1: broken link fragment `#impl-From` pointing to `std/sync/atomic/struct.AtomicPtr.html`
[01:10:12] std/sync/atomic/struct.AtomicI16.html:1: broken link fragment `#impl-From` pointing to `std/sync/atomic/struct.AtomicI16.html`
[01:10:12] std/sync/atomic/struct.AtomicI8.html:1: broken link fragment `#impl-From` pointing to `std/sync/atomic/struct.AtomicI8.html`
[01:10:12] std/sync/atomic/struct.AtomicU64.html:1: broken link fragment `#impl-From` pointing to `std/sync/atomic/struct.AtomicU64.html`
[01:10:12] std/sync/atomic/struct.AtomicU32.html:1: broken link fragment `#impl-From` pointing to `std/sync/atomic/struct.AtomicU32.html`
[01:10:12] std/sync/atomic/struct.AtomicIsize.html:1: broken link fragment `#impl-From` pointing to `std/sync/atomic/struct.AtomicIsize.html`
[01:10:12] std/sync/atomic/struct.AtomicBool.html:1: broken link fragment `#impl-From` pointing to `std/sync/atomic/struct.AtomicBool.html`
[01:10:12] std/sync/atomic/struct.AtomicUsize.html:1: broken link fragment `#impl-From` pointing to `std/sync/atomic/struct.AtomicUsize.html`
[01:10:12] std/sync/struct.RwLockReadGuard.html:24: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:12] std/sync/struct.PoisonError.html:1: broken link fragment `#impl-From` pointing to `std/sync/struct.PoisonError.html`
[01:10:12] std/sync/struct.PoisonError.html:71: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:12] std/sync/mpsc/struct.IntoIter.html:87: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:12] std/sync/mpsc/struct.SendError.html:1: broken link fragment `#impl-From` pointing to `std/sync/mpsc/struct.SendError.html`
[01:10:12] std/sync/mpsc/struct.SendError.html:30: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:12] std/sync/mpsc/enum.RecvTimeoutError.html:1: broken link fragment `#impl-From` pointing to `std/sync/mpsc/enum.RecvTimeoutError.html`
[01:10:12] std/sync/mpsc/enum.RecvTimeoutError.html:38: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:12] std/sync/mpsc/struct.RecvError.html:1: broken link fragment `#impl-From` pointing to `std/sync/mpsc/struct.RecvError.html`
[01:10:12] std/sync/mpsc/struct.RecvError.html:31: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:12] std/sync/mpsc/struct.TryIter.html:96: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:12] std/sync/mpsc/enum.TryRecvError.html:1: broken link fragment `#impl-From` pointing to `std/sync/mpsc/enum.TryRecvError.html`
[01:10:12] std/sync/mpsc/enum.TryRecvError.html:38: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:12] std/sync/mpsc/struct.Iter.html:86: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:12] std/sync/mpsc/enum.TrySendError.html:1: broken link fragment `#impl-From` pointing to `std/sync/mpsc/enum.TrySendError.html`
[01:10:12] std/sync/mpsc/enum.TrySendError.html:39: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:12] std/sync/struct.RwLockWriteGuard.html:25: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:13] std/os/windows/ffi/struct.EncodeWide.html:68: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/os/unix/net/struct.Incoming.html:89: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/fs/struct.ReadDir.html:74: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/fs/struct.File.html:1: broken link fragment `#impl-From` pointing to `std/fs/struct.File.html`
[01:10:13] std/panic/struct.AssertUnwindSafe.html:79: broken link fragment `#method.call_box` pointing to `std/boxed/trait.FnBox.html`
[01:10:13] std/panic/struct.Location.html:72: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:13] std/panic/struct.PanicInfo.html:64: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:13] std/env/struct.Args.html:79: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/env/struct.JoinPathsError.html:19: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:13] std/env/enum.VarError.html:37: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:13] std/env/struct.Vars.html:69: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/env/struct.SplitPaths.html:70: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/env/struct.VarsOs.html:69: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/env/struct.ArgsOs.html:79: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/mem/struct.PinMut.html:58: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:13] std/boxed/struct.PinBox.html:1: broken link fragment `#impl-From` pointing to `std/boxed/struct.PinBox.html`
[01:10:13] std/boxed/struct.PinBox.html:76: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:13] std/boxed/struct.Box.html:1: broken link fragment `#impl-From` pointing to `std/boxed/struct.Box.html`
[01:10:13] std/boxed/struct.Box.html:1: broken link fragment `#impl-Borrow` pointing to `std/boxed/struct.Box.html`
[01:10:13] std/boxed/struct.Box.html:1: broken link fragment `#impl-BorrowMut` pointing to `std/boxed/struct.Box.html`
[01:10:13] std/boxed/struct.Box.html:334: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/boxed/struct.Box.html:346: broken link fragment `#method.call_box` pointing to `std/boxed/trait.FnBox.html`
[01:10:13] std/boxed/struct.Box.html:351: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:13] std/collections/hash_map/struct.ValuesMut.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/hash_map/struct.IntoIter.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/hash_map/struct.IterMut.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/hash_map/struct.Drain.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/hash_map/struct.Keys.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/hash_map/struct.Iter.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/hash_map/struct.Values.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/struct.BinaryHeap.html:1: broken link fragment `#impl-From` pointing to `std/collections/struct.BinaryHeap.html`
[01:10:13] std/collections/struct.VecDeque.html:1: broken link fragment `#impl-From` pointing to `std/collections/struct.VecDeque.html`
[01:10:13] std/collections/vec_deque/struct.VecDeque.html:1: broken link fragment `#impl-From` pointing to `std/collections/vec_deque/struct.VecDeque.html`
[01:10:13] std/collections/vec_deque/struct.IntoIter.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/vec_deque/struct.IterMut.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/vec_deque/struct.Drain.html:76: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/vec_deque/struct.Iter.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/enum.CollectionAllocErr.html:1: broken link fragment `#impl-From` pointing to `std/collections/enum.CollectionAllocErr.html`
[01:10:13] std/collections/linked_list/struct.DrainFilter.html:69: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/linked_list/struct.IntoIter.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/linked_list/struct.IterMut.html:111: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/linked_list/struct.Iter.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/binary_heap/struct.BinaryHeap.html:1: broken link fragment `#impl-From` pointing to `std/collections/binary_heap/struct.BinaryHeap.html`
[01:10:13] std/collections/binary_heap/struct.IntoIter.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/binary_heap/struct.Drain.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/binary_heap/struct.Iter.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_map/struct.RangeMut.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_map/struct.ValuesMut.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_map/struct.IntoIter.html:76: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_map/struct.IterMut.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_map/struct.Range.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_map/struct.Keys.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_map/struct.Iter.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_map/struct.Values.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_set/struct.SymmetricDifference.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_set/struct.IntoIter.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_set/struct.Difference.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_set/struct.Intersection.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_set/struct.Union.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_set/struct.Range.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/btree_set/struct.Iter.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/hash_set/struct.SymmetricDifference.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/hash_set/struct.IntoIter.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/hash_set/struct.Difference.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/hash_set/struct.Intersection.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/hash_set/struct.Union.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:13] std/collections/hash_set/struct.Drain.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:14] std/collections/hash_set/struct.Iter.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:14] std/ops/struct.RangeFrom.html:151: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:14] std/ops/struct.RangeInclusive.html:211: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:14] std/ops/struct.Range.html:225: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:14] std/ascii/struct.EscapeDefault.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:14] std/path/struct.Ancestors.html:80: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:14] std/path/struct.StripPrefixError.html:29: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:14] std/path/struct.Display.html:26: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:14] std/path/struct.Path.html:1: broken link fragment `#impl-Borrow` pointing to `std/path/struct.Path.html`
[01:10:14] std/path/struct.Components.html:111: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:14] std/path/struct.PathBuf.html:1: broken link fragment `#impl-From` pointing to `std/path/struct.PathBuf.html`
[01:10:14] std/path/struct.PathBuf.html:1: broken link fragment `#impl-Borrow` pointing to `std/path/struct.PathBuf.html`
[01:10:14] std/path/struct.Iter.html:87: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:14] std/ffi/struct.OsString.html:1: broken link fragment `#impl-From` pointing to `std/ffi/struct.OsString.html`
[01:10:14] std/ffi/struct.OsString.html:1: broken link fragment `#impl-Borrow` pointing to `std/ffi/struct.OsString.html`
[01:10:14] std/ffi/struct.NulError.html:1: broken link fragment `#impl-From` pointing to `std/ffi/struct.NulError.html`
[01:10:14] std/ffi/struct.NulError.html:54: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:14] std/ffi/struct.CString.html:1: broken link fragment `#impl-From` pointing to `std/ffi/struct.CString.html`
[01:10:14] std/ffi/struct.CString.html:1: broken link fragment `#impl-Borrow` pointing to `std/ffi/struct.CString.html`
[01:10:14] std/ffi/struct.OsStr.html:1: broken link fragment `#impl-Borrow` pointing to `std/ffi/struct.OsStr.html`
[01:10:14] std/ffi/struct.IntoStringError.html:35: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:14] std/ffi/struct.CStr.html:1: broken link fragment `#impl-Borrow` pointing to `std/ffi/struct.CStr.html`
[01:10:14] std/ffi/struct.FromBytesWithNulError.html:36: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/process/struct.ExitStatus.html:63: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/process/struct.ChildStdin.html:1: broken link fragment `#impl-From` pointing to `std/process/struct.ChildStdin.html`
[01:10:15] std/process/struct.Stdio.html:1: broken link fragment `#impl-From` pointing to `std/process/struct.Stdio.html`
[01:10:15] std/process/struct.ChildStderr.html:1: broken link fragment `#impl-From` pointing to `std/process/struct.ChildStderr.html`
[01:10:15] std/process/struct.ChildStdout.html:1: broken link fragment `#impl-From` pointing to `std/process/struct.ChildStdout.html`
[01:10:15] std/task/struct.Waker.html:1: broken link fragment `#impl-From` pointing to `std/task/struct.Waker.html`
[01:10:15] std/task/struct.LocalWaker.html:1: broken link fragment `#impl-From` pointing to `std/task/struct.LocalWaker.html`
[01:10:15] std/task/enum.Poll.html:1: broken link fragment `#impl-From` pointing to `std/task/enum.Poll.html`
[01:10:15] std/rc/struct.Rc.html:1: broken link fragment `#impl-From` pointing to `std/rc/struct.Rc.html`
[01:10:15] std/rc/struct.Rc.html:1: broken link fragment `#impl-Borrow` pointing to `std/rc/struct.Rc.html`
[01:10:15] std/rc/struct.Rc.html:301: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/thread/struct.AccessError.html:16: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/option/struct.IntoIter.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/option/struct.IterMut.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/option/enum.Option.html:1: broken link fragment `#impl-From` pointing to `std/option/enum.Option.html`
[01:10:15] std/option/struct.Iter.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/vec/struct.DrainFilter.html:69: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/vec/struct.IntoIter.html:96: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/vec/struct.Drain.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/vec/struct.Vec.html:1: broken link fragment `#impl-From` pointing to `std/vec/struct.Vec.html`
[01:10:15] std/vec/struct.Vec.html:1: broken link fragment `#impl-Borrow` pointing to `std/vec/struct.Vec.html`
[01:10:15] std/vec/struct.Vec.html:1: broken link fragment `#impl-BorrowMut` pointing to `std/vec/struct.Vec.html`
[01:10:15] std/vec/struct.Splice.html:76: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/borrow/enum.Cow.html:1: broken link fragment `#impl-From` pointing to `std/borrow/enum.Cow.html`
[01:10:15] std/borrow/enum.Cow.html:1: broken link fragment `#impl-Borrow` pointing to `std/borrow/enum.Cow.html`
[01:10:15] std/str/struct.Utf8Error.html:91: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/str/struct.MatchIndices.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.EncodeUtf16.html:71: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.Lines.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.Matches.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.RSplit.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.SplitAsciiWhitespace.html:76: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.RMatchIndices.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.SplitTerminator.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.SplitN.html:69: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.SplitWhitespace.html:76: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.CharIndices.html:78: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.RSplitN.html:69: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.RMatches.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.Split.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.Chars.html:88: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.ParseBoolError.html:26: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/str/struct.Bytes.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.RSplitTerminator.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/str/struct.LinesAny.html:74: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/result/struct.IntoIter.html:78: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/result/struct.IterMut.html:74: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/result/struct.Iter.html:77: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/cell/struct.BorrowMutError.html:18: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/cell/struct.Ref.html:56: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/cell/struct.UnsafeCell.html:1: broken link fragment `#impl-From` pointing to `std/cell/struct.UnsafeCell.html`
[01:10:15] std/cell/struct.RefMut.html:59: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/cell/struct.Cell.html:1: broken link fragment `#impl-From` pointing to `std/cell/struct.Cell.html`
[01:10:15] std/cell/struct.BorrowError.html:18: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/cell/struct.RefCell.html:1: broken link fragment `#impl-From` pointing to `std/cell/struct.RefCell.html`
[01:10:15] std/time/struct.SystemTimeError.html:55: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/fmt/struct.Error.html:57: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/fmt/struct.Arguments.html:38: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/net/struct.Ipv4Addr.html:1: broken link fragment `#impl-From` pointing to `std/net/struct.Ipv4Addr.html`
[01:10:15] std/net/struct.Ipv4Addr.html:251: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/net/struct.Ipv6Addr.html:1: broken link fragment `#impl-From` pointing to `std/net/struct.Ipv6Addr.html`
[01:10:15] std/net/struct.Ipv6Addr.html:273: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/net/struct.Incoming.html:69: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:15] std/net/struct.SocketAddrV6.html:1: broken link fragment `#impl-From` pointing to `std/net/struct.SocketAddrV6.html`
[01:10:15] std/net/struct.SocketAddrV6.html:125: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/net/struct.AddrParseError.html:43: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:15] std/net/enum.IpAddr.html:1: broken link fragment `#impl-From` pointing to `std/net/enum.IpAddr.html`
[01:10:16] std/net/enum.IpAddr.html:229: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:16] std/net/enum.SocketAddr.html:1: broken link fragment `#impl-From` pointing to `std/net/enum.SocketAddr.html`
[01:10:16] std/net/enum.SocketAddr.html:116: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:16] std/net/struct.SocketAddrV4.html:1: broken link fragment `#impl-From` pointing to `std/net/struct.SocketAddrV4.html`
[01:10:16] std/net/struct.SocketAddrV4.html:83: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:16] std/alloc/struct.AllocErr.html:1: broken link fragment `#impl-From` pointing to `std/alloc/struct.AllocErr.html`
[01:10:16] std/alloc/struct.AllocErr.html:30: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:16] std/alloc/struct.CannotReallocInPlace.html:29: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:16] std/alloc/struct.LayoutErr.html:1: broken link fragment `#impl-From` pointing to `std/alloc/struct.LayoutErr.html`
[01:10:16] std/alloc/struct.LayoutErr.html:28: broken link fragment `#method.to_string` pointing to `std/string/trait.ToString.html`
[01:10:16] std/slice/struct.ChunksMut.html:76: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.Windows.html:76: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.IterMut.html:118: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.RSplitNMut.html:70: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.RSplit.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.SplitNMut.html:69: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.Chunks.html:79: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.SplitN.html:69: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.RSplitN.html:70: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.RSplitMut.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.Split.html:75: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.Iter.html:108: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.ExactChunks.html:83: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.SplitMut.html:73: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] std/slice/struct.ExactChunksMut.html:81: broken link fragment `#method.into_iter` pointing to `std/iter/trait.IntoIterator.html`
[01:10:16] test/enum.OutputFormat.html:17: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/enum.OutputFormat.html:18: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/enum.OutputFormat.html:21: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/enum.OutputFormat.html:22: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/enum.OutputFormat.html:23: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/enum.OutputFormat.html:26: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/enum.OutputFormat.html:27: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/enum.TestResult.html:18: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/enum.TestResult.html:19: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/enum.TestResult.html:22: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/enum.TestResult.html:23: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/enum.TestResult.html:24: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/enum.TestResult.html:27: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/enum.TestResult.html:28: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/enum.BenchMode.html:15: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/enum.BenchMode.html:16: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/enum.BenchMode.html:19: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/enum.BenchMode.html:20: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/enum.BenchMode.html:21: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/enum.BenchMode.html:24: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/enum.BenchMode.html:25: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/struct.Metric.html:10: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/struct.Metric.html:11: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/struct.Metric.html:14: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/struct.Metric.html:15: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/struct.Metric.html:16: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/struct.Metric.html:19: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/struct.Metric.html:20: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/enum.NamePadding.html:18: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/enum.NamePadding.html:19: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/enum.NamePadding.html:22: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/enum.NamePadding.html:23: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/enum.NamePadding.html:24: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/enum.NamePadding.html:27: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/enum.NamePadding.html:28: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/stats/struct.Summary.html:73: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/stats/struct.Summary.html:74: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/stats/struct.Summary.html:77: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/stats/struct.Summary.html:78: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/stats/struct.Summary.html:79: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/stats/struct.Summary.html:82: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/stats/struct.Summary.html:83: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/enum.TestEvent.html:15: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/enum.TestEvent.html:16: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/enum.TestEvent.html:19: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/enum.TestEvent.html:20: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/enum.TestEvent.html:21: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/enum.TestEvent.html:24: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/enum.TestEvent.html:25: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/struct.Options.html:9: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/struct.Options.html:10: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/struct.Options.html:13: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/struct.Options.html:14: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/struct.Options.html:15: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/struct.Options.html:18: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/struct.Options.html:19: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/struct.TestDescAndFn.html:14: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/struct.TestDescAndFn.html:15: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/struct.TestDescAndFn.html:18: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/struct.TestDescAndFn.html:19: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/struct.TestDescAndFn.html:20: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/struct.TestDescAndFn.html:23: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/struct.TestDescAndFn.html:24: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/enum.TestName.html:19: broken link fragment `#method.to_string` pointing to `alloc/string/trait.ToString.html`
[01:10:16] test/enum.TestName.html:20: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/enum.TestName.html:21: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/enum.TestName.html:24: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/enum.TestName.html:25: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/enum.TestName.html:26: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/enum.TestName.html:29: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/enum.TestName.html:30: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/struct.BenchSamples.html:9: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/struct.BenchSamples.html:10: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/struct.BenchSamples.html:13: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/struct.BenchSamples.html:14: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/struct.BenchSamples.html:15: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/struct.BenchSamples.html:18: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/struct.BenchSamples.html:19: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/struct.TestOpts.html:69: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/struct.TestOpts.html:70: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/struct.TestOpts.html:73: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/struct.TestOpts.html:74: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/struct.TestOpts.html:75: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/struct.TestOpts.html:78: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/struct.TestOpts.html:79: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/struct.Bencher.html:20: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/struct.Bencher.html:21: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/struct.Bencher.html:24: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/struct.Bencher.html:25: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/struct.Bencher.html:26: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/struct.Bencher.html:29: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/struct.Bencher.html:30: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/struct.TestDesc.html:34: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/struct.TestDesc.html:35: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/struct.TestDesc.html:38: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/struct.TestDesc.html:39: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/struct.TestDesc.html:40: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/struct.TestDesc.html:43: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/struct.TestDesc.html:44: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/struct.MetricMap.html:20: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/struct.MetricMap.html:21: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/struct.MetricMap.html:24: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/struct.MetricMap.html:25: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/struct.MetricMap.html:26: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/struct.MetricMap.html:29: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/struct.MetricMap.html:30: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/enum.ColorConfig.html:14: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/enum.ColorConfig.html:15: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/enum.ColorConfig.html:18: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/enum.ColorConfig.html:19: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/enum.ColorConfig.html:20: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/enum.ColorConfig.html:23: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/enum.ColorConfig.html:24: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/enum.ShouldPanic.html:18: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/enum.ShouldPanic.html:19: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/enum.ShouldPanic.html:22: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/enum.ShouldPanic.html:23: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/enum.ShouldPanic.html:24: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/enum.ShouldPanic.html:27: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/enum.ShouldPanic.html:28: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] test/enum.TestFn.html:9: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] test/enum.TestFn.html:10: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] test/enum.TestFn.html:13: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] test/enum.TestFn.html:14: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] test/enum.TestFn.html:15: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] test/enum.TestFn.html:18: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] test/enum.TestFn.html:19: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] proc_macro/struct.Punct.html:1: broken link fragment `#impl-From` pointing to `proc_macro/struct.Punct.html`
[01:10:16] proc_macro/struct.Punct.html:27: broken link fragment `#method.to_string` pointing to `alloc/string/trait.ToString.html`
[01:10:16] proc_macro/struct.Punct.html:28: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] proc_macro/struct.Punct.html:31: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] proc_macro/struct.Punct.html:32: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] proc_macro/struct.Punct.html:33: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] proc_macro/struct.Punct.html:36: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] proc_macro/struct.Punct.html:37: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] proc_macro/struct.TokenStream.html:1: broken link fragment `#impl-From` pointing to `proc_macro/struct.TokenStream.html`
[01:10:16] proc_macro/struct.TokenStream.html:44: broken link fragment `#method.to_string` pointing to `alloc/string/trait.ToString.html`
[01:10:16] proc_macro/struct.TokenStream.html:45: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] proc_macro/struct.TokenStream.html:48: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] proc_macro/struct.TokenStream.html:49: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] proc_macro/struct.TokenStream.html:50: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] proc_macro/struct.TokenStream.html:53: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] proc_macro/struct.TokenStream.html:54: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] proc_macro/token_stream/struct.IntoIter.html:69: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] proc_macro/token_stream/struct.IntoIter.html:74: broken link fragment `#method.into_iter` pointing to `core/iter/traits/../../../core/iter/trait.IntoIterator.html`
[01:10:16] proc_macro/token_stream/struct.IntoIter.html:75: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] proc_macro/token_stream/struct.IntoIter.html:78: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] proc_macro/token_stream/struct.IntoIter.html:79: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] proc_macro/token_stream/struct.IntoIter.html:80: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] proc_macro/token_stream/struct.IntoIter.html:83: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] proc_macro/token_stream/struct.IntoIter.html:84: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] proc_macro/enum.TokenTree.html:1: broken link fragment `#impl-From` pointing to `proc_macro/enum.TokenTree.html`
[01:10:16] proc_macro/enum.TokenTree.html:39: broken link fragment `#method.to_string` pointing to `alloc/string/trait.ToString.html`
[01:10:16] proc_macro/enum.TokenTree.html:40: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] proc_macro/enum.TokenTree.html:43: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] proc_macro/enum.TokenTree.html:44: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] proc_macro/enum.TokenTree.html:45: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] proc_macro/enum.TokenTree.html:48: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] proc_macro/enum.TokenTree.html:49: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] proc_macro/enum.Delimiter.html:27: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] proc_macro/enum.Delimiter.html:28: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] proc_macro/enum.Delimiter.html:31: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] proc_macro/enum.Delimiter.html:32: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] proc_macro/enum.Delimiter.html:33: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] proc_macro/enum.Delimiter.html:36: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] proc_macro/enum.Delimiter.html:37: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] proc_macro/struct.LineColumn.html:26: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] proc_macro/struct.LineColumn.html:27: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] proc_macro/struct.LineColumn.html:30: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] proc_macro/struct.LineColumn.html:31: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] proc_macro/struct.LineColumn.html:32: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] proc_macro/struct.LineColumn.html:35: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] proc_macro/struct.LineColumn.html:36: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] proc_macro/struct.Ident.html:1: broken link fragment `#impl-From` pointing to `proc_macro/struct.Ident.html`
[01:10:16] proc_macro/struct.Ident.html:32: broken link fragment `#method.to_string` pointing to `alloc/string/trait.ToString.html`
[01:10:16] proc_macro/struct.Ident.html:33: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] proc_macro/struct.Ident.html:36: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] proc_macro/struct.Ident.html:37: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] proc_macro/struct.Ident.html:38: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] proc_macro/struct.Ident.html:41: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] proc_macro/struct.Ident.html:42: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] proc_macro/struct.SourceFile.html:20: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] proc_macro/struct.SourceFile.html:21: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] proc_macro/struct.SourceFile.html:24: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] proc_macro/struct.SourceFile.html:25: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] proc_macro/struct.SourceFile.html:26: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] proc_macro/struct.SourceFile.html:29: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] proc_macro/struct.SourceFile.html:30: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] proc_macro/struct.Diagnostic.html:31: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] proc_macro/struct.Diagnostic.html:32: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] proc_macro/struct.Diagnostic.html:35: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] proc_macro/struct.Diagnostic.html:36: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] proc_macro/struct.Diagnostic.html:37: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] proc_macro/struct.Diagnostic.html:40: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] proc_macro/struct.Diagnostic.html:41: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] proc_macro/struct.Span.html:38: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] proc_macro/struct.Span.html:39: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] proc_macro/struct.Span.html:42: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] proc_macro/struct.Span.html:43: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] proc_macro/struct.Span.html:44: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] proc_macro/struct.Span.html:47: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] proc_macro/struct.Span.html:48: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] proc_macro/struct.LexError.html:3: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] proc_macro/struct.LexError.html:4: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
[01:10:16] proc_macro/struct.LexError.html:7: broken link fragment `#method.try_from` pointing to `core/convert/trait.TryFrom.html`
[01:10:16] proc_macro/struct.LexError.html:8: broken link fragment `#method.borrow` pointing to `core/borrow/trait.Borrow.html`
[01:10:16] proc_macro/struct.LexError.html:9: broken link fragment `#method.borrow_mut` pointing to `core/borrow/trait.BorrowMut.html`
[01:10:16] proc_macro/struct.LexError.html:12: broken link fragment `#method.try_into` pointing to `core/convert/trait.TryInto.html`
[01:10:16] proc_macro/struct.LexError.html:13: broken link fragment `#method.get_type_id` pointing to `core/any/trait.Any.html`
[01:10:16] proc_macro/enum.Level.html:21: broken link fragment `#method.from` pointing to `core/convert/trait.From.html`
[01:10:16] proc_macro/enum.Level.html:22: broken link fragment `#method.into` pointing to `core/convert/trait.Into.html`
