plain
[00:44:27] ....................................................................................................
[00:44:30] ....................................................................................................
[00:44:33] ....................................................................................................
[00:44:36] ........i...........................................................................................
[00:44:40] ............................................................................F.......................
[00:44:47] ...........................ii.iii...................................................................
[00:44:49] ....................................................................................................
[00:44:51] ....................................................................................................
[00:44:54] ....................................................................................................
---
[00:46:21] 
[00:46:21] 29 error[E0080]: could not evaluate constant expression
[00:46:21] 30   --> $DIR/const-fn-error.rs:29:13
[00:46:21] 31    |
[00:46:21] - LL |       for i in 0..x {
[00:46:21] -    |                ---- inside call to `std::iter::range::<impl std::iter::Iterator for std::ops::Range<A>><usize>::next`
[00:46:21] + LL |     for i in 0..x {
[00:46:21] +    |  :21] error: 1 errors occurred comparing output.
[00:46:21] status: exit code: 1
[00:46:21] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/consts/const-fn-error.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const-fn-error/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const-fn-error/auxiliary" "-A" "unused"
[00:46:21] ------------------------------------------
[00:46:21] 
[00:46:21] ------------------------------------------
[00:46:21] stderr:
[00:46:21] stderr:
[00:46:21] ------------------------------------------
[00:46:21] {"message":"let bindings in constant functions are unstable (see issue #48821)","code":{"code":"E0658","explanation":"\nAn unstable feature was used.\n\nErroneous code example:\n\n