plain
[01:28:58] ....................................................................................................
[01:29:01] .....................................................i..............................................
[01:29:04] ....................................................................................................
[01:29:07] ....................................................................................................
[01:29:09] ..iiiiiiiii.........................................................................................
[01:29:16] ....................................................................................................
[01:29:19] ...................................................................................i................
[01:29:21] ....................................................................................................
[01:29:24] ......................................i.i..ii.......................................................
---
travis_time:start:test_run-pass
Check compiletest suite=run-pass mode=run-pass (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:34:23] 
[01:34:23] running 549 tests
[01:34:36] ...................................F....i...........................................................
[01:35:00] ....................................................................................................
[01:35:10] ....................................................................................................
[01:35:24] ................i...................................................................................
[01:35:30] .................................................
---
[01:35:30] test result: FAILED. 546 passed; 1 failed; 2 ignored; 0 measured; 0 filtered out
[01:35:30] 
[01:35:30] 
[01:35:30] 
[01:35:30] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/run-pass" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "run-pass" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-5.0/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "5.0.0\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[01:35:30] 
[01:35:30] 
[01:35:30] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:35:30] Build completed unsuccessfully in 0:14:54
[01:35:30] Build completed unsuccessfully in 0:14:54
[01:35:30] Makefile:58: recipe for target 'check' failed
[01:35:30] make: *** [check] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:043ba108
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
