plain
Check compiletest suite=ui mode=ui (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:49:02] 
[00:49:02] running 6790 tests
[00:49:05] ....................................................................................................
[00:49:08] ....................................................................F...............................
[00:49:14] ....................................................................................................
[00:49:17] ....................................................................................................
[00:49:20] .................i..................................................................................
[00:49:25] ....................................................................................................
---
[00:50:37] ...............................................i....................................................
[00:50:40] ....................................................................................................
[00:50:43] ....................................................................................................
[00:50:46] ....................................................................................................
[00:50:49] .............................................................F.FFFFFF..................i............
[00:51:04] ....................................................................................................
[00:51:11] ....................................................................................................
[00:51:19] ....................................................................................................
[00:51:28] ....................................................................................................
---
[00:55:50] 
[00:55:50] ---- [ui] ui/bind-by-move/bind-by-move-no-guards.rs stdout ----
[00:55:50] diff of stderr:
[00:55:50] 
[00:55:50] 1 error[E0008]: cannot bind by-move into a pattern guard
[00:55:50] +   --> $DIR/bind-by-move-no-guards.rs:8:14
[00:55:50] 3    |
[00:55:50] 3    |
[00:55:50] 4 LL |         Some(z) if z.recv().unwrap() => { panic!() },
[00:55:50] 5    |              ^ moves value into pattern guard
[00:55:50] 
[00:55:50] The actual stderr differed from the expected stderr.
[00:55:50] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/bind-by-move/bind-by-move-no-guards/bind-by-move-no-guards.stderr
[00:55:50] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/bind-by-move/bind-by-move-no-guards/bind-by-move-no-guards.stderr
[00:55:50] To update references, rerun the tests and pass the `--bless` flag
[00:55:50] To only update this specific test, also pass `--test-args bind-by-move/bind-by-move-no-guards.rs`
[00:55:50] error: 1 errors occurred comparing output.
[00:55:50] status: exit code: 1
[00:55:50] status: exit code: 1
[00:55:50] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/bind-by-move/bind-by-move-no-guards.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/bind-by-move/bind-by-move-no-guards/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/bind-by-move/bind-by-move-no-guards/auxiliary" "-A" "unused"
[00:55:50] ------------------------------------------
[00:55:50] 
[00:55:50] ------------------------------------------
[00:55:50] stderr:
[00:55:50] stderr:
[00:55:50] ------------------------------------------
[00:55:50] {"message":"cannot bind by-move into a pattern guard","code":{"code":"E0008","explanation":"\nNames bound in match arms retain their type in pattern guards. As such, if a\nname is bound by move in a pattern, it should also be moved to wherever it is\nreferenced in the pattern guard code. Doing so however would prevent the name\nfrom being available in the body of the match arm"cannot bind by-move into a pattern guard","code":{"code":"E0008","explanation":"\nNames bound in match arms retain their type in pattern guards. As such, if a\nname is bound by move in a pattern, it should also be moved to wherever it is\nreferenced in the pattern guard code. Doing so however would prevent the name\nfrom being available in the body of the match arm. Consider the following:\n\n