 rust
enum Dir { North, East, South, West }

/* everything below this would be generated by `#[deriving(Enumerable)]` on the enum */

impl Enumerable<DirEnumerator> for Dir {
    fn enumerator() -> DirEnumerator { DirEnumerator }
}

struct DirEnumerator;

impl BaseIter<Dir> for DirEnumerator {
    fn each(&self, blk: &fn(&Dir) -> bool) {
        [North, East, South, West].each(blk);
    }

    fn size_hint(&self) -> Option<uint> { Some(4) }
 }
