plain
[00:48:04] ....................................................................................................
[00:48:07] ....................................................................................................
[00:48:09] ....................................................................................................
[00:48:12] ...................................i................................................................
[00:48:15] ..i...............F.................................................................................
[00:48:21] .........................................................................................i..........
[00:48:24] ....................................................................................................
[00:48:27] ....................................................................................................
[00:48:30] ....................................................................................................
[00:48:30] ....................................................................................................
[00:48:33] ....................................................................................................
[00:48:36] ....................................................................................................
[00:48:39] ....................................................................................................
[00:48:42] ....................................................................................................
[00:48:46] ....................................................................................................
[00:48:49] ...................................................................................i................
[00:48:52] ......F.............................................................................................
[00:48:59] ....................................................................................................
[00:49:02] .....................................................i..............................................
[00:49:05] ....................................................................................................
[00:49:08] ....................................................................................................
[00:49:08] ....................................................................................................
[00:49:11] ....................................................................................................
[00:49:14] .............................................................................................i......
[00:49:20] ....................................................................................................
[00:49:28] ....................................................................................................
[00:49:35] ....................................................................................................
[00:49:43] ....................................................................................................
[00:49:52] ....................................................................................................
[00:50:05] .............................................................................F.F....................
[00:50:24] ....................................................................................................
[00:50:35] ....................................................................................................
[00:50:44] ....................................................................................................
[00:50:51] ....................................................................................................
---
[00:51:51] ....................................................................................................
[00:52:02] ....................................................................................................
[00:52:12] ....................................................................i........................i......
[00:52:33] ....................................................................................................
[00:52:40] .....................................................................................ii..F.F........
[00:53:01] ....................................................................................................
[00:53:28] ....................................................................................................
[00:53:36] ....................................................................................................
[00:53:46] ....................................................................................................
---
[00:54:04] ....................................................................................................
[00:54:07] ....................................................................................................
00:54:09] The actual stderr differed from the expected stderr.
[00:54:09] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/macro-path-prelude-pass/macro-path-prelude-pass.stderr
[00:54:09] To update references, rerun the tests and pass the `--bless` flag
[00:54:09] To only update this specific test, also pass `--test-args macros/macro-path-prelude-pass.rs`
[00:54:09] error: 1 errors occurred comparing output.
[00:54:09] status: exit code: 0
[00:54:09] status: exit code: 0
[00:54:09] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/macros/macro-path-prelude-pass.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/macro-path-prelude-pass/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/macro-path-prelude-pass/auxiliary" "-A" "unused"
[00:54:09] ------------------------------------------
[00:54:09] 
[00:54:09] ------------------------------------------
[00:54:09] stderr:
[00:54:09] stderr:
[00:54:09] ------------------------------------------
[00:54:09] {"message":"the feature `extern_prelude` has been stable since 1.30.0 and no longer requires an attribute to enable","code":{"code":"stable_features","explanation":null},"level":"warning","spans":[{"file_name":"/checkout/src/test/ui/macros/macro-path-prelude-pass.rs","byte_start":495,"byte_end":509,"line_start":13,"line_end":13,"column_start":12,"column_end":
[00:54:09] To update references, rerun the tests and pass the `--bless` flag
[00:54:09] To only update this specific test, also pass `--test-args run-pass/extern/extern-prelude-core.rs`
[00:54:09] error: 1 errors occurred comparing output.
[00:54:09] status: exit code: 0
[00:54:09] status: exit code: 0
[00:54:09] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/run-pass/extern/extern-prelude-core.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/run-pass/extern/extern-prelude-core/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/run-pass/extern/extern-prelude-core/auxiliary" "-A" "unused"
[00:54:09] ------------------------------------------
[00:54:09] 
[00:54:09] ------------------------------------------
[00:54:09] stderr:
[00:54:09] stderr:
[00:54:09] ------------------------------------------
[00:54:09] {"message":"the feature `extern_prelude` has been stable since 1.30.0 and no longer requires an attribute to enable","code":{"code":"stable_features","explanation":null},"level":"warning","spans":[{"file_name":"/checkout/src/test/ui/run-pass/extern/extern-prelude-core.rs","byte_start":490,"byte_end":504,"line_start":12,"line_end":12,"column_start":12,"column_end":26,"is_primary":true,"text":[{"text":"#![feature(extern_prelude, lang_items, start, alloc)]","highlight_start":12,"highlight_end":26}],"label":null,"suggested_replacement":null,"suggestioss/extern/extern-prelude-std.rs`
[00:54:09] error: 1 errors occurred comparing output.
[00:54:09] status: exit code: 0
[00:54:09] status: exit code: 0
[00:54:09] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/run-pass/extern/extern-prelude-std.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/run-pass/extern/extern-prelude-std/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/run-pass/extern/extern-prelude-std/auxiliary" "-A" "unused"
[00:54:09] ------------------------------------------
[00:54:09] 
[00:54:09] ------------------------------------------
[00:54:09] stderr:
[00:54:09] stderr:
[00:54:09] ------------------------------------------
[00:54:09] {"message":"the feature `extern_prelude` has been stable since 1.30.0 and no longer requires an attribute to enable","code":{"code":"stable_features","explanation":null},"level":"warning","spans":[{"file_name":"/checkout/src/test/ui/run-pass/extern/extern-prelude-std.rs","byte_start":490,"byte_end":504,"line_start":12,"line_end":12,"column_start":12,"column_end":26,"is_primary":true,"text":[{"text":"#![feature(extern_prelude)]","highlight_start":12,"highlight_end":26}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"#[warn(stable_features)] on by default","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"warning: the feature `extern_prelude` has been stable since 1.30.0 and no longer requires an attribute to enable\n  --> /checkout/src/test/ui/run-pass/extern/extern-prelude-std.rs:12:12\n   |\nLL | #![feature(extern_prelude)]\n   |            ^^^^^^^^^^^^^^\n   |\n   = note: #[warn(stable_features)] on by default\n\n"}
[00:54:09] ------------------------------------------
[00:54:09] 
[00:54:09] thread '[ui] ui/run-pass/extern/extern-prelude-std.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3205:9
[00:54:09] 
[00:54:09] 
[00:54:09] ---- [ui] ui/run-pass/rfcs/rfc-2126-crate-paths/crate-path-visibility-ambiguity.rs stdout ----
[00:54:09] normalized stderr:
[00:54:09] warning: the feature `crate_in_paths` has been stable since 1.30.0 and no longer requires an attribute to enable
[00:54:09]   --> $DIR/crate-path-visibility-ambiguity.rs:12:12
[00:54:09]    |
[00:54:09] LL | #![feature(crate_in_paths)]
[00:54:09]    |
[00:54:09]    = note: #[warn(stable_features)] on by default
[00:54:09] 
[00:54:09] 
[00:54:09] 
[00:54:09] 
[00:54:09] 
[00:54:09] The actual stderr differed from the expected stderr.
[00:54:09] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/run-pass/rfcs/rfc-2126-crate-paths/crate-path-visibility-ambiguity/crate-path-visibility-ambiguity.stderr
[00:54:09] To update references, rerun the tests and pass the `--bless` flag
[00:54:09] To only update this specific test, also pass `--test-args run-pass/rfcs/rfc-2126-crate-paths/crate-path-visibility-ambiguity.rs`
[00:54:09] error: 1 errors occurred comparing output.
[00:54:09] status: exit code: 0
[00:54:09] status: exit code: 0
[00:54:09] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/run-pass/rfcs/rfc-2126-crate-paths/crate-path-visibility-ambiguity.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/run-pass/rfcs/rfc-2126-crate-paths/crate-path-visibility-ambiguity/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/run-pass/rfcs/rfc-2126-crate-paths/crate-path-visibility-ambiguity/auxiliary" "-A" "unused"
[00:54:09] ------------------------------------------
[00:54:09] 
[00:54:09] ------------------------------------------
[00:54:09] stderr:
[00:54:09] stderr:
[00:54:09] ------------------------------------------
[00:54:09] {"message":"the feature `crate_in_paths` has been stable since 1.30.0 and no longer requires an attribute to enable","code":{"code":"stable_features","explanation":null},"level":"warning","spans":[{"file_name":"/checkout/src/test/ui/run-pass/rfcs/rfc-2126-crate-paths/crate-path-visibility-ambiguity.rs","byte_start":490,"byte_end":504,"line_start":12,"line_end":12,"column_start":12,"column_end":26,"is_primary":true,"text":[{"text":"#![feature(crate_in_paths)]","highlight_start":12,"highlight_end":26}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"#[warn(stable_features)] on by default","code":null,"level":"note","spans":[],"childr4:09] error: 1 errors occurred comparing output.
[00:54:09] status: exit code: 0
[00:54:09] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/run-pass/rfcs/rfc-2126-crate-paths/crate-path-absolute.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/run-pass/rfcs/rfc-2126-crate-paths/crate-path-absolute/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/run-pass/rfcs/rfc-2126-crate-paths/crate-path-absolute/auxiliary" "-A" "unused"
[00:54:09] ------------------------------------------
[00:54:09] 
[00:54:09] ------------------------------------------
[00:54:09] stderr:
[00:54:09] stderr:
[00:54:09] ------------------------------------------
[00:54:09] {"message":"the feature `crate_in_paths` has been stable since 1.30.0 and no longer requires an attribute to enable","code":{"code":"stable_features","explanation":null},"level":"warning","spans":[{"file_name":"/checkout/src/test/ui/run-pass/rfcs/rfc-2126-crate-paths/crate-path-absolute.rs","byte_start":490,"byte_end":504,"line_start":12,"line_end":12,"column_start":12,"column_end":26,"is_primary":true,"text":[{"text":"#![feature(crate_in_paths)]","highlight_start":12,"highlight_end":26}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"#[warn(stable_features)] on by default","code":null,"level":"note","spans":[],"children":[],"/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release
129772 ./obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release
128436 ./obj/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps
122628 ./obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps
113596 ./obj/build/x86_64-unknown-linux-gnu/stage1-std
