
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:480
   5: std::panicking::begin_panic
             at /home/oliver/Projects/rust/rust4/src/libstd/panicking.rs:410
   6: rustc_errors::Handler::emit_db
             at librustc_errors/lib.rs:500
             at librustc_errors/lib.rs:607
             at librustc_errors/lib.rs:724
   7: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
             at librustc_errors/diagnostic_builder.rs:98
   8: rustc::traits::error_reporting::<impl rustc::infer::InferCtxt<'a, 'gcx, 'tcx>>::report_overflow_error
             at librustc/traits/error_reporting.rs:550
   9: rustc::traits::project::opt_normalize_projection_type
             at librustc/traits/project.rs:888
             at librustc/traits/project.rs:642
  10: rustc::traits::project::project_and_unify_type
             at librustc/traits/project.rs:246
  11: rustc::infer::InferCtxt::commit_if_ok
             at librustc/traits/project.rs:210
             at librustc/infer/mod.rs:822
  12: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
             at librustc/traits/project.rs:205
             at librustc/traits/select.rs:825
  13: rustc::infer::InferCtxt::probe
             at librustc/traits/select.rs:671
             at librustc/traits/select.rs:1091
             at librustc/traits/select.rs:559
             at librustc/infer/mod.rs:854
  14: rustc::traits::select::SelectionContext::evaluate_candidate
             at librustc/traits/select.rs:559
             at librustc/traits/select.rs:1088
  15: rustc::traits::select::SelectionContext::evaluate_stack
             at librustc/traits/select.rs:1044
  16: rustc::dep_graph::graph::DepGraph::with_anon_task
             at librustc/traits/select.rs:915
             at librustc/traits/select.rs:1237
             at librustc/dep_graph/graph.rs:378
  17: rustc::traits::select::SelectionContext::in_task
             at librustc/traits/select.rs:1235
  18: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
             at librustc/traits/select.rs:915
             at librustc/traits/select.rs:698
  19: rustc::infer::InferCtxt::probe
             at librustc/traits/select.rs:671
             at librustc/traits/select.rs:1091
             at librustc/traits/select.rs:559
             at librustc/infer/mod.rs:854
  20: rustc::traits::select::SelectionContext::evaluate_candidate
             at librustc/traits/select.rs:559
             at librustc/traits/select.rs:1088
  21: <&mut I as core::iter::iterator::Iterator>::next
             at librustc/traits/select.rs:1376
             at /home/oliver/Projects/rust/rust4/src/libcore/ops/function.rs:286
             at /home/oliver/Projects/rust/rust4/src/libcore/option.rs:424
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:1394
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:1394
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:2686
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:2523
             at /home/oliver/Projects/rust/rust4/src/libcore/result.rs:1232
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/iterator.rs:2623
  22: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /home/oliver/Projects/rust/rust4/src/liballoc/vec.rs:1788
  23: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
             at /home/oliver/Projects/rust/rust4/src/liballoc/vec.rs:1700
             at /home/oliver/Projects/rust/rust4/src/libcore/result.rs:1249
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/iterator.rs:1476
             at librustc/traits/select.rs:1374
  24: rustc::dep_graph::graph::DepGraph::with_anon_task
             at librustc/traits/select.rs:1216
             at librustc/traits/select.rs:1237
             at librustc/dep_graph/graph.rs:378
  25: rustc::traits::select::SelectionContext::in_task
             at librustc/traits/select.rs:1235
  26: rustc::traits::select::SelectionContext::candidate_from_obligation
             at librustc/traits/select.rs:1216
  27: rustc::traits::select::SelectionContext::select
             at librustc/traits/select.rs:597
  28: rustc::infer::InferCtxt::commit_if_ok
             at librustc/traits/project.rs:1056
             at librustc/infer/mod.rs:822
  29: rustc::traits::project::opt_normalize_projection_type
             at librustc/traits/project.rs:1055
             at librustc/traits/project.rs:914
             at librustc/traits/project.rs:642
  30: rustc::traits::project::project_and_unify_type
             at librustc/traits/project.rs:246
  31: rustc::infer::InferCtxt::commit_if_ok
             at librustc/traits/project.rs:210
             at librustc/infer/mod.rs:822
  32: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
             at librustc/traits/project.rs:205
             at librustc/traits/select.rs:825
  33: rustc::infer::InferCtxt::probe
             at librustc/traits/select.rs:671
             at librustc/traits/select.rs:1091
             at librustc/traits/select.rs:559
             at librustc/infer/mod.rs:854
  34: rustc::traits::select::SelectionContext::evaluate_candidate
             at librustc/traits/select.rs:559
             at librustc/traits/select.rs:1088
  35: rustc::traits::select::SelectionContext::evaluate_stack
             at librustc/traits/select.rs:1044
  36: rustc::dep_graph::graph::DepGraph::with_anon_task
             at librustc/traits/select.rs:915
             at librustc/traits/select.rs:1237
             at librustc/dep_graph/graph.rs:378
  37: rustc::traits::select::SelectionContext::in_task
             at librustc/traits/select.rs:1235
  38: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
             at librustc/traits/select.rs:915
             at librustc/traits/select.rs:698
  39: rustc::infer::InferCtxt::probe
             at librustc/traits/select.rs:671
             at librustc/traits/select.rs:1091
             at librustc/traits/select.rs:559
             at librustc/infer/mod.rs:854
  40: rustc::traits::select::SelectionContext::evaluate_candidate
             at librustc/traits/select.rs:559
             at librustc/traits/select.rs:1088
  41: <&mut I as core::iter::iterator::Iterator>::next
             at librustc/traits/select.rs:1376
             at /home/oliver/Projects/rust/rust4/src/libcore/ops/function.rs:286
             at /home/oliver/Projects/rust/rust4/src/libcore/option.rs:424
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:1394
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:1394
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:2686
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:2523
             at /home/oliver/Projects/rust/rust4/src/libcore/result.rs:1232
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/iterator.rs:2623
  42: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /home/oliver/Projects/rust/rust4/src/liballoc/vec.rs:1788
  43: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
             at /home/oliver/Projects/rust/rust4/src/liballoc/vec.rs:1700
             at /home/oliver/Projects/rust/rust4/src/libcore/result.rs:1249
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/iterator.rs:1476
             at librustc/traits/select.rs:1374
  44: rustc::dep_graph::graph::DepGraph::with_anon_task
             at librustc/traits/select.rs:1216
             at librustc/traits/select.rs:1237
             at librustc/dep_graph/graph.rs:378
  45: rustc::traits::select::SelectionContext::in_task
             at librustc/traits/select.rs:1235
  46: rustc::traits::select::SelectionContext::candidate_from_obligation
             at librustc/traits/select.rs:1216
  47: rustc::traits::select::SelectionContext::select
             at librustc/traits/select.rs:597
  48: rustc::infer::InferCtxt::commit_if_ok
             at librustc/traits/project.rs:1056
             at librustc/infer/mod.rs:822
  49: rustc::traits::project::opt_normalize_projection_type
             at librustc/traits/project.rs:1055
             at librustc/traits/project.rs:914
             at librustc/traits/project.rs:642
  50: rustc::traits::project::project_and_unify_type
             at librustc/traits/project.rs:246
  51: rustc::infer::InferCtxt::commit_if_ok
             at librustc/traits/project.rs:210
             at librustc/infer/mod.rs:822
  52: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
             at librustc/traits/project.rs:205
             at librustc/traits/select.rs:825
  53: rustc::infer::InferCtxt::probe
             at librustc/traits/select.rs:671
             at librustc/traits/select.rs:1091
             at librustc/traits/select.rs:559
             at librustc/infer/mod.rs:854
  54: rustc::traits::select::SelectionContext::evaluate_candidate
             at librustc/traits/select.rs:559
             at librustc/traits/select.rs:1088
  55: rustc::traits::select::SelectionContext::evaluate_stack
             at librustc/traits/select.rs:1044
  56: rustc::dep_graph::graph::DepGraph::with_anon_task
             at librustc/traits/select.rs:915
             at librustc/traits/select.rs:1237
             at librustc/dep_graph/graph.rs:378
  57: rustc::traits::select::SelectionContext::in_task
             at librustc/traits/select.rs:1235
  58: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
             at librustc/traits/select.rs:915
             at librustc/traits/select.rs:698
  59: rustc::infer::InferCtxt::probe
             at librustc/traits/select.rs:671
             at librustc/traits/select.rs:1091
             at librustc/traits/select.rs:559
             at librustc/infer/mod.rs:854
  60: rustc::traits::select::SelectionContext::evaluate_candidate
             at librustc/traits/select.rs:559
             at librustc/traits/select.rs:1088
  61: <&mut I as core::iter::iterator::Iterator>::next
             at librustc/traits/select.rs:1376
             at /home/oliver/Projects/rust/rust4/src/libcore/ops/function.rs:286
             at /home/oliver/Projects/rust/rust4/src/libcore/option.rs:424
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:1394
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:1394
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:2686
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:2523
             at /home/oliver/Projects/rust/rust4/src/libcore/result.rs:1232
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/iterator.rs:2623
  62: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /home/oliver/Projects/rust/rust4/src/liballoc/vec.rs:1788
  63: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
             at /home/oliver/Projects/rust/rust4/src/liballoc/vec.rs:1700
             at /home/oliver/Projects/rust/rust4/src/libcore/result.rs:1249
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/iterator.rs:1476
             at librustc/traits/select.rs:1374
  64: rustc::dep_graph::graph::DepGraph::with_anon_task
             at librustc/traits/select.rs:1216
             at librustc/traits/select.rs:1237
             at librustc/dep_graph/graph.rs:378
  65: rustc::traits::select::SelectionContext::in_task
             at librustc/traits/select.rs:1235
  66: rustc::traits::select::SelectionContext::candidate_from_obligation
             at librustc/traits/select.rs:1216
  67: rustc::traits::select::SelectionContext::select
             at librustc/traits/select.rs:597
  68: rustc::infer::InferCtxt::commit_if_ok
             at librustc/traits/project.rs:1056
             at librustc/infer/mod.rs:822
  69: rustc::traits::project::opt_normalize_projection_type
             at librustc/traits/project.rs:1055
             at librustc/traits/project.rs:914
             at librustc/traits/project.rs:642
  70: rustc::traits::project::project_and_unify_type
             at librustc/traits/project.rs:246
  71: rustc::infer::InferCtxt::commit_if_ok
             at librustc/traits/project.rs:210
             at librustc/infer/mod.rs:822
  72: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
             at librustc/traits/project.rs:205
             at librustc/traits/select.rs:825
  73: rustc::infer::InferCtxt::probe
             at librustc/traits/select.rs:671
             at librustc/traits/select.rs:1091
             at librustc/traits/select.rs:559
             at librustc/infer/mod.rs:854
  74: rustc::traits::select::SelectionContext::evaluate_candidate
             at librustc/traits/select.rs:559
             at librustc/traits/select.rs:1088
  75: rustc::traits::select::SelectionContext::evaluate_stack
             at librustc/traits/select.rs:1044
  76: rustc::dep_graph::graph::DepGraph::with_anon_task
             at librustc/traits/select.rs:915
             at librustc/traits/select.rs:1237
             at librustc/dep_graph/graph.rs:378
  77: rustc::traits::select::SelectionContext::in_task
             at librustc/traits/select.rs:1235
  78: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
             at librustc/traits/select.rs:915
             at librustc/traits/select.rs:698
  79: rustc::infer::InferCtxt::probe
             at librustc/traits/select.rs:671
             at librustc/traits/select.rs:1091
             at librustc/traits/select.rs:559
             at librustc/infer/mod.rs:854
  80: rustc::traits::select::SelectionContext::evaluate_candidate
             at librustc/traits/select.rs:559
             at librustc/traits/select.rs:1088
  81: <&mut I as core::iter::iterator::Iterator>::next
             at librustc/traits/select.rs:1376
             at /home/oliver/Projects/rust/rust4/src/libcore/ops/function.rs:286
             at /home/oliver/Projects/rust/rust4/src/libcore/option.rs:424
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:1394
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:1394
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:2686
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/mod.rs:2523
             at /home/oliver/Projects/rust/rust4/src/libcore/result.rs:1232
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/iterator.rs:2623
  82: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /home/oliver/Projects/rust/rust4/src/liballoc/vec.rs:1788
  83: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
             at /home/oliver/Projects/rust/rust4/src/liballoc/vec.rs:1700
             at /home/oliver/Projects/rust/rust4/src/libcore/result.rs:1249
             at /home/oliver/Projects/rust/rust4/src/libcore/iter/iterator.rs:1476
             at librustc/traits/select.rs:1374
  84: rustc::dep_graph::graph::DepGraph::with_anon_task
             at librustc/traits/select.rs:1216
             at librustc/traits/select.rs:1237
             at librustc/dep_graph/graph.rs:378
  85: rustc::traits::select::SelectionContext::in_task
             at librustc/traits/select.rs:1235
  86: rustc::traits::select::SelectionContext::candidate_from_obligation
             at librustc/traits/select.rs:1216
  87: rustc::traits::select::SelectionContext::select
             at librustc/traits/select.rs:597
  88: rustc::infer::InferCtxt::commit_if_ok
             at librustc/traits/project.rs:1056
             at librustc/infer/mod.rs:822
  89: rustc::traits::project::opt_normalize_projection_type
             at librustc/traits/project.rs:1055
             at librustc/traits/project.rs:914
             at librustc/traits/project.rs:642
  90: rustc::traits::project::project_and_unify_type
             at librustc/traits/project.rs:246
  91: rustc::infer::InferCtxt::commit_if_ok
             at librustc/traits/project.rs:210
             at librustc/infer/mod.rs:822
  92: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
             at librustc/traits/project.rs:205
             at librustc/traits/select.rs:825
  93: rustc::infer::InferCtxt::probe
             at librustc/traits/select.rs:671
             at librustc/traits/select.rs:1091
             at librustc/traits/select.rs:559
             at librustc/infer/mod.rs:854
  94: rustc::traits::select::SelectionContext::evaluate_candidate
             at librustc/traits/select.rs:559
             at librustc/traits/select.rs:1088
  95: rustc::traits::select::SelectionContext::evaluate_stack
             at librustc/traits/select.rs:1044
  96: rustc::dep_graph::graph::DepGraph::with_anon_task
             at librustc/traits/select.rs:915
             at librustc/traits/select.rs:1237
             at librustc/dep_graph/graph.rs:378
  97: rustc::traits::select::SelectionContext::in_task
             at librustc/traits/select.rs:1235
  98: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
             at librustc/traits/select.rs:915
             at librustc/traits/select.rs:698
  99: rustc::infer::InferCtxt::probe
             at librustc/traits/select.rs:671
             at librustc/traits/select.rs:1091
             at librustc/traits/select.rs:559
             at librustc/infer/mod.rs:854
