plain
travis_fold:end:after_failure.1
travis_fold:start:after_failure.2
travis_time:start:216df14c
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /homisting.
Do you need "set solib-search-path" or "set sysroot"?
Core was generated by `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc --crate-name core'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  LLVMRustDemoteSimdArguments () at ../rustllvm/DemoteSimd.cpp:105
105 ../rustllvm/DemoteSimd.cpp: No such file or directory.
#0  LLVMRustDemoteSimdArguments () at ../rustllvm/DemoteSimd.cpp:105
#1  0x00007f52dc5c7c13 in rustc_codegen_llvm::back::write::codegen::h5039c8b641469834 () from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#2  0x00007f52dc5cb91b in rustc_codegen_llvm::back::write::execute_work_item::h34b0aa62d2268ca6 () from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#3  0x00007f52dc5934c8 in std::sys_common::backtrace::__rust_begin_short_backtrace::h301299b992f7bb1e () from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#4  0x00007f52dc5bcd18 in std::panicking::try::do_call::hb9c7fd6d713d4119 () from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#5  0x00007f52e4636b1a in __rust_maybe_catch_panic () from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/../lib/libstd-0d136737b6669f47.so
#6  0x00007f52dc5bcb3b in std::panicking::try::h475196685066fb73 () from ./checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_code with 1.
