plain
[00:00:05] Cloning into '/home/travis/build/rust-lang/rust/src/stdsimd'...
[00:00:28] Cloning into '/home/travis/build/rust-lang/rust/src/tools/lld'...
[00:00:28] Cloning into '/home/travis/build/rust-lang/rust/src/tools/lldb'...
[00:00:28] Cloning into '/home/travis/build/rust-lang/rust/src/tools/clang'...
No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
