\n"},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/fully-qualified-type/fully-qualified-type-name1.rs","byte_start":580,"byte_end":581,"line_start":15,"line_end":15,"column_start":9,"column_end":10,"is_primary":true,"text":[{"text":"    x = 5;","highlight_start":9,"highlight_end":10}],"label":"expected enum `std::option::Option`, found integral variable","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"expected type `std::option::Option<usize>`\n   found type `{integer}`","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"try using a variant of the expected type","code":null,"level":"help","spans":[{"file_name":"/checkout/src/test/ui/fully-qualified-type/fully-qualified-type-name1.rs","byte_start":580,"byte_end":581,"line_start":15,"line_end":15,"column_start":9,"column_end":10,"is_primary":true,"text":[{"text":"    x = 5;","highlight_start":9,"highlight_end":10}],"label":null,"suggested_replacement":"std::option::Option::Some(5)","suggestion_applicability":"MaybeIncorrect","expansion":null}],"children":[],"rendered":null}],"rendered":"error[E0308]: mismatched types\n  --> /checkout/src/test/ui/fully-qualified-type/fully-qualified-type-name1.rs:15:9\n   |\nLL |     x = 5;\n   |         ^\n   |         |\n   |         expected enum `std::option::Option`, found integral variable\n   |         help: try using a variant of the expected type: `std::option::Op
[00:52:38] error: 1 errors occurred comparing output.
[00:52:38] status: exit code: 1
[00:52:38] status: exit code: 1
[00:52:38] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/issues/issue-39175.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-39175/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-39175/auxiliary" "-A" "unused"
[00:52:38] ------------------------------------------
[00:52:38] 
[00:52:38] ------------------------------------------
[00:52:38] stderr:
[00:52:38] stderr:
[00:52:38] ------------------------------------------
[00:52:38] {"message":"no method named `exec` found for type `&mut std::process::Command` in the current scope","code":{"code":"E0599","explanation":"\nThis error occurs when a method is used on a type which doesn't implement it:\n\nErroneous code example:\n\n