rust
// Defined by clippy (probably generated by a macro)
mod clippy_sim {
    pub const my_sim1: Symbol = Symbol::from_u32(Symbol::NUM_PREINTERNED + 0);
    pub const my_sim2: Symbol = Symbol::from_u32(Symbol::NUM_PREINTERNED + 1);
    pub const my_sim3: Symbol = Symbol::from_u32(Symbol::NUM_PREINTERNED + 2);
    ...
}

fn rustc_interface_prefill_extra_callback() -> &[&str] { // Defined by clippy, called by `Interner::prefill` in rustc
    &["my_sim1", "my_sim2", "my_sim3", ...]
}
