rust
#[derive(Foo)]
struct S {
    #[foo_helper] // marked as known
    field1: u8,
    #[some_attr]
    #[foo_helper] // marked as known
    field2: u8,
    field3: bang_macro_type!(), // `#[foo_helper]` inside the macro is NOT marked as known
}

// Generated by `Foo`
impl Foo for S {
    #[derive_helper] // NOT marked as known
    fn method(&self) { /* ... */ }
}
