rust
#[foo_attr] // #[proc_macro_attribute(attributes(foo_helper))] fn foo_attr(...) { ... }
struct S {
    // no need to erase this attribute from code generated by `foo_attr`,
    // it will be treated as a known helper attribute
    #[foo_helper]
    field: u8,
}
