rust
#[derive(Trait)]
struct S {
    field: type!(), // code inside `type!()` doesn't see the Trait's helpers
}

// Generated by the derive above
impl Trait for S { ... } // code in the generated impl also doesn't see the Trait's helpers
