
Core was generated by `rustc --crate-name zola src/main.rs --color always --crate-type bin --emit=dep-'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f00839a14b3 in llvm::CallGraphSCC::ReplaceNode(llvm::CallGraphNode*, llvm::CallGraphNode*) () from /usr/lib/libLLVM-8.so
[Current thread is 1 (LWP 16188)]
(gdb) bt
#0  0x00007f00839a14b3 in llvm::CallGraphSCC::ReplaceNode(llvm::CallGraphNode*, llvm::CallGraphNode*) () from /usr/lib/libLLVM-8.so
#1  0x00007f00837924dc in ?? () from /usr/lib/libLLVM-8.so
#2  0x00007f00839a37e5 in ?? () from /usr/lib/libLLVM-8.so
#3  0x00007f0082a99b26 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /usr/lib/libLLVM-8.so
#4  0x00007f0082a0dd79 in LLVMRunPassManager () from /usr/lib/libLLVM-8.so
#5  0x00007f008664acb7 in rustc_codegen_llvm::back::lto::run_pass_manager () from /usr/lib/rustlib/x86_64-foxkit-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so
#6  0x00007f008657aab3 in std::sys_common::backtrace::__rust_begin_short_backtrace () from /usr/lib/rustlib/x86_64-foxkit-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so
#7  0x00007f008657fe24 in std::panicking::try::do_call () from /usr/lib/rustlib/x86_64-foxkit-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so
#8  0x00007f0089008e4a in __rust_maybe_catch_panic (f=0x7f0064536510, data=0x394f <error: Cannot access memory at address 0x394f>, data_ptr=0x7f005d7f8500, vtable_ptr=0x7f005d7f8508) at src/libpanic_unwind/lib.rs:80
#9  0x00007f0086581173 in core::ops::function::FnOnce::call_once{{vtable-shim}} () from /usr/lib/rustlib/x86_64-foxkit-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so
#10 0x00007f0088fdb08f in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once (self=..., args=<optimized out>) at /usr/src/packages/user/rust/src/rustc-1.38.0-src/src/liballoc/boxed.rs:787
#11 0x00007f0089007cf0 in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once (self=<optimized out>, args=<optimized out>) at /usr/src/packages/user/rust/src/rustc-1.38.0-src/src/liballoc/boxed.rs:787
#12 std::sys_common::thread::start_thread (main=0x562e374248c0 "@\327\071Y.V") at src/libstd/sys_common/thread.rs:13
#13 std::sys::unix::thread::Thread::new::thread_start (main=0x562e374248c0) at src/libstd/sys/unix/thread.rs:79
#14 0x00007f008b4ce2ad in start (p=0x7f005d7f8920) at src/thread/pthread_create.c:192
#15 0x00007f008b4dc7f7 in __clone () at src/thread/x86_64/clone.s:22
Backtrace stopped: frame did not save the PC
