
failures:

---- build::compiler_json_error_format stdout ----
running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo build -v --message-format=json --jobs=1`
thread 'build::compiler_json_error_format' panicked at '
Expected: execs
    but: expected 6 json lines, got 8, stdout:
{"reason":"compiler-artifact","package_id":"foo 0.5.0 (path+file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo)","target":{"kind":["custom-build"],"crate_types":["bin"],"name":"build-script-build","src_path":"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/build.rs","edition":"2015","doctest":false},"profile":{"opt_level":"0","debuginfo":2,"debug_assertions":true,"overflow_checks":true,"test":false},"features":[],"filenames":["/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/target/debug/build/foo-a2fe4ed8615e06cb/build-script-build"],"executable":null,"fresh":false}
{"reason":"compiler-message","package_id":"bar 0.5.0 (path+file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/bar)","target":{"kind":["lib"],"crate_types":["lib"],"name":"bar","src_path":"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/bar/src/lib.rs","edition":"2015","doctest":true},"message":{"rendered":"warning: function is never used: `dead`\n --> bar/src/lib.rs:1:4\n  |\n1 | fn dead() {}\n  |    ^^^^\n  |\n  = note: `#[warn(dead_code)]` on by default\n\n","children":[{"children":[],"code":null,"level":"note","message":"`#[warn(dead_code)]` on by default","rendered":null,"spans":[]}],"code":{"code":"dead_code","explanation":null},"level":"warning","message":"function is never used: `dead`","spans":[{"byte_end":7,"byte_start":3,"column_end":8,"column_start":4,"expansion":null,"file_name":"bar/src/lib.rs","is_primary":true,"label":null,"line_end":1,"line_start":1,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":8,"highlight_start":4,"text":"fn dead() {}"}]}]}}
{"reason":"compiler-message","package_id":"bar 0.5.0 (path+file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/bar)","target":{"kind":["lib"],"crate_types":["lib"],"name":"bar","src_path":"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/bar/src/lib.rs","edition":"2015","doctest":true},"message":{"rendered":"warning: 1 warning emitted\n\n","children":[],"code":null,"level":"warning","message":"1 warning emitted","spans":[]}}
{"reason":"compiler-artifact","package_id":"bar 0.5.0 (path+file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/bar)","target":{"kind":["lib"],"crate_types":["lib"],"name":"bar","src_path":"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/bar/src/lib.rs","edition":"2015","doctest":true},"profile":{"opt_level":"0","debuginfo":2,"debug_assertions":true,"overflow_checks":true,"test":false},"features":[],"filenames":["/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/target/debug/deps/libbar-d1a517969926112a.rlib","/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/target/debug/deps/libbar-d1a517969926112a.rmeta"],"executable":null,"fresh":false}
{"reason":"build-script-executed","package_id":"foo 0.5.0 (path+file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo)","linked_libs":[],"linked_paths":[],"cfgs":["xyz"],"env":[],"out_dir":"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/target/debug/build/foo-b54076dc724f1a28/out"}
{"reason":"compiler-message","package_id":"foo 0.5.0 (path+file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo)","target":{"kind":["bin"],"crate_types":["bin"],"name":"foo","src_path":"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/src/main.rs","edition":"2015","doctest":false},"message":{"rendered":"warning: unused variable: `unused`\n --> src/main.rs:1:17\n  |\n1 | fn main() { let unused = 92; }\n  |                 ^^^^^^ help: if this is intentional, prefix it with an underscore: `_unused`\n  |\n  = note: `#[warn(unused_variables)]` on by default\n\n","children":[{"children":[],"code":null,"level":"note","message":"`#[warn(unused_variables)]` on by default","rendered":null,"spans":[]},{"children":[],"code":null,"level":"help","message":"if this is intentional, prefix it with an underscore","rendered":null,"spans":[{"byte_end":22,"byte_start":16,"column_end":23,"column_start":17,"expansion":null,"file_name":"src/main.rs","is_primary":true,"label":null,"line_end":1,"line_start":1,"suggested_replacement":"_unused","suggestion_applicability":"MachineApplicable","text":[{"highlight_end":23,"highlight_start":17,"text":"fn main() { let unused = 92; }"}]}]}],"code":{"code":"unused_variables","explanation":null},"level":"warning","message":"unused variable: `unused`","spans":[{"byte_end":22,"byte_start":16,"column_end":23,"column_start":17,"expansion":null,"file_name":"src/main.rs","is_primary":true,"label":null,"line_end":1,"line_start":1,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":23,"highlight_start":17,"text":"fn main() { let unused = 92; }"}]}]}}
{"reason":"compiler-message","package_id":"foo 0.5.0 (path+file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo)","target":{"kind":["bin"],"crate_types":["bin"],"name":"foo","src_path":"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/src/main.rs","edition":"2015","doctest":false},"message":{"rendered":"warning: 1 warning emitted\n\n","children":[],"code":null,"level":"warning","message":"1 warning emitted","spans":[]}}
{"reason":"compiler-artifact","package_id":"foo 0.5.0 (path+file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo)","target":{"kind":["bin"],"crate_types":["bin"],"name":"foo","src_path":"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/src/main.rs","edition":"2015","doctest":false},"profile":{"opt_level":"0","debuginfo":2,"debug_assertions":true,"overflow_checks":true,"test":false},"features":[],"filenames":["/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/target/debug/foo"],"executable":"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t214/foo/target/debug/foo","fresh":false}
', src/tools/cargo/crates/cargo-test-support/src/lib.rs:847:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- build::message_format_json_forward_stderr stdout ----
running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/cargo rustc --release --bin foo --message-format JSON`
thread 'build::message_format_json_forward_stderr' panicked at '
Expected: execs
    but: expected 2 json lines, got 3, stdout:
{"reason":"compiler-message","package_id":"foo 0.5.0 (path+file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t267/foo)","target":{"kind":["bin"],"crate_types":["bin"],"name":"foo","src_path":"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t267/foo/src/main.rs","edition":"2015","doctest":false},"message":{"rendered":"warning: unused variable: `unused`\n --> src/main.rs:1:17\n  |\n1 | fn main() { let unused = 0; }\n  |                 ^^^^^^ help: if this is intentional, prefix it with an underscore: `_unused`\n  |\n  = note: `#[warn(unused_variables)]` on by default\n\n","children":[{"children":[],"code":null,"level":"note","message":"`#[warn(unused_variables)]` on by default","rendered":null,"spans":[]},{"children":[],"code":null,"level":"help","message":"if this is intentional, prefix it with an underscore","rendered":null,"spans":[{"byte_end":22,"byte_start":16,"column_end":23,"column_start":17,"expansion":null,"file_name":"src/main.rs","is_primary":true,"label":null,"line_end":1,"line_start":1,"suggested_replacement":"_unused","suggestion_applicability":"MachineApplicable","text":[{"highlight_end":23,"highlight_start":17,"text":"fn main() { let unused = 0; }"}]}]}],"code":{"code":"unused_variables","explanation":null},"level":"warning","message":"unused variable: `unused`","spans":[{"byte_end":22,"byte_start":16,"column_end":23,"column_start":17,"expansion":null,"file_name":"src/main.rs","is_primary":true,"label":null,"line_end":1,"line_start":1,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":23,"highlight_start":17,"text":"fn main() { let unused = 0; }"}]}]}}
{"reason":"compiler-message","package_id":"foo 0.5.0 (path+file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t267/foo)","target":{"kind":["bin"],"crate_types":["bin"],"name":"foo","src_path":"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t267/foo/src/main.rs","edition":"2015","doctest":false},"message":{"rendered":"warning: 1 warning emitted\n\n","children":[],"code":null,"level":"warning","message":"1 warning emitted","spans":[]}}
{"reason":"compiler-artifact","package_id":"foo 0.5.0 (path+file:///checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t267/foo)","target":{"kind":["bin"],"crate_types":["bin"],"name":"foo","src_path":"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t267/foo/src/main.rs","edition":"2015","doctest":false},"profile":{"opt_level":"3","debuginfo":null,"debug_assertions":false,"overflow_checks":false,"test":false},"features":[],"filenames":["/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t267/foo/target/release/foo"],"executable":"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/cit/t267/foo/target/release/foo","fresh":false}
', src/tools/cargo/crates/cargo-test-support/src/lib.rs:847:13


failures:
    build::compiler_json_error_format
    build::message_format_json_forward_stderr

test result: FAILED. 1789 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test testsuite'
