
[DEBUG rustc_typeck::check] try_index_step(expr=Expr { hir_id: HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 28 }, kind: Index(Expr { hir_id: HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 24 }, kind: Path(Resolved(None, Path { span: src/test/ui/issues/issue-72002.rs:28:5: 28:6, res: Local(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 1 }), segments: [PathSegment { ident: v#0, hir_id: Some(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 23 }), res: Some(Local(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 1 })), args: None, infer_args: true }] })), attrs: ThinVec(None), span: src/test/ui/issues/issue-72002.rs:28:5: 28:6 }, Expr { hir_id: HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 27 }, kind: AddrOf(Ref, Not, Expr { hir_id: HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 26 }, kind: Path(Resolved(None, Path { span: src/test/ui/issues/issue-72002.rs:28:8: 28:13, res: Local(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 2 }), segments: [PathSegment { ident: field#0, hir_id: Some(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 25 }), res: Some(Local(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 2 })), args: None, infer_args: true }] })), attrs: ThinVec(None), span: src/test/ui/issues/issue-72002.rs:28:8: 28:13 }), attrs: ThinVec(None), span: src/test/ui/issues/issue-72002.rs:28:7: 28:13 }), attrs: ThinVec(None), span: src/test/ui/issues/issue-72002.rs:28:5: 28:14 }, base_expr=Expr { hir_id: HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 24 }, kind: Path(Resolved(None, Path { span: src/test/ui/issues/issue-72002.rs:28:5: 28:6, res: Local(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 1 }), segments: [PathSegment { ident: v#0, hir_id: Some(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 23 }), res: Some(Local(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 1 })), args: None, infer_args: true }] })), attrs: ThinVec(None), span: src/test/ui/issues/issue-72002.rs:28:5: 28:6 }, adjusted_ty=Indexable, index_ty=&std::string::String)
[DEBUG rustc_typeck::check] try_overloaded_place_op(src/test/ui/issues/issue-72002.rs:28:5: 28:14,Indexable,None,Index)
[DEBUG rustc_typeck::check::method] lookup_in_trait_adjusted(self_ty=Indexable, m_name=index, trait_def_id=DefId(2:2146 ~ core[4753]::ops[0]::index[0]::Index[0]))
[DEBUG rustc_typeck::check::method] lookup_in_trait_adjusted: substs=[Indexable, _]
[DEBUG rustc_typeck::check::method] lookup_in_trait_adjusted: obligation=Obligation(predicate=Binder(TraitPredicate(<Indexable as std::ops::Index<_>>)), depth=0) trait_ref=<Indexable as std::ops::Index<_>>
[DEBUG rustc_typeck::check::method] lookup_in_trait_adjusted: method_item=AssocItem { def_id: DefId(2:2149 ~ core[4753]::ops[0]::index[0]::Index[0]::index[0]), ident: index#0, kind: Fn, vis: Public, defaultness: Default { has_value: false }, container: TraitContainer(DefId(2:2146 ~ core[4753]::ops[0]::index[0]::Index[0])), fn_has_self_parameter: true }
[DEBUG rustc_typeck::check::method] lookup_in_trait_adjusted: matched method method_ty=fn(&Indexable, _) -> &Indexable obligation=Obligation(predicate=Binder(TraitPredicate(<Indexable as std::ops::Index<_>>)), depth=0)
[DEBUG rustc_typeck::check::method] callee = MethodCallee { def_id: DefId(2:2149 ~ core[4753]::ops[0]::index[0]::Index[0]::index[0]), substs: [Indexable, _], sig: ([&Indexable, _]; c_variadic: false)->&Indexable }
[DEBUG rustc_typeck::check] try_index_step: success, using overloaded indexing
[DEBUG rustc_typeck::check] register_predicate(Obligation(predicate=Binder(TraitPredicate(<Indexable as std::ops::Index<&str>>)), depth=0))
[DEBUG rustc_typeck::check] register_predicate(Obligation(predicate=WellFormed(fn(&Indexable, _) -> &Indexable), depth=0))
[DEBUG rustc_typeck::check] apply_adjustments(expr=Expr { hir_id: HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 24 }, kind: Path(Resolved(None, Path { span: src/test/ui/issues/issue-72002.rs:28:5: 28:6, res: Local(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 1 }), segments: [PathSegment { ident: v#0, hir_id: Some(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 23 }), res: Some(Local(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 1 })), args: None, infer_args: true }] })), attrs: ThinVec(None), span: src/test/ui/issues/issue-72002.rs:28:5: 28:6 }, adj=[Borrow(Ref('_#13r, Not)) -> &Indexable])
[DEBUG rustc_typeck::check] write_method_call(hir_id=HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 28 }, method=MethodCallee { def_id: DefId(2:2149 ~ core[4753]::ops[0]::index[0]::Index[0]::index[0]), substs: [Indexable, _], sig: ([&Indexable, _]; c_variadic: false)->&Indexable })
[DEBUG rustc_typeck::check] write_substs(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 28 }, [Indexable, _]) in fcx 0x700007e38178
[DEBUG rustc_typeck::check] resolve_vars_with_obligations(ty=_)
[DEBUG rustc_typeck::check] resolve_vars_with_obligations: ty=&str
[DEBUG rustc_typeck::check] resolve_vars_with_obligations(ty=&std::string::String)
[DEBUG rustc_typeck::check] resolve_vars_with_obligations: ty=&std::string::String
[DEBUG rustc_typeck::check::coercion] coercion::try(Expr { hir_id: HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 27 }, kind: AddrOf(Ref, Not, Expr { hir_id: HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 26 }, kind: Path(Resolved(None, Path { span: src/test/ui/issues/issue-72002.rs:28:8: 28:13, res: Local(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 2 }), segments: [PathSegment { ident: field#0, hir_id: Some(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 25 }), res: Some(Local(HirId { owner: DefId(0:12 ~ issue_72002[317d]::main[0]), local_id: 2 })), args: None, infer_args: true }] })), attrs: ThinVec(None), span: src/test/ui/issues/issue-72002.rs:28:8: 28:13 }), attrs: ThinVec(None), span: src/test/ui/issues/issue-72002.rs:28:7: 28:13 }: &std::string::String -> &str)
[DEBUG rustc_typeck::check::coercion] Coerce.tys(&std::string::String => &str)
[DEBUG rustc_typeck::check::coercion] coerce_unsized(source=&std::string::String, target=&str)
[DEBUG rustc_typeck::check::coercion] unify(a: _, b: &str, use_lub: false)
[DEBUG rustc_typeck::check::coercion] coerce_unsized resolve step: Obligation(predicate=Binder(TraitPredicate(<&std::string::String as std::ops::CoerceUnsized<_>>)), depth=0)
[DEBUG rustc_typeck::check::coercion] coerce_unsized resolve step: Obligation(predicate=Binder(OutlivesPredicate('_#19r, '_#18r)), depth=1)
[DEBUG rustc_typeck::check::coercion] coerce_unsized resolve step: Obligation(predicate=Binder(TraitPredicate(<std::string::String as std::marker::Unsize<str>>)), depth=1)
[DEBUG rustc_typeck::check::coercion] coerce_unsized: early return - can't prove obligation
[DEBUG rustc_typeck::check::coercion] coerce: unsize failed
[DEBUG rustc_typeck::check::coercion] coerce_borrowed_pointer(a=&std::string::String, b=&str)
[DEBUG rustc_typeck::check::autoderef] autoderef: steps=[], cur_ty=&std::string::String
[DEBUG rustc_typeck::check::autoderef] autoderef stage #0 is &std::string::String
[DEBUG rustc_typeck::check::autoderef] autoderef: steps=[], cur_ty=&std::string::String
[DEBUG rustc_typeck::check::autoderef] autoderef stage #1 is std::string::String from (&std::string::String, Builtin)
[DEBUG rustc_typeck::check::coercion] unify(a: &std::string::String, b: &str, use_lub: false)
[DEBUG rustc_typeck::check::autoderef] autoderef: steps=[(&std::string::String, Builtin)], cur_ty=std::string::String
[DEBUG rustc_typeck::check::autoderef] overloaded_deref_ty(std::string::String)
[DEBUG rustc_typeck::check::autoderef] overloaded_deref_ty(std::string::String) = (str, [])
[DEBUG rustc_typeck::check::autoderef] autoderef stage #2 is str from (std::string::String, Overloaded)
[DEBUG rustc_typeck::check::coercion] unify(a: &str, b: &str, use_lub: false)
[DEBUG rustc_typeck::check] try_overloaded_place_op(src/test/ui/issues/issue-72002.rs:28:7: 28:13,std::string::String,None,Deref)
[DEBUG rustc_typeck::check::method] lookup_in_trait_adjusted(self_ty=std::string::String, m_name=deref, trait_def_id=DefId(2:2065 ~ core[4753]::ops[0]::deref[0]::Deref[0]))
[DEBUG rustc_typeck::check::method] lookup_in_trait_adjusted: substs=[std::string::String]
[DEBUG rustc_typeck::check::method] lookup_in_trait_adjusted: obligation=Obligation(predicate=Binder(TraitPredicate(<std::string::String as std::ops::Deref>)), depth=0) trait_ref=<std::string::String as std::ops::Deref>
[DEBUG rustc_typeck::check::method] lookup_in_trait_adjusted: method_item=AssocItem { def_id: DefId(2:2067 ~ core[4753]::ops[0]::deref[0]::Deref[0]::deref[0]), ident: deref#0, kind: Fn, vis: Public, defaultness: Default { has_value: false }, container: TraitContainer(DefId(2:2065 ~ core[4753]::ops[0]::deref[0]::Deref[0])), fn_has_self_parameter: true }
[DEBUG rustc_typeck::check::method] lookup_in_trait_adjusted: matched method method_ty=fn(&std::string::String) -> &str obligation=Obligation(predicate=Binder(TraitPredicate(<std::string::String as std::ops::Deref>)), depth=0)
