
   Compiling cfg-if v0.1.10
     Running `/tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/build/bootstrap/debug/rustc --crate-name cfg_if --edition=2018 /tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/vendor/cfg-if/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C debuginfo=0 -C metadata=839ba1f5688689c8 -C extra-filename=-839ba1f5688689c8 --out-dir /tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C linker=x86_64-pc-linux-gnu-gcc -L dependency=/tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps -L dependency=/tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps --cap-lints allow --cfg=bootstrap -Zexternal-macro-backtrace -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings -Zunstable-options '-Wrustc::internal' -Cprefer-dynamic -Zbinary-dep-depinfo`
rustc command: "LD_LIBRARY_PATH"="/tmp/portage/dev-lang/rust-1.43.1/work/rust-stage0/lib:/tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps:/tmp/portage/dev-lang/rust-1.43.1/work/rust-stage0/lib" "/tmp/portage/dev-lang/rust-1.43.1/work/rust-stage0/bin/rustc" "--crate-name" "cfg_if" "--edition=2018" "/tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/vendor/cfg-if/src/lib.rs" "--error-format=json" "--json=diagnostic-rendered-ansi,artifacts" "--crate-type" "lib" "--emit=dep-info,metadata,link" "-C" "opt-level=3" "-C" "debuginfo=0" "-C" "metadata=839ba1f5688689c8" "-C" "extra-filename=-839ba1f5688689c8" "--out-dir" "/tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "--target" "x86_64-unknown-linux-gnu" "-C" "linker=x86_64-pc-linux-gnu-gcc" "-L" "dependency=/tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-L" "dependency=/tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps" "--cap-lints" "allow" "--cfg=bootstrap" "-Zexternal-macro-backtrace" "-Wrust_2018_idioms" "-Wunused_lifetimes" "-Dwarnings" "-Zunstable-options" "-Wrustc::internal" "-Cprefer-dynamic" "-Zbinary-dep-depinfo" "--sysroot" "/tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/build/x86_64-unknown-linux-gnu/stage0-sysroot" "-C" "debug-assertions=n" "-Z" "force-unstable-if-unmarked"
sysroot: "/tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/build/x86_64-unknown-linux-gnu/stage0-sysroot"
libdir: "/tmp/portage/dev-lang/rust-1.43.1/work/rust-stage0/lib"
[INFO  rustc_metadata::creader] resolving crate `core`
[INFO  rustc_metadata::creader] falling back to a load
[INFO  rustc_metadata::locator] lib candidate: /tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-17765580c343294b.rlib
[INFO  rustc_metadata::locator] rlib reading metadata from: /tmp/portage/dev-lang/rust-1.43.1/work/rustc-1.43.1-src/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-17765580c343294b.rlib
[INFO  rustc_metadata::locator] reading "libcore-17765580c343294b.rlib" => 63.478µs
[INFO  rustc_metadata::creader] register crate `core` (private_dep = false)
