
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 355f2829215..2d62df39459 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,7 +5,7 @@
 # This file was automatically generated by the expand-yaml-anchors tool. The
 # source file that generated this one is:
 #
-#   src/ci/github-actions/ci.yml
+#   src/ci/github-actions\ci.yml
 #
 # Once you make changes to that file you need to run:
 #
