
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "boolsatr"
version = "0.1.0"
dependencies = [
 "dc2",
 "lazy_fields",
]

[[package]]
name = "dc2"
version = "0.1.0"
source = "git+https://github.com/davidspies/dc2?branch=main#9e1fb2ea481ad9b8774a0c3a9d29460fec980a2b"

[[package]]
name = "lazy_fields"
version = "0.1.0"
source = "git+https://github.com/davidspies/lazy-fields?branch=main#79d2e45d2a43972938fd80048c9376dfeb0a029b"
