
> fd .html doc | xargs tidy --mute-id yes -quiet -o /dev/null
line 1 column 562 - Warning: <link> proprietary attribute "disabled" (PROPRIETARY_ATTRIBUTE)
line 1 column 630 - Warning: <link> proprietary attribute "disabled" (PROPRIETARY_ATTRIBUTE)
line 4 column 234 - Warning: <a> attribute "href" lacks value (MISSING_ATTR_VALUE)
line 1 column 558 - Warning: <link> proprietary attribute "disabled" (PROPRIETARY_ATTRIBUTE)
line 1 column 626 - Warning: <link> proprietary attribute "disabled" (PROPRIETARY_ATTRIBUTE)
line 4 column 472 - Warning: trimming empty <span> (TRIM_EMPTY_ELEMENT)
line 5 column 131 - Warning: trimming empty <span> (TRIM_EMPTY_ELEMENT)
line 5 column 323 - Warning: trimming empty <span> (TRIM_EMPTY_ELEMENT)
line 5 column 530 - Warning: trimming empty <span> (TRIM_EMPTY_ELEMENT)
line 5 column 739 - Warning: trimming empty <span> (TRIM_EMPTY_ELEMENT)
line 5 column 920 - Warning: trimming empty <span> (TRIM_EMPTY_ELEMENT)
line 5 column 1120 - Warning: trimming empty <span> (TRIM_EMPTY_ELEMENT)
line 5 column 1302 - Warning: trimming empty <span> (TRIM_EMPTY_ELEMENT)
line 1 column 532 - Warning: <link> proprietary attribute "disabled" (PROPRIETARY_ATTRIBUTE)
line 1 column 599 - Warning: <link> proprietary attribute "disabled" (PROPRIETARY_ATTRIBUTE)
line 4 column 628 - Warning: <select> proprietary attribute "autocomplete" (PROPRIETARY_ATTRIBUTE)
line 4 column 951 - Warning: <select> proprietary attribute "autocomplete" (PROPRIETARY_ATTRIBUTE)
line 1 column 557 - Warning: <link> proprietary attribute "disabled" (PROPRIETARY_ATTRIBUTE)
line 1 column 628 - Warning: <link> proprietary attribute "disabled" (PROPRIETARY_ATTRIBUTE)
