
1 error: linking with `cc` failed: exit status: 1
2    |
-    = note: "cc" "-m64" "$TEST_BUILD_DIR/dylibs/issue-82151-serverctl-prefdyn/issue-82151-serverctl-prefdyn.issue_82151_serverctl_prefdyn.72d5a704-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "$BUILD_DIR/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "$TEST_BUILD_DIR/dylibs/issue-82151-serverctl-prefdyn/auxiliary" "-L" "$BUILD_DIR/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "$TEST_BUILD_DIR/dylibs/issue-82151-serverctl-prefdyn/auxiliary" "-lshared" "-L" "$TEST_BUILD_DIR/dylibs/issue-82151-serverctl-prefdyn/auxiliary" "-lbar" "-Wl,--start-group" "-L" "$BUILD_DIR/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-lstd-f2409c1bc0340a9e" "-Wl,--end-group" "-Wl,-Bstatic" "$BUILD_DIR/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-bc417570076b2daa.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "$BUILD_DIR/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "$TEST_BUILD_DIR/dylibs/issue-82151-serverctl-prefdyn/issue-82151-serverctl-prefdyn" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-Wl,-rpath,$ORIGIN/auxiliary" "-Wl,-rpath,$ORIGIN/../../../../stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--enable-new-dtags"
-    = note: /usr/bin/ld: $TEST_BUILD_DIR/dylibs/issue-82151-serverctl-prefdyn/auxiliary/libshared.so: undefined reference to `bar::bar'
+    = note: "cc" "-m64" "$TEST_BUILD_DIR/dylibs/issue-82151-serverctl-prefdyn/issue-82151-serverctl-prefdyn.issue_82151_serverctl_prefdyn.72d5a704-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "$BUILD_DIR/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "$TEST_BUILD_DIR/dylibs/issue-82151-serverctl-prefdyn/auxiliary" "-L" "$BUILD_DIR/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "$TEST_BUILD_DIR/dylibs/issue-82151-serverctl-prefdyn/auxiliary" "-lshared" "-L" "$TEST_BUILD_DIR/dylibs/issue-82151-serverctl-prefdyn/auxiliary" "-lbar" "-Wl,--start-group" "-L" "$BUILD_DIR/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-lstd-979615b1d869d792" "-Wl,--end-group" "-Wl,-Bstatic" "$BUILD_DIR/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-52fe0581016e3544.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "$BUILD_DIR/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "$TEST_BUILD_DIR/dylibs/issue-82151-serverctl-prefdyn/issue-82151-serverctl-prefdyn" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-Wl,-rpath,$ORIGIN/auxiliary" "-Wl,-rpath,$ORIGIN/../../../../stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--enable-new-dtags"
+    = note: $TEST_BUILD_DIR/dylibs/issue-82151-serverctl-prefdyn/auxiliary/libshared.so: undefined reference to `bar::bar'
5            collect2: error: ld returned 1 exit status
Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
6            
7    = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
