plain
Verifying status of rls...
Verifying status of miri...
Verifying status of embedded-book...
Cloning into 'rust-toolstate'...
error: Tool `rls` should be test-pass but is build-fail
{"reference":"test-pass","rustbook":"test-fail","rls":"build-fail","cargo-miri":"test-fail","nomicon":"test-pass","embedded-book":"test-pass","rust-by-example":"test-pass","miri":"test-fail","book":"test-pass","edition-guide":"test-pass"}Build completed unsuccessfully in 0:00:00
