
orphan_check_impl() // this errors and increases the error count
...
x = new InferCtxt
...
specialization_graph_of() // this doesn't error because of the error in `orphan_check_impl` above
...
x.is_tainted_by_errors() // now returns `false`
