plain
---- compile_test stdout ----

error: failed to compile fixed code
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/clippy-driver" "tests/ui/iter_count.fixed" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/test" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/test/iter_count.stage-id" "--emit=metadata" "-Dwarnings" "-Zui-testing" "-L" "dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps" "-L" "dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps" "--extern" "syn=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libsyn-2c42e7af51424ce5.rlib" "--extern" "serde=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libserde-89222f6e0d369b36.rlib" "--extern" "serde_derive=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libserde_derive-8bd56d0234290b82.so" "--extern" "itertools=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libitertools-b0f19a5fad83a10b.rlib" "--extern" "regex=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libregex-392b40a2759b0504.rlib" "--extern" "if_chain=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libif_chain-b3e76e8f62643cc6.rlib" "--extern" "clippy_utils=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libclippy_utils-bc2b0c8a9dcb9fb3.rlib" "--extern" "derive_new=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libderive_new-ea1db0c41efed0d6.so" "--extern" "quote=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libquote-c6bd037ba33baa25.rlib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/test/iter_count.stage-id.aux"
stdout:
------------------------------------------

------------------------------------------
------------------------------------------
stderr:
------------------------------------------
{"message":"unused return value of `std::collections::BTreeMap::<K, V>::len` that must be used","code":{"code":"unused_must_use","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/iter_count.fixed","byte_start":1523,"byte_end":1540,"line_start":59,"line_end":59,"column_start":5,"column_end":22,"is_primary":true,"text":[{"text":"    b_tree_map.len();","highlight_start":5,"highlight_end":22}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"`-D unused-must-use` implied by `-D warnings`","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"error: unused return value of `std::collections::BTreeMap::<K, V>::len` that must be used\n  --> tests/ui/iter_count.fixed:59:5\n   |\nLL |     b_tree_map.len();\n   |     ^^^^^^^^^^^^^^^^^\n   |\n   = note: `-D unused-must-use` implied by `-D warnings`\n\n"}
{"message":"unused return value of `std::collections::BTreeSet::<T>::len` that must be used","code":{"code":"unused_must_use","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/iter_count.fixed","byte_start":1545,"byte_end":1562,"line_start":60,"line_end":60,"column_start":5,"column_end":22,"is_primary":true,"text":[{"text":"    b_tree_set.len();","highlight_start":5,"highlight_end":22}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: unused return value of `std::collections::BTreeSet::<T>::len` that must be used\n  --> tests/ui/iter_count.fixed:60:5\n   |\nLL |     b_tree_set.len();\n   |     ^^^^^^^^^^^^^^^^^\n\n"}
{"message":"unused return value of `std::collections::LinkedList::<T>::len` that must be used","code":{"code":"unused_must_use","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/iter_count.fixed","byte_start":1567,"byte_end":1585,"line_start":61,"line_end":61,"column_start":5,"column_end":23,"is_primary":true,"text":[{"text":"    linked_list.len();","highlight_start":5,"highlight_end":23}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: unused return value of `std::collections::LinkedList::<T>::len` that must be used\n  --> tests/ui/iter_count.fixed:61:5\n   |\nLL |     linked_list.len();\n   |     ^^^^^^^^^^^^^^^^^^\n\n"}
{"message":"unused return value of `std::collections::BinaryHeap::<T>::len` that must be used","code":{"code":"unused_must_use","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/iter_count.fixed","byte_start":1590,"byte_end":1608,"line_start":62,"line_end":62,"column_start":5,"column_end":23,"is_primary":true,"text":[{"text":"    binary_heap.len();","highlight_start":5,"highlight_end":23}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: unused return value of `std::collections::BinaryHeap::<T>::len` that must be used\n  --> tests/ui/iter_count.fixed:62:5\n   |\nLL |     binary_heap.len();\n   |     ^^^^^^^^^^^^^^^^^^\n\n"}
{"message":"unused return value of `std::collections::BTreeMap::<K, V>::len` that must be used","code":{"code":"unused_must_use","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/iter_count.fixed","byte_start":1698,"byte_end":1715,"line_start":68,"line_end":68,"column_start":5,"column_end":22,"is_primary":true,"text":[{"text":"    b_tree_map.len();","highlight_start":5,"highlight_end":22}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: unused return value of `std::collections::BTreeMap::<K, V>::len` that must be used\n  --> tests/ui/iter_count.fixed:68:5\n   |\nLL |     b_tree_map.len();\n   |     ^^^^^^^^^^^^^^^^^\n\n"}
{"message":"unused return value of `std::collections::LinkedList::<T>::len` that must be used","code":{"code":"unused_must_use","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/iter_count.fixed","byte_start":1720,"byte_end":1738,"line_start":69,"line_end":69,"column_start":5,"column_end":23,"is_primary":true,"text":[{"text":"    linked_list.len();","highlight_start":5,"highlight_end":23}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: unused return value of `std::collections::LinkedList::<T>::len` that must be used\n  --> tests/ui/iter_count.fixed:69:5\n   |\nLL |     linked_list.len();\n   |     ^^^^^^^^^^^^^^^^^^\n\n"}
{"message":"unused return value of `std::collections::BTreeMap::<K, V>::len` that must be used","code":{"code":"unused_must_use","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/iter_count.fixed","byte_start":1848,"byte_end":1865,"line_start":76,"line_end":76,"column_start":5,"column_end":22,"is_primary":true,"text":[{"text":"    b_tree_map.len();","highlight_start":5,"highlight_end":22}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: unused return value of `std::collections::BTreeMap::<K, V>::len` that must be used\n  --> tests/ui/iter_count.fixed:76:5\n   |\nLL |     b_tree_map.len();\n   |     ^^^^^^^^^^^^^^^^^\n\n"}
{"message":"unused return value of `std::collections::BTreeSet::<T>::len` that must be used","code":{"code":"unused_must_use","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/iter_count.fixed","byte_start":1870,"byte_end":1887,"line_start":77,"line_end":77,"column_start":5,"column_end":22,"is_primary":true,"text":[{"text":"    b_tree_set.len();","highlight_start":5,"highlight_end":22}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: unused return value of `std::collections::BTreeSet::<T>::len` that must be used\n  --> tests/ui/iter_count.fixed:77:5\n   |\nLL |     b_tree_set.len();\n   |     ^^^^^^^^^^^^^^^^^\n\n"}
{"message":"unused return value of `std::collections::LinkedList::<T>::len` that must be used","code":{"code":"unused_must_use","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/iter_count.fixed","byte_start":1892,"byte_end":1910,"line_start":78,"line_end":78,"column_start":5,"column_end":23,"is_primary":true,"text":[{"text":"    linked_list.len();","highlight_start":5,"highlight_end":23}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: unused return value of `std::collections::LinkedList::<T>::len` that must be used\n  --> tests/ui/iter_count.fixed:78:5\n   |\nLL |     linked_list.len();\n   |     ^^^^^^^^^^^^^^^^^^\n\n"}
{"message":"unused return value of `std::collections::BinaryHeap::<T>::len` that must be used","code":{"code":"unused_must_use","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/iter_count.fixed","byte_start":1915,"byte_end":1933,"line_start":79,"line_end":79,"column_start":5,"column_end":23,"is_primary":true,"text":[{"text":"    binary_heap.len();","highlight_start":5,"highlight_end":23}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: unused return value of `std::collections::BinaryHeap::<T>::len` that must be used\n  --> tests/ui/iter_count.fixed:79:5\n   |\nLL |     binary_heap.len();\n   |     ^^^^^^^^^^^^^^^^^^\n\n"}

------------------------------------------

thread 'compile_test' panicked at 'Some tests failed', /cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.7.0/src/lib.rs:105:22
