rust
let e_flags = elf::EF_MIPS_CPIC
    | elf::EF_MIPS_PIC
    | if sess.target.options.cpu.contains("r6") {
        // copied from the `e_flags` field of the object
        // generated by `mipsisa64r6el-linux-gnuabi64-gcc foo.c -c`
        elf::EF_MIPS_ARCH_64R6 | elf::EF_MIPS_NAN2008
    } else {
        elf::EF_MIPS_ARCH_64R2
    };
