text
Adding src/tools/rust-analyzer/xtask/src/release/changelog.rs
Adding src/tools/rust-analyzer/xtask/src/release.rs
Adding src/tools/rust-analyzer/xtask/src/metrics.rs
Adding src/tools/rust-analyzer/xtask/src/main.rs
Adding src/tools/rust-analyzer/xtask/src/install.rs
Adding src/tools/rust-analyzer/xtask/src/flags.rs
Adding src/tools/rust-analyzer/xtask/src/dist.rs
Adding src/tools/rust-analyzer/xtask/Cargo.toml
Adding src/tools/rust-analyzer/rustfmt.toml
Adding src/tools/rust-analyzer/lib/arena/src/map.rs
Adding src/tools/rust-analyzer/lib/arena/src/lib.rs
Adding src/tools/rust-analyzer/lib/arena/Cargo.toml
Adding src/tools/rust-analyzer/lib/README.md
Adding src/tools/rust-analyzer/editors/code/tsconfig.json
Adding src/tools/rust-analyzer/editors/code/tests/unit/runnable_env.test.ts
Adding src/tools/rust-analyzer/editors/code/tests/unit/launch_config.test.ts
Adding src/tools/rust-analyzer/editors/code/tests/unit/index.ts
Adding src/tools/rust-analyzer/editors/code/tests/runTests.ts
Adding src/tools/rust-analyzer/editors/code/src/util.ts
Adding src/tools/rust-analyzer/editors/code/src/toolchain.ts
Adding src/tools/rust-analyzer/editors/code/src/tasks.ts
Adding src/tools/rust-analyzer/editors/code/src/snippets.ts
Adding src/tools/rust-analyzer/editors/code/src/run.ts
Adding src/tools/rust-analyzer/editors/code/src/persistent_state.ts
Adding src/tools/rust-analyzer/editors/code/src/net.ts
Adding src/tools/rust-analyzer/editors/code/src/main.ts
Adding src/tools/rust-analyzer/editors/code/src/lsp_ext.ts
Adding src/tools/rust-analyzer/editors/code/src/inlay_hints.ts
Adding src/tools/rust-analyzer/editors/code/src/debug.ts
Adding src/tools/rust-analyzer/editors/code/src/ctx.ts
Adding src/tools/rust-analyzer/editors/code/src/config.ts
Adding src/tools/rust-analyzer/editors/code/src/commands.ts
Adding src/tools/rust-analyzer/editors/code/src/client.ts
Adding src/tools/rust-analyzer/editors/code/src/ast_inspector.ts
Adding src/tools/rust-analyzer/editors/code/ra_syntax_tree.tmGrammar.json
Adding src/tools/rust-analyzer/editors/code/package.json
Adding src/tools/rust-analyzer/editors/code/language-configuration.json
Adding src/tools/rust-analyzer/editors/code/icon.png
Adding src/tools/rust-analyzer/editors/code/README.md
Adding src/tools/rust-analyzer/editors/code/.vscodeignore
Adding src/tools/rust-analyzer/editors/code/.gitignore
Adding src/tools/rust-analyzer/editors/code/.eslintrc.js
Adding src/tools/rust-analyzer/editors/code/.eslintignore
Adding src/tools/rust-analyzer/docs/user/manual.adoc
Adding src/tools/rust-analyzer/docs/user/generated_config.adoc
Adding src/tools/rust-analyzer/docs/user/.gitignore
Adding src/tools/rust-analyzer/docs/dev/syntax.md
Adding src/tools/rust-analyzer/docs/dev/style.md
Adding src/tools/rust-analyzer/docs/dev/lsp-extensions.md
Adding src/tools/rust-analyzer/docs/dev/guide.md
Adding src/tools/rust-analyzer/docs/dev/debugging.md
Adding src/tools/rust-analyzer/docs/dev/architecture.md
Adding src/tools/rust-analyzer/docs/dev/README.md
Adding src/tools/rust-analyzer/crates/vfs/src/vfs_path/tests.rs
Adding src/tools/rust-analyzer/crates/vfs/src/vfs_path.rs
Adding src/tools/rust-analyzer/crates/vfs/src/path_interner.rs
Adding src/tools/rust-analyzer/crates/vfs/src/loader.rs
Adding src/tools/rust-analyzer/crates/vfs/src/lib.rs
Adding src/tools/rust-analyzer/crates/vfs/src/file_set/tests.rs
Adding src/tools/rust-analyzer/crates/vfs/src/file_set.rs
Adding src/tools/rust-analyzer/crates/vfs/src/anchored_path.rs
Adding src/tools/rust-analyzer/crates/vfs/Cargo.toml
Adding src/tools/rust-analyzer/crates/vfs-notify/src/lib.rs
Adding src/tools/rust-analyzer/crates/vfs-notify/Cargo.toml
Adding src/tools/rust-analyzer/crates/tt/src/lib.rs
Adding src/tools/rust-analyzer/crates/tt/src/buffer.rs
Adding src/tools/rust-analyzer/crates/tt/Cargo.toml
Adding src/tools/rust-analyzer/crates/toolchain/src/lib.rs
Adding src/tools/rust-analyzer/crates/toolchain/Cargo.toml
Adding src/tools/rust-analyzer/crates/text_edit/src/lib.rs
Adding src/tools/rust-analyzer/crates/text_edit/Cargo.toml
Adding src/tools/rust-analyzer/crates/test_utils/src/minicore.rs
Adding src/tools/rust-analyzer/crates/test_utils/src/lib.rs
Adding src/tools/rust-analyzer/crates/test_utils/src/fixture.rs
Adding src/tools/rust-analyzer/crates/test_utils/src/bench_fixture.rs
Adding src/tools/rust-analyzer/crates/test_utils/src/assert_linear.rs
Adding src/tools/rust-analyzer/crates/test_utils/Cargo.toml
Adding src/tools/rust-analyzer/crates/syntax/test_data/reparse/fuzz-failures/0005.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/reparse/fuzz-failures/0004.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/reparse/fuzz-failures/0003.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/reparse/fuzz-failures/0002.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/reparse/fuzz-failures/0001.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/reparse/fuzz-failures/0000.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0071_stmt_attr_placement.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0071_stmt_attr_placement.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0070_expr_attr_placement.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0070_expr_attr_placement.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0069_multi_trait_object.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0069_multi_trait_object.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0068_item_modifiers.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0068_item_modifiers.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0067_where_for_pred.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0067_where_for_pred.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0066_default_modifier.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0066_default_modifier.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0065_plus_after_fn_trait_bound.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0065_plus_after_fn_trait_bound.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0065_comment_newline.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0065_comment_newline.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0064_impl_fn_params.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0064_impl_fn_params.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0063_variadic_fun.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0063_variadic_fun.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0063_trait_fn_patterns.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0063_trait_fn_patterns.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0062_macro_2.0.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0062_macro_2.0.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0061_match_full_range.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0061_match_full_range.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0060_as_range.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0060_as_range.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0059_loops_in_parens.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0059_loops_in_parens.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0058_unary_expr_precedence.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0058_unary_expr_precedence.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0057_loop_in_call.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0057_loop_in_call.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0056_neq_in_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0056_neq_in_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0055_dot_dot_dot.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0055_dot_dot_dot.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0054_qual_path_in_type_arg.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0054_qual_path_in_type_arg.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0053_outer_attribute_on_macro_rules.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0053_outer_attribute_on_macro_rules.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0052_for_range_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0052_for_range_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0051_parameter_attrs.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0051_parameter_attrs.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0050_async_block_as_argument.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0050_async_block_as_argument.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0049_async_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0049_async_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0048_compound_assignment.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0048_compound_assignment.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0047_minus_in_inner_pattern.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0047_minus_in_inner_pattern.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0046_extern_inner_attributes.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0046_extern_inner_attributes.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0045_block_attrs.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0045_block_attrs.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0044_let_attrs.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0044_let_attrs.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0043_complex_assignment.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0043_complex_assignment.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0042_ufcs_call_list.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0042_ufcs_call_list.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0041_raw_keywords.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0041_raw_keywords.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0040_raw_struct_item_field.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0040_raw_struct_item_field.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0039_raw_fn_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0039_raw_fn_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0038_where_pred_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0038_where_pred_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0037_mod.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0037_mod.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0036_fully_qualified.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0036_fully_qualified.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0035_weird_exprs.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0035_weird_exprs.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0034_crate_path_in_call.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0034_crate_path_in_call.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0033_label_break.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0033_label_break.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0032_where_for.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0032_where_for.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0031_extern.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0031_extern.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0030_traits.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0030_traits.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0030_string_suffixes.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0030_string_suffixes.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0029_range_forms.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0029_range_forms.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0028_operator_binding_power.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0028_operator_binding_power.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0027_unsafe_fn_in_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0027_unsafe_fn_in_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0026_const_fn_in_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0026_const_fn_in_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0025_extern_fn_in_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0025_extern_fn_in_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0024_const_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0024_const_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0023_static_items.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0023_static_items.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0022_empty_extern_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0022_empty_extern_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0020_type_param_bounds.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0020_type_param_bounds.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0019_enums.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0019_enums.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0018_struct_type_params.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0018_struct_type_params.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0017_attr_trailing_comma.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0017_attr_trailing_comma.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0016_struct_flavors.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0016_struct_flavors.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0015_use_tree.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0015_use_tree.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0014_use_tree.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0014_use_tree.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0013_use_path_self_super.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0013_use_path_self_super.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0012_visibility.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0012_visibility.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0011_outer_attribute.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0011_outer_attribute.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0010_use_path_segments.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0010_use_path_segments.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0009_use_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0009_use_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0008_mod_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0008_mod_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0007_extern_crate.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0007_extern_crate.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0006_inner_attributes.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0006_inner_attributes.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0005_fn_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0005_fn_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0004_file_shebang.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0004_file_shebang.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0002_struct_item_field.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0002_struct_item_field.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0001_struct_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0001_struct_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0000_empty.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/ok/0000_empty.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0194_macro_inside_generic_arg.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0194_macro_inside_generic_arg.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0194_let_stmt_ascription.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0194_let_stmt_ascription.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0194_let_else.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0194_let_else.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0193_let_stmt_init.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0193_let_stmt_init.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0192_const_arg_bool_literal.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0192_const_arg_bool_literal.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0191_const_arg_negative_number.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0191_const_arg_negative_number.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0190_generic_arg.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0190_generic_arg.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0189_const_arg_literal.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0189_const_arg_literal.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0188_const_arg_path.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0188_const_arg_path.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0187_assoc_type_eq.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0187_assoc_type_eq.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0186_lifetime_arg.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0186_lifetime_arg.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0185_assoc_type_bound.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0185_assoc_type_bound.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0184_generic_param_list.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0184_generic_param_list.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0184_const_arg.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0184_const_arg.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0183_type_param.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0183_type_param.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0183_const_arg_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0183_const_arg_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0182_lifetime_param.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0182_lifetime_param.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0181_use_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0181_use_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0181_generic_param_attribute.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0181_generic_param_attribute.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0180_use_tree_path_star.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0180_use_tree_path_star.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0179_use_tree_abs_star.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0179_use_tree_abs_star.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0178_use_tree_path_use_tree.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0178_use_tree_path_use_tree.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0177_use_tree_path.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0177_use_tree_path.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0177_use_tree.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0177_use_tree.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0177_trait_alias_where_clause.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0177_trait_alias_where_clause.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0177_assoc_item_list_inner_attrs.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0177_assoc_item_list_inner_attrs.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0176_use_tree_alias.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0176_use_tree_alias.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0176_trait_item_where_clause.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0176_trait_item_where_clause.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0175_trait_item_bounds.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0175_trait_item_bounds.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0174_use_tree_star.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0174_use_tree_star.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0174_unit_struct.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0174_unit_struct.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0174_trait_item_generic_params.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0174_trait_item_generic_params.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0173_union_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0173_union_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0173_macro_def_curly.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0173_macro_def_curly.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0173_anonymous_const.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0173_anonymous_const.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0172_record_field_list.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0172_record_field_list.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0172_const_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0172_const_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0171_struct_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0171_struct_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0170_tuple_struct.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0170_tuple_struct.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0170_mod_item_curly.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0170_mod_item_curly.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0169_mod_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0169_mod_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0168_extern_crate_self.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0168_extern_crate_self.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0168_extern_crate_rename.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0168_extern_crate_rename.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0166_half_open_range_pat.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0166_half_open_range_pat.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0165_const_param_defaults.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0165_const_param_defaults.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0164_type_path_in_pattern.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0164_type_path_in_pattern.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0164_default_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0164_default_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0163_default_unsafe_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0163_default_unsafe_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0163_default_async_fn.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0163_default_async_fn.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0162_unsafe_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0162_unsafe_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0162_default_async_unsafe_fn.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0162_default_async_unsafe_fn.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0161_labeled_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0161_labeled_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0161_impl_item_const.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0161_impl_item_const.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0160_try_macro_rules.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0160_try_macro_rules.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0160_crate_visibility_in.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0160_crate_visibility_in.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0159_yield_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0159_yield_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0159_try_macro_fallback.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0159_try_macro_fallback.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0158_macro_rules_non_brace.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0158_macro_rules_non_brace.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0158_lambda_ret_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0158_lambda_ret_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0158_binop_resets_statementness.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0158_binop_resets_statementness.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0157_variant_discriminant.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0157_variant_discriminant.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0157_fn_pointer_unnamed_arg.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0157_fn_pointer_unnamed_arg.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0157_const_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0157_const_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0156_or_pattern.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0156_or_pattern.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0156_fn_def_param.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0156_fn_def_param.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0156_const_block_pat.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0156_const_block_pat.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0155_closure_params.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0155_closure_params.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0154_tuple_attrs.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0154_tuple_attrs.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0154_no_dyn_trait_leading_for.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0154_no_dyn_trait_leading_for.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0154_fn_pointer_param_ident_path.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0154_fn_pointer_param_ident_path.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0153_pub_parens_typepath.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0153_pub_parens_typepath.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0152_arg_with_attr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0152_arg_with_attr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0151_trait_alias.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0151_trait_alias.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0151_fn.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0151_fn.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0150_impl_type_params.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0150_impl_type_params.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0150_array_attrs.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0150_array_attrs.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0147_macro_def.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0147_macro_def.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0147_const_param.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0147_const_param.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0146_as_precedence.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0146_as_precedence.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0145_record_pat_field.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0145_record_pat_field.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0144_dot_dot_pat.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0144_dot_dot_pat.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0143_box_pat.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0143_box_pat.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0142_for_range_from.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0142_for_range_from.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0139_param_outer_arg.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0139_param_outer_arg.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0138_self_param_outer_attr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0138_self_param_outer_attr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0138_expression_after_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0138_expression_after_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0138_associated_type_bounds.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0138_associated_type_bounds.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0137_await_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0137_await_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0134_nocontentexpr_after_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0134_nocontentexpr_after_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0132_box_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0132_box_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0131_existential_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0131_existential_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0130_try_block_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0130_try_block_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0130_let_stmt.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0130_let_stmt.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0129_marco_pat.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0129_marco_pat.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0126_attr_on_expr_stmt.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0126_attr_on_expr_stmt.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0125_record_literal_field_with_attr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0125_record_literal_field_with_attr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0125_crate_keyword_path.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0125_crate_keyword_path.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0123_param_list_vararg.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0123_param_list_vararg.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0121_match_arms_outer_attributes.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0121_match_arms_outer_attributes.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0120_match_arms_inner_attribute.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0120_match_arms_inner_attribute.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0118_match_guard.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0118_match_guard.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0117_macro_call_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0117_macro_call_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0115_tuple_field_attrs.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0115_tuple_field_attrs.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0114_tuple_struct_where.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0114_tuple_struct_where.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0113_nocontentexpr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0113_nocontentexpr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0112_bind_pat.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0112_bind_pat.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0111_tuple_pat.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0111_tuple_pat.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0109_label.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0109_label.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0108_tuple_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0108_tuple_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0107_method_call_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0107_method_call_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0106_lambda_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0106_lambda_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0104_path_fn_trait_args.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0104_path_fn_trait_args.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0103_array_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0103_array_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0102_record_pat_field_list.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0102_record_pat_field_list.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0100_for_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0100_for_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0099_param_list.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0099_param_list.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0096_no_semi_after_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0096_no_semi_after_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0095_placeholder_pat.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0095_placeholder_pat.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0093_index_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0093_index_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0092_fn_pointer_type_with_ret.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0092_fn_pointer_type_with_ret.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0090_type_param_default.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0090_type_param_default.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0088_break_ambiguity.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0088_break_ambiguity.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0086_function_ret_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0086_function_ret_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0085_expr_literals.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0085_expr_literals.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0084_paren_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0084_paren_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0083_struct_items.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0082_ref_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0082_ref_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0081_for_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0081_for_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0080_postfix_range.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0080_postfix_range.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0079_impl_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0079_impl_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0078_type_alias.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0078_type_alias.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0077_try_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0077_try_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0076_function_where_clause.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0076_function_where_clause.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0075_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0075_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0074_stmt_postfix_expr_ambiguity.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0074_stmt_postfix_expr_ambiguity.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0073_type_item_type_params.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0073_type_item_type_params.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0072_return_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0072_return_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0071_match_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0071_match_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0070_stmt_bin_expr_ambiguity.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0070_stmt_bin_expr_ambiguity.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0067_crate_path.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0067_crate_path.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0066_match_arm.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0066_match_arm.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0065_dyn_trait_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0065_dyn_trait_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0064_if_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0064_if_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0063_impl_item_neg.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0063_impl_item_neg.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0062_mod_contents.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0062_mod_contents.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0061_record_lit.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0061_record_lit.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0060_extern_crate.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0060_extern_crate.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0059_match_arms_commas.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0059_match_arms_commas.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0058_range_pat.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0058_range_pat.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0056_where_clause.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0056_where_clause.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0055_literal_pattern.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0055_literal_pattern.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0054_record_field_attrs.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0054_record_field_attrs.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0053_path_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0053_path_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0052_path_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0052_path_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0051_unit_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0051_unit_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0050_fn_decl.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0050_fn_decl.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0048_path_type_with_bounds.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0048_path_type_with_bounds.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0046_singleton_tuple_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0046_singleton_tuple_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0045_param_list_opt_patterns.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0045_param_list_opt_patterns.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0044_block_items.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0044_block_items.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0042_call_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0042_call_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0041_trait_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0041_trait_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0040_crate_keyword_vis.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0040_crate_keyword_vis.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0038_full_range_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0038_full_range_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0037_qual_paths.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0037_qual_paths.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0034_break_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0034_break_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0033_reference_type;.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0033_reference_type;.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0032_fn_pointer_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0032_fn_pointer_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0031_while_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0031_while_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0030_cond.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0030_cond.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0029_cast_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0029_cast_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0028_impl_trait_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0028_impl_trait_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0027_ref_pat.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0027_ref_pat.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0026_tuple_pat_fields.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0026_tuple_pat_fields.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0025_slice_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0025_slice_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0024_slice_pat.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0024_slice_pat.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0023_placeholder_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0023_placeholder_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0022_crate_visibility.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0022_crate_visibility.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0021_assoc_item_list.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0021_assoc_item_list.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0019_unary_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0019_unary_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0018_arb_self_types.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0018_arb_self_types.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0017_array_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0017_array_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0015_continue_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0015_continue_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0014_never_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0014_never_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0013_pointer_type_mut.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0013_pointer_type_mut.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0012_type_item_where_clause.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0012_type_item_where_clause.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0011_field_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0011_field_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0010_extern_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0010_extern_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0009_loop_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0009_loop_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0008_path_part.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0008_path_part.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0007_type_param_bounds.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0007_type_param_bounds.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0006_self_param.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0006_self_param.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0005_function_type_params.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0005_function_type_params.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0004_value_parameters_no_patterns.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0004_value_parameters_no_patterns.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0003_where_pred_for.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0003_where_pred_for.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0002_use_tree_list.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/ok/0002_use_tree_list.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0015_missing_fn_param_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0015_missing_fn_param_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0015_empty_segment.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0015_empty_segment.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0014_struct_field_recover.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0014_struct_field_recover.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0014_record_literal_before_ellipsis_recovery.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0014_record_literal_before_ellipsis_recovery.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0013_anonymous_static.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0013_anonymous_static.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0010_bad_tuple_index_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0010_bad_tuple_index_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0008_pub_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0008_pub_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0007_async_without_semicolon.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0007_async_without_semicolon.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0006_unsafe_block_in_mod.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0006_unsafe_block_in_mod.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0005_fn_pointer_type_missing_fn.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0005_fn_pointer_type_missing_fn.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0004_impl_type.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0004_impl_type.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0003_pointer_type_no_mutability.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0003_pointer_type_no_mutability.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0002_misplaced_label_err.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0002_misplaced_label_err.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0001_array_type_missing_semi.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/inline/err/0001_array_type_missing_semi.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fuzz-failures/0004.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fuzz-failures/0003.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fuzz-failures/0002.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fuzz-failures/0001.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fuzz-failures/0000.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/type/ok/0000_result.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/type/ok/0000_result.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/type/err/0000_missing_close.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/type/err/0000_missing_close.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_unterminated_let_stmt.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_unterminated_let_stmt.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_unterminated_fn_call.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_unterminated_fn_call.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_struct_item.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_struct_item.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_macro_unterminated_let_stmt.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_macro_unterminated_let_stmt.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_macro_let_stmt.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_macro_let_stmt.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_let_stmt.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_let_stmt.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_fn_call.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_fn_call.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_expr_block.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_expr_block.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/ok/0000_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/err/0000_unterminated_expr.rs
Adding src/tools/rust-analerror: add_cacheinfo failed to refresh for path 'src/tools/rust-analyzer/crates/syntax/test_data/parser/err/0048_repated_extern_modifier.rs'; merge aborting.
yzer/crates/syntax/test_data/parser/fragments/stmt/err/0000_unterminated_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/err/0000_semicolon.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/err/0000_semicolon.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/err/0000_open_parenthesis.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/err/0000_open_parenthesis.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/err/0000_multiple_stmts.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/err/0000_multiple_stmts.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/err/0000_attr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/stmt/err/0000_attr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/pattern/ok/0000_enum.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/pattern/ok/0000_enum.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/pattern/err/0001_missing_paren.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/pattern/err/0001_missing_paren.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/pattern/err/0000_reserved_word.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/pattern/err/0000_reserved_word.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/path/ok/0001_multipart.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/path/ok/0001_multipart.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/path/ok/0000_single_ident.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/path/ok/0000_single_ident.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/path/err/0001_expression.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/path/err/0001_expression.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/path/err/0000_reserved_word.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/path/err/0000_reserved_word.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/item/ok/0000_fn.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/item/ok/0000_fn.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/item/err/0000_extra_keyword.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/item/err/0000_extra_keyword.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/expr/ok/0000_add.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/expr/ok/0000_add.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/expr/err/0000_truncated_add.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/fragments/expr/err/0000_truncated_add.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/err/0049_double_fish.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/err/0049_double_fish.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/err/0048_repated_extern_modifier.rs

