
WARNING: `CARGO_MANIFEST_DIR` env variable not set
Building kernel
   Compiling core v0.0.0 (/home/bjorn/Projects/cg_clif2/build/lib/rustlib/src/rust/library/core)
     Running `/home/bjorn/Projects/cg_clif2/build/bin/cg_clif --crate-name core --edition=2018 /home/bjorn/Projects/cg_clif2/build/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=ee2ad1b2d63ad9c6 -C extra-filename=-ee2ad1b2d63ad9c6 --out-dir /home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps --target /home/bjorn/Documenten/blog_os/x86_64-blog_os.json -Z force-unstable-if-unmarked -L dependency=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps -L dependency=/home/bjorn/Documenten/blog_os/target/debug/deps --cap-lints allow -Ccodegen-units=1`
   Compiling rustc-std-workspace-core v1.99.0 (/home/bjorn/Projects/cg_clif2/build/lib/rustlib/src/rust/library/rustc-std-workspace-core)
     Running `/home/bjorn/Projects/cg_clif2/build/bin/cg_clif --crate-name rustc_std_workspace_core --edition=2018 /home/bjorn/Projects/cg_clif2/build/lib/rustlib/src/rust/library/rustc-std-workspace-core/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=eade2e2614db767f -C extra-filename=-eade2e2614db767f --out-dir /home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps --target /home/bjorn/Documenten/blog_os/x86_64-blog_os.json -Z force-unstable-if-unmarked -L dependency=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps -L dependency=/home/bjorn/Documenten/blog_os/target/debug/deps --extern core=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libcore-ee2ad1b2d63ad9c6.rmeta --cap-lints allow -Ccodegen-units=1`
   Compiling compiler_builtins v0.1.49
     Running `/home/bjorn/Projects/cg_clif2/build/bin/cg_clif --crate-name compiler_builtins /home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.49/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="compiler-builtins"' --cfg 'feature="core"' --cfg 'feature="default"' --cfg 'feature="mem"' --cfg 'feature="rustc-dep-of-std"' -C metadata=e4d6a99e201768d9 -C extra-filename=-e4d6a99e201768d9 --out-dir /home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps --target /home/bjorn/Documenten/blog_os/x86_64-blog_os.json -Z force-unstable-if-unmarked -L dependency=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps -L dependency=/home/bjorn/Documenten/blog_os/target/debug/deps --extern core=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/librustc_std_workspace_core-eade2e2614db767f.rmeta --cap-lints allow -Ccodegen-units=1 --cfg 'feature="unstable"'`
   Compiling spin v0.5.2
   Compiling bootloader v0.9.19
     Running `/home/bjorn/Projects/cg_clif2/build/bin/cg_clif --crate-name spin /home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.5.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=1d1cf7edac185c46 -C extra-filename=-1d1cf7edac185c46 --out-dir /home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps --target /home/bjorn/Documenten/blog_os/x86_64-blog_os.json -L dependency=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps -L dependency=/home/bjorn/Documenten/blog_os/target/debug/deps --extern 'noprelude:compiler_builtins=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libcompiler_builtins-e4d6a99e201768d9.rmeta' --extern 'noprelude:core=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libcore-ee2ad1b2d63ad9c6.rmeta' -Z unstable-options --cap-lints allow -Ccodegen-units=1`
     Running `/home/bjorn/Projects/cg_clif2/build/bin/cg_clif --crate-name bootloader --edition=2018 /home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/bootloader-0.9.19/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=1746666be0e974e4 -C extra-filename=-1746666be0e974e4 --out-dir /home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps --target /home/bjorn/Documenten/blog_os/x86_64-blog_os.json -L dependency=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps -L dependency=/home/bjorn/Documenten/blog_os/target/debug/deps --extern 'noprelude:compiler_builtins=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libcompiler_builtins-e4d6a99e201768d9.rmeta' --extern 'noprelude:core=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libcore-ee2ad1b2d63ad9c6.rmeta' -Z unstable-options --cap-lints allow -Ccodegen-units=1`
   Compiling volatile v0.2.7
     Running `/home/bjorn/Projects/cg_clif2/build/bin/cg_clif --crate-name volatile /home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/volatile-0.2.7/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=98b64e9c368db155 -C extra-filename=-98b64e9c368db155 --out-dir /home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps --target /home/bjorn/Documenten/blog_os/x86_64-blog_os.json -L dependency=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps -L dependency=/home/bjorn/Documenten/blog_os/target/debug/deps --extern 'noprelude:compiler_builtins=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libcompiler_builtins-e4d6a99e201768d9.rmeta' --extern 'noprelude:core=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libcore-ee2ad1b2d63ad9c6.rmeta' -Z unstable-options --cap-lints allow -Ccodegen-units=1`
   Compiling lazy_static v1.4.0
     Running `/home/bjorn/Projects/cg_clif2/build/bin/cg_clif --crate-name lazy_static /home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="spin"' --cfg 'feature="spin_no_std"' -C metadata=1a7b46a88fab49fd -C extra-filename=-1a7b46a88fab49fd --out-dir /home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps --target /home/bjorn/Documenten/blog_os/x86_64-blog_os.json -L dependency=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps -L dependency=/home/bjorn/Documenten/blog_os/target/debug/deps --extern 'noprelude:compiler_builtins=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libcompiler_builtins-e4d6a99e201768d9.rmeta' --extern 'noprelude:core=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libcore-ee2ad1b2d63ad9c6.rmeta' --extern spin=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libspin-1d1cf7edac185c46.rmeta -Z unstable-options --cap-lints allow -Ccodegen-units=1`
   Compiling blog_os v0.1.0 (/home/bjorn/Documenten/blog_os)
     Running `/home/bjorn/Projects/cg_clif2/build/bin/cg_clif --crate-name blog_os --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=8310d2b7a9f27e67 -C extra-filename=-8310d2b7a9f27e67 --out-dir /home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps --target /home/bjorn/Documenten/blog_os/x86_64-blog_os.json -C incremental=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/incremental -L dependency=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps -L dependency=/home/bjorn/Documenten/blog_os/target/debug/deps --extern bootloader=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libbootloader-1746666be0e974e4.rlib --extern 'noprelude:compiler_builtins=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libcompiler_builtins-e4d6a99e201768d9.rlib' --extern 'noprelude:core=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libcore-ee2ad1b2d63ad9c6.rlib' --extern lazy_static=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/liblazy_static-1a7b46a88fab49fd.rlib --extern spin=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libspin-1d1cf7edac185c46.rlib --extern volatile=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libvolatile-98b64e9c368db155.rlib -Z unstable-options -Ccodegen-units=1`
error: internal compiler error: encountered incremental compilation error with exported_symbols(core[96cd])
<snip>
error: could not compile `blog_os` due to previous error

Caused by:
  process didn't exit successfully: `/home/bjorn/Projects/cg_clif2/build/bin/cg_clif --crate-name blog_os --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=8310d2b7a9f27e67 -C extra-filename=-8310d2b7a9f27e67 --out-dir /home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps --target /home/bjorn/Documenten/blog_os/x86_64-blog_os.json -C incremental=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/incremental -L dependency=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps -L dependency=/home/bjorn/Documenten/blog_os/target/debug/deps --extern bootloader=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libbootloader-1746666be0e974e4.rlib --extern 'noprelude:compiler_builtins=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libcompiler_builtins-e4d6a99e201768d9.rlib' --extern 'noprelude:core=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libcore-ee2ad1b2d63ad9c6.rlib' --extern lazy_static=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/liblazy_static-1a7b46a88fab49fd.rlib --extern spin=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libspin-1d1cf7edac185c46.rlib --extern volatile=/home/bjorn/Documenten/blog_os/target/x86_64-blog_os/debug/deps/libvolatile-98b64e9c368db155.rlib -Z unstable-options -Ccodegen-units=1` (exit status: 101)
Error: Kernel build failed.
Stderr:
