plain
    Finished release [optimized] target(s) in 24.62s
Check compiletest suite=ui mode=ui (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 13086 tests
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF....FFFFFFFFFFFFFF.FFFFFFFFFFF.FFFFF.FFFFFFFFFFFF 88/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFiiiFiiiiiiiiiiiFFFFFFF 176/13086
FFFFFFFiFiFFFFFFFFFFFFFFFFFiFFFiFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 264/13086
FFFFFFFFFF.FFFFF.FFFF..F.FFFFFFFFFFFFF..FFFFF.FFF..F...FFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFF 352/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFF...F.FFFFFFFFFFFF 440/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.F.FFFFFFFFF.FFFFFFFFFFFF....FFFFFFFFFFFFFFFFFFFFF.FFFFFF. 528/13086
FFF.FF..FFFFFFFFFFFFFFFFFFFFFFF..FFFFFFFFFF.FFFFFFF.FFFF..FF.FF.FF.FFFFFFFFFFFFFFFFFFFFF 616/13086
FFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FF.FFFFFFFFFF.FFFFFFFFFFFFFFFFFFFF 704/13086
FFFFFFFFFFFF.FFFF..FFFF.FFFFFFFFFFFFFFFFFiFFFFF..FFF.F....FF..FFF..FFFF..FF...FF...F...F 792/13086
.FFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFiFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 880/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.F 968/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 1056/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 1144/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 1232/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFiFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFF 1320/13086
FFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFF.FFFFFFFFFF.FFFFFFFFFFFFFFFFFFFF.F.FFFFFFFiFFFFF 1408/13086
.FFFFFFFFFF.F.FFFF....FFFFFFFFF.FF.F......F...F...F..FFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFF 1496/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 1584/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.. 1672/13086
FFF.FFFFFFFFFF.FFFFFFi.FFF.iiFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 1760/13086
FFFFFFF..FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 1848/13086
FFFFFFFFFFFFF.FFFFFFFFFFFF..FFFFFFFFFFFFFFF.....F....F....F...FF.F.F...F..FFi..FFFFFFFF. 1936/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.F.FFFFFFF.FFFFFFFFFFF.FFFFFFF..FFFFFFFFFFF.F 2024/13086
FFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2112/13086
FFFFFFFF.FFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFF.FFFF 2200/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFF..F.FFFFFFFFFFFFFFFFFFFFFFFFFF 2288/13086
FFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2376/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2464/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2552/13086
FFFF..F.FFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2640/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF. 2728/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2816/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2904/13086
FFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFiFFFFFFFFFFFFFFFFFFFFFFFFFFFF.F.FF.FFF.FFFFFFFFFFFFFFFi 2992/13086
.FF.FFFFFFFFFFFFF.FF...FFFFF..FF.FFFFFFFFFFF.FFFFFFFF.F.FFFFFFFFFFFFFFFF.FF.F.FFFFFFFFFF 3080/13086
FFFFFFFFFFFFFFFFFFFFFF..F.FF..FF..FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFF 3168/13086
FFFFFFFF.FFFFFFFFFFFFFF.FFFFFFFFFFF.FFFFFFFFFF.FFFFiiiiiFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFF 3256/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.F..F.F.FFFFFFFFFFFFFFFFFFFFFFFFFFF 3344/13086
FFFFFF..FF.FFFFFFFFFFFFFFFFF.FFFFF..FFFFFFFFFFFF.FF.FF.FFFFFFFFFFFFFFFFFFFFFF.FFFF.FF.F. 3432/13086
FFFFFFF..FFFFFFFFFFFFFF..FFFFFFFFFFF.FFF.F..F....F....F.FFF...F..F.F.FFFFFFF..FFFFFFFFFF 3520/13086
FF..F.F....F.....FFFFFFFFFFFFFFFFFFF..FF.F.FFFFFFF.FFFFF....FF.FFFFFF.F....F..F.FFFFFFFF 3608/13086
FFFF.F.FFFFFFFFF..F..F..FFFFFF..FFFFFFFFFFFFFFFFFF.F..FF...FFFF.F...FFFFFFFFFFF.F.FFFFFF 3696/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFF..FFFFFFFFiFF..FFFFFFiFFF.FFFFFFi 3784/13086
FFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFF....FFFFFFFFFF..FF.FFFF.FFFFFFFF..F.FFFF.FF.FFFF... 3872/13086
.F.....FF..F.....F.FF.FF.FF..F...FF....FFFFFFF...FF.F.FF..FiF....F....F...F.....F..F.F.F 3960/13086
FFF.FFFFFFFFFFFFFFF..F....F.....F.....F.....FFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFF.FFFFFFFFFF 4048/13086
FFFFFFFFFFFFFFFFiFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.F.FFF.FFFFFFFFFFFFFFFFFFFFFFFF 4136/13086
FFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 4224/13086
FFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFF.FFFFF.FFFF..F.FFFFFFFFF 4312/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFF.FFFFFF.FFFFFFFF.F..FFFFFFFFFFFFFFFFFF 4400/13086
FFFFF.FFFFFFFFFFFFFF.FFFFFFFFFFFF.FFFFFFFFFFFF..F..FF..FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 4488/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFF.FFFFFFFFFFFFFFF 4576/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFF 4664/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FF.FFFFFFFFFFFFFFFFFFF 4752/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFF. 4840/13086
F.FFF.FFF.FFFFFFFF..FFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFF...F...F....F...F..F.FF..F..F... 4928/13086
F..F.FFFFFFF.FF..F...F.....F.F.F...FFF.F.F..FFFFF..F.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 5016/13086
FFFFFFFFFFFFFFFFFFFFFFFFFFiFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.F..F..FF...F..F 5104/13086
...F.i..FFFFFFFFFFFF.F.FFFFFFFF..FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 5192/13086
FF.FFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFF.FFF.FFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 5280/13086
FFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 5368/13086
FFFF.FFFFFFFFFF.FFFFF.FFFFFFFFF.F.FFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFF.FF.FFF.FFFFFFF 5456/13086
FFFFFFFF.F.F.F.FFFFFFFFFFFFFFF.FF.FFFFFFFFF.FFFFFFFFFFFFFFFFF.FFFFFFFFFFFFF.FF.FFFFFFFFF 5544/13086
FFFFFFFFFFFFFFFFF.F.FFFF.FFFFFFF.F.FFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFF.FF. 5632/13086
.FFFFFFFFFFFFFFFFFFFFFF..FFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFF 5720/13086
src/ci/docker/run.sh: line 260:  4156 Killed                  docker run --workdir /checkout/obj --env SRC=/checkout $args --env CARGO_HOME=/cargo --env DEPLOY --env DEPLOY_ALT --env CI --env TF_BUILD --env BUILD_SOURCEBRANCHNAME --env GITHUB_ACTIONS --env GITHUB_REF --env TOOLSTATE_REPO_ACCESS_TOKEN --env TOOLSTATE_REPO --env TOOLSTATE_PUBLISH --env RUST_CI_OVERRIDE_RELEASE_CHANNEL --env CI_JOB_NAME="${CI_JOB_NAME-$IMAGE}" --env BASE_COMMIT="$BASE_COMMIT" --init --rm rust-ci $command
##[error]Process completed with exit code 137.
Post job cleanup.
