plain
tests/fail\validity\uninit_integer.rs  ... ok
tests/fail\panic\double_panic.rs  ... ok

tests/fail\dangling_pointers\null_pointer_write_zst.rs FAILED:
command: "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools-bin\\miri.exe" "--edition" "2018" "-Astable-features" "-Aunused" "--sysroot" "C:\\Users\\runneradmin\\AppData\\Local\\rust-lang\\miri\\cache\\HOST" "-Zui-testing" "--extern" "getrandom_1=D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libgetrandom-dd672771ea44d4c7.rmeta" "--extern" "getrandom_2=D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libgetrandom-c9fcdfa62039a643.rmeta" "--extern" "libc=D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\liblibc-b6f84c0e091211d7.rmeta" "--extern" "page_size=D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libpage_size-0be2a45ec4076b31.rmeta" "--extern" "rand=D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\librand-02cf28822a5c7bea.rmeta" "--extern" "tokio=D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libtokio-08c5e516ddaa9497.rmeta" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\parking_lot_core-01e7881ae074c3ba" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\quote-95e478362eaa6fee" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\syn-8e3120bbe689f21a" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\winapi-fb9a27d8a2795a7c" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\proc-macro2-ef0760c3857c99a0" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\deps" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\getrandom-485958166e79d74d" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\log-cb8d4d693bac362b" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\lock_api-bfb3ddc59de1f123" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\libc-5b9c17ff5946bc74" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\windows_x86_64_msvc-ba0f4f4584401c9c" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\memchr-1e9e295b52ef8ba4" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug" "tests/fail\\dangling_pointers\\null_pointer_write_zst.rs" "--error-format=json" "-Zmir-opt-level=0"
actual output differed from expected tests/fail\dangling_pointers\null_pointer_write_zst.stderr
Diff < left / right > :
 error: Undefined Behavior: memory access failed: null pointer is a dangling pointer (it has no provenance)
<  --> RUSTLIB/core/src/ptr/mod.rs:LL:CC
---



tests/fail\intrinsics\write_bytes_overflow.rs FAILED:
command: "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools-bin\\miri.exe" "--edition" "2018" "-Astable-features" "-Aunused" "--sysroot" "C:\\Users\\runneradmin\\AppData\\Local\\rust-lang\\miri\\cache\\HOST" "-Zui-testing" "--extern" "getrandom_1=D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libgetrandom-dd672771ea44d4c7.rmeta" "--extern" "getrandom_2=D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libgetrandom-c9fcdfa62039a643.rmeta" "--extern" "libc=D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\liblibc-b6f84c0e091211d7.rmeta" "--extern" "page_size=D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libpage_size-0be2a45ec4076b31.rmeta" "--extern" "rand=D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\librand-02cf28822a5c7bea.rmeta" "--extern" "tokio=D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps\\libtokio-08c5e516ddaa9497.rmeta" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\parking_lot_core-01e7881ae074c3ba" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug\\deps" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\quote-95e478362eaa6fee" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\syn-8e3120bbe689f21a" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\winapi-fb9a27d8a2795a7c" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\proc-macro2-ef0760c3857c99a0" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\deps" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\getrandom-485958166e79d74d" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\log-cb8d4d693bac362b" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\lock_api-bfb3ddc59de1f123" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\libc-5b9c17ff5946bc74" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\windows_x86_64_msvc-ba0f4f4584401c9c" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\debug\\build\\memchr-1e9e295b52ef8ba4" "-L" "D:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage2-tools\\miri\\x86_64-pc-windows-msvc\\debug" "tests/fail\\intrinsics\\write_bytes_overflow.rs" "--error-format=json"
actual output differed from expected tests/fail\intrinsics\write_bytes_overflow.stderr
Diff < left / right > :
 error: Undefined Behavior: overflow computing total size of `write_bytes`
<  --> RUSTLIB/core/src/intrinsics.rs:LL:CC
---
Verifying status of rls...
Verifying status of miri...
Verifying status of embedded-book...
Cloning into 'rust-toolstate'...
fatal: unable to access 'https://github.com/rust-lang-nursery/rust-toolstate/': Could not resolve host: github.com
thread 'main' panicked at 'git clone unsuccessful (status: Ok(ExitStatus(ExitStatus(128))))', toolstate.rs:325:9
Build completed unsuccessfully in 0:00:12
