plain

failures:

---- test_frequency::prop_frequency_indexed stdout ----
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-43]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-43]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-84]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-84]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-113]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-113]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-142]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-142]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-169]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-169]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-194]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-194]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-233]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-233]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-266]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-266]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-304]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-304]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-336]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-336]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-367]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-367]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-402]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-402]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-433]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-433]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-461]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-461]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-490]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-490]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-519]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-519]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-548]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-548]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-583]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-583]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-617]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-617]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-656]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-656]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-683]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-683]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-710]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-710]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-742]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-742]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-772]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-772]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-802]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-802]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-826]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-826]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-849]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-849]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-877]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-877]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-909]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-909]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-943]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-943]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-971]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-971]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-999]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-999]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1027]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1027]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1053]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1053]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1079]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1079]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1109]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1109]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1149]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1149]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1177]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1177]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
thread 'test_frequency::prop_frequency_indexed' panicked at 'assertion failed: `(left == right)`
  left: `[("!", 1), ("%", 1), ("(NULL)", 47), ("*", 1), ("-", 1), ("/", 1), ("2", 1), ("5", 1), (":", 1), (";", 1), ("@", 1), ("F", 1), ("J", 1), ("U", 1), ("X", 1), ("]", 1), ("p", 1), ("s", 1), ("{", 1), ("~", 2), ("\u{82}", 1), ("\u{87}", 1), ("\u{89}", 1), ("\u{8e}", 1), ("\u{96}", 1), ("\u{202b}", 2), ("‱", 1), ("\u{206d}", 1), ("䠔", 1), ("吪", 1), ("胐", 1), ("並", 1), ("\u{6afbe}", 1), ("\u{e0020}", 1), ("\u{f0000}", 1)]`,
 right: `[("!", 1), ("%", 1), ("(NULL)", 47), ("*", 1), ("-", 1), ("/", 1), ("2", 1), ("5", 1), (":", 1), (";", 1), ("@", 1), ("F", 1), ("J", 1), ("U", 1), ("X", 1), ("]", 1), ("p", 1), ("s", 1), ("{", 1), ("~", 2), ("\u{82}", 1), ("\u{87}", 1), ("\u{89}", 1), ("\u{8e}", 1), ("\u{96}", 1), ("\u{202b}", 1), ("‱", 1), ("\u{206d}", 1), ("䠔", 1), ("吪", 1), ("胐", 1), ("並", 1), ("\u{feff}", 1), ("\u{6afbe}", 1), ("\u{e0020}", 1), ("\u{f0000}", 1)]`', tests/test_frequency.rs:256:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1229]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1229]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1249]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1249]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1277]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1277]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1304]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1304]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1328]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1328]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1356]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1356]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1385]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1385]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
thread 'test_frequency::prop_frequency_indexed' panicked at 'assertion failed: `(left == right)`
  left: `[("(NULL)", 36), ("/", 1), ("2", 1), ("5", 1), (":", 1), ("@", 1), ("F", 1), ("U", 1), ("]", 1), ("p", 1), ("s", 1), ("{", 1), ("~", 2), ("\u{82}", 1), ("\u{87}", 1), ("\u{89}", 1), ("\u{96}", 1), ("‱", 1), ("\u{206d}", 1), ("䠔", 1), ("吪", 1), ("胐", 1), ("並", 1), ("\u{e0020}", 1), ("\u{f0000}", 1)]`,
 right: `[("(NULL)", 36), ("/", 1), ("2", 1), ("5", 1), (":", 1), ("@", 1), ("F", 1), ("U", 1), ("]", 1), ("p", 1), ("s", 1), ("{", 1), ("~", 2), ("\u{82}", 1), ("\u{87}", 1), ("\u{89}", 1), ("\u{96}", 1), ("‱", 1), ("\u{206d}", 1), ("䠔", 1), ("吪", 1), ("胐", 1), ("並", 1), ("\u{feff}", 1), ("\u{e0020}", 1), ("\u{f0000}", 1)]`', tests/test_frequency.rs:256:9
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1409]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1409]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1423]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1423]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1451]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1451]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1476]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1476]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1497]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1497]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1521]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1521]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1542]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1542]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1562]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1562]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1586]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1586]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1609]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1609]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1631]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1631]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1656]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1656]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1680]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1680]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1704]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1704]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1720]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1720]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1737]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1737]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1743]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1743]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1747]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1747]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1751]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1751]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1754]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1754]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1759]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1759]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1762]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1762]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1765]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1765]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1768]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1768]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1773]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1773]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1776]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1776]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1779]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1779]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1782]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1782]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1784]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1784]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1785]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1785]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1786]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1786]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1787]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1787]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1788]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1788]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1789]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1789]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1790]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1790]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1791]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1791]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1792]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1792]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1793]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1793]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1794]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1794]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1795]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1795]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1796]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1796]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1797]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1797]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1798]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1798]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1799]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1799]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1800]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1800]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1801]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1801]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1802]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1802]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1803]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1803]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1804]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1804]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1805]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1805]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1806]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1806]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1807]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1807]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1808]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1808]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1809]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1809]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1810]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1810]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1811]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1811]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1812]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1812]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1813]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1813]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1814]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1814]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1815]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1815]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1816]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1816]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1817]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1817]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1818]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1818]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1819]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1819]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1820]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1820]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1821]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1821]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1822]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1822]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1823]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1823]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1824]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1824]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1825]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1825]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1826]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1826]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1827]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1827]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1828]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1828]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1829]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1829]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1830]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1830]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1831]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1831]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1832]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1832]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1833]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1833]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1834]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1834]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1835]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
error: test failed, to rerun pass '--test tests'
thread 'main' panicked at 'tests failed for https://github.com/BurntSushi/xsv', src/tools/cargotest/main.rs:101:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [check-aux] Error 1
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1835]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1836]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1836]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1837]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1837]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1838]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1838]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1839]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1839]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1840]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1840]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1841]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1841]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1842]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1842]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1843]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1843]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1844]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1844]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1845]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1845]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1846]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1846]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1847]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1847]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1848]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1848]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1849]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1849]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1850]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1850]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1851]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1851]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1852]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1852]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1853]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1853]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1854]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1854]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1855]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1855]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
thread 'test_frequency::prop_frequency_indexed' panicked at 'assertion failed: `(left == right)`
  left: `[("(NULL)", 35), ("/", 1), ("2", 1), ("5", 1), (":", 1), ("@", 1), ("F", 1), ("U", 1), ("]", 1), ("p", 1), ("s", 1), ("{", 1), ("~", 2), ("\u{82}", 1), ("\u{87}", 1), ("\u{89}", 1), ("\u{96}", 1), ("‱", 1), ("\u{206d}", 1), ("䠔", 1), ("吪", 1), ("胐", 1), ("並", 1), ("\u{e0020}", 1), ("\u{f0000}", 1)]`,
 right: `[("(NULL)", 35), ("/", 1), ("2", 1), ("5", 1), (":", 1), ("@", 1), ("F", 1), ("U", 1), ("]", 1), ("p", 1), ("s", 1), ("{", 1), ("~", 2), ("\u{82}", 1), ("\u{87}", 1), ("\u{89}", 1), ("\u{96}", 1), ("‱", 1), ("\u{206d}", 1), ("䠔", 1), ("吪", 1), ("胐", 1), ("並", 1), ("\u{feff}", 1), ("\u{e0020}", 1), ("\u{f0000}", 1)]`', tests/test_frequency.rs:256:9
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1856]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1856]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1857]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1857]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1858]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1858]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1859]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1859]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1860]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1860]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1861]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1861]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1862]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1862]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1863]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1863]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1864]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1864]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1865]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1865]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1866]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1866]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1867]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1867]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1868]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1868]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1869]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1869]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1870]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1870]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1871]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1871]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1872]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1872]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1873]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1873]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1874]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1874]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1875]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1875]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1876]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1876]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1877]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1877]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1878]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1878]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1879]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1879]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1880]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1880]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1881]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1881]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1882]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1882]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1883]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1883]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1884]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1884]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1885]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1885]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1886]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1886]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1887]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1887]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1888]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1888]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1889]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1889]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1890]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1890]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1891]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1891]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1892]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1892]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1893]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1893]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1894]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1894]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1895]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1895]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1896]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1896]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1897]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1897]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1898]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1898]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1899]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1899]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1900]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1900]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1901]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1901]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1902]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1902]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1903]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1903]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1904]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1904]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1905]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1905]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1906]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1906]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1907]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1907]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1908]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1908]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1909]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1909]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1910]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1910]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1911]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1911]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1912]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1912]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1913]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1913]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1914]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1914]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1915]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1915]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1916]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1916]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1917]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1917]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1918]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1918]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1919]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1919]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1920]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1920]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1921]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1921]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1922]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1922]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1923]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1923]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1924]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1924]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1925]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1925]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1926]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1926]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1927]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1927]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1928]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1928]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1929]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1929]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1930]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1930]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1931]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1931]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1932]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1932]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1933]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1933]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1934]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1934]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1935]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1935]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1936]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1936]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1937]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1937]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1938]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1938]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1939]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1939]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1940]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1940]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1941]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1941]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1942]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1942]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1943]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1943]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1944]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1944]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1945]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1945]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1946]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1946]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1947]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1947]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1948]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1948]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1949]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1949]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1950]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1950]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1951]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "index" "in.csv"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_frequency_indxed/test-1951]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "frequency" "in.csv" "-j" "4" "--limit" "0"
