plain
   Compiling lsp-server v0.6.0 (/checkout/src/tools/rust-analyzer/lib/lsp-server)
   Compiling flycheck v0.0.0 (/checkout/src/tools/rust-analyzer/crates/flycheck)
   Compiling base-db v0.0.0 (/checkout/src/tools/rust-analyzer/crates/base-db)
   Compiling flate2 v1.0.24
   Compiling sourcegen v0.0.0 (/checkout/src/tools/rust-analyzer/crates/sourcegen)
   Compiling hir-expand v0.0.0 (/checkout/src/tools/rust-analyzer/crates/hir-expand)
   Compiling hir-def v0.0.0 (/checkout/src/tools/rust-analyzer/crates/hir-def)
   Compiling cfg v0.0.0 (/checkout/src/tools/rust-analyzer/crates/cfg)
   Compiling hir-ty v0.0.0 (/checkout/src/tools/rust-analyzer/crates/hir-ty)
   Compiling hir-ty v0.0.0 (/checkout/src/tools/rust-analyzer/crates/hir-ty)
   Compiling hir v0.0.0 (/checkout/src/tools/rust-analyzer/crates/hir)
   Compiling ide-completion v0.0.0 (/checkout/src/tools/rust-analyzer/crates/ide-completion)
   Compiling ide-ssr v0.0.0 (/checkout/src/tools/rust-analyzer/crates/ide-ssr)
   Compiling ide v0.0.0 (/checkout/src/tools/rust-analyzer/crates/ide)
   Compiling ide-db v0.0.0 (/checkout/src/tools/rust-analyzer/crates/ide-db)
   Compiling ide-assists v0.0.0 (/checkout/src/tools/rust-analyzer/crates/ide-assists)
   Compiling xtask v0.1.0 (/checkout/src/tools/rust-analyzer/xtask)
   Compiling ide-diagnostics v0.0.0 (/checkout/src/tools/rust-analyzer/crates/ide-diagnostics)
   Compiling parser v0.0.0 (/checkout/src/tools/rust-analyzer/crates/parser)
   Compiling rust-analyzer v0.0.0 (/checkout/src/tools/rust-analyzer/crates/rust-analyzer)
   Compiling cargo-platform v0.1.2
---
test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 10 tests
test tests::demorgan ... ok
test tests::hints_impossible ... ok
test tests::distribute ... ok
test tests::nested ... ok
test tests::smoke ... ok
test tests::smoke ... ok
test tests::regression ... ok
test tests::test_cfg_expr_parser ... ok
test tests::why_inactive ... ok
test tests::proptest ... ok
test result: ok. 10 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/flycheck-5783c4927cf6e636)
     Running unittests src/lib.rs (build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/hir-673729ea76e3f8fb)
     Running unittests src/lib.rs (build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/hir-673729ea76e3f8fb)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 1 test
test db::hir_database_is_object_safe ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/hir_def-78010cec22e57c13)


running 332 tests
test body::scope::tests::test_match ... ok
test body::scope::tests::broken_inner_item ... ok
test body::scope::tests::test_call_scope ... ok
test body::scope::tests::test_bindings_after_at ... ok
test body::scope::tests::test_lambda_scope ... ok
test body::scope::tests::ref_patterns_contribute_bindings ... ok
test body::scope::tests::test_resolve_local_name_shadow ... ok
test body::scope::tests::test_loop_scope ... ok
test body::scope::tests::match_guard_if_let ... ok
test body::scope::tests::test_method_call_scope ... ok
test body::scope::tests::test_resolve_local_name ... ok
test body::tests::block::inner_item_smoke ... ok
test body::tests::block::is_visible_from_same_def_map ... ok
test body::tests::block::merge_namespaces ... ok
test body::tests::block::legacy_macro_items ... ok
test body::scope::tests::test_resolve_local_name_declaration ... ok
test body::tests::block::nested_blocks ... ok
test body::tests::block::nested_module_scoping ... ok
test body::scope::tests::macro_inner_item ... ok
test body::scope::tests::test_shadow_variable ... ok
test body::scope::tests::let_chains_can_reference_previous_lets ... ok
test body::tests::block::stmt_macro_expansion_with_trailing_expr ... ok
test body::tests::block::super_does_not_resolve_to_block_module ... ok
test body::tests::block::nested_macro_item_decl ... ok
test body::tests::block::macro_resolve_legacy ... ok
test body::scope::tests::while_let_adds_binding ... ok
test body::tests::block::macro_resolve ... ok
test body::tests::block::super_imports ... ok
test body::tests::block::underscore_import ... ok
test body::tests::block::use_from_crate ... ok
test body::tests::macro_resolve ... ok
test body::tests::recursion_limit ... ok
test find_path::tests::enum_variant ... ok
test find_path::tests::builtins_are_in_scope ... ok
test find_path::tests::discount_private_imports ... ok
---
test find_path::tests::sub_module ... ok
test find_path::tests::self_module ... ok
test find_path::tests::same_crate_reexport_rename ... ok
test find_path::tests::shortest_path ... ok
test find_path::tests::super_module ... ok
test import_map::tests::fuzzy_import_trait_and_assoc_items ... ok
test import_map::tests::cyclic_module_reexport ... ok
test body::tests::your_stack_belongs_to_me ... ok
test import_map::tests::macro_reexport ... ok
test body::tests::issue_3642_bad_macro_stackover ... ok
test import_map::tests::module_reexport ... ok
test import_map::tests::name_only ... ok
test import_map::tests::assoc_items_filtering ... ok
test find_path::tests::different_crate_reexport ... ok
test find_path::tests::different_crate ... ok
test find_path::tests::different_crate_renamed ... ok
test import_map::tests::search_limit ... ok
test import_map::tests::search_limit ... ok
test import_map::tests::namespacing ... ok
test item_tree::tests::macros ... ok
test item_tree::tests::extern_blocks ... ok
test item_tree::tests::adts ... ok
test item_tree::tests::imports ... ok
test item_tree::tests::misc ... ok
test item_tree::tests::mod_paths ... ok
test import_map::tests::search_casing ... ok
---
test import_map::tests::search_exclusions ... ok
test import_map::tests::smoke ... ok
test macro_expansion_tests::builtin_fn_macro::test_compile_error_expand ... ok
test macro_expansion_tests::builtin_derive_macro::test_clone_expand ... ok
test item_tree::tests::generics ... ok
test macro_expansion_tests::builtin_fn_macro::test_column_expand ... ok
test macro_expansion_tests::builtin_fn_macro::test_concat_bytes_expand ... ok
test macro_expansion_tests::builtin_derive_macro::test_copy_expand_simple ... ok
test macro_expansion_tests::builtin_fn_macro::test_concat_expand ... ok
test macro_expansion_tests::builtin_fn_macro::test_env_expand ... ok
test macro_expansion_tests::builtin_fn_macro::test_file_expand ... ok
test macro_expansion_tests::builtin_derive_macro::test_copy_expand_with_type_params ... ok
test macro_expansion_tests::builtin_fn_macro::test_concat_with_captured_expr ... ok
test import_map::tests::type_reexport_cross_crate ... ok
test macro_expansion_tests::builtin_fn_macro::test_format_args_expand ... ok
test macro_expansion_tests::builtin_fn_macro::test_line_expand ... ok
test macro_expansion_tests::builtin_fn_macro::test_format_args_expand_with_broken_member_access ... ok
test macro_expansion_tests::builtin_fn_macro::test_format_args_expand_with_comma_exprs ... ok
test macro_expansion_tests::builtin_fn_macro::test_include_bytes_expand ... ok
test macro_expansion_tests::builtin_fn_macro::test_option_env_expand ... ok
test macro_expansion_tests::builtin_derive_macro::test_copy_expand_with_lifetimes ... ok
test macro_expansion_tests::mbe::expr_interpolation ... ok
test macro_expansion_tests::builtin_fn_macro::test_stringify_expand ... ok
test find_path::tests::prefer_shorter_paths_if_not_alloc ... ok
test macro_expansion_tests::mbe::match_by_ident ... ok
test macro_expansion_tests::mbe::match_by_last_token_literally ... ok
test macro_expansion_tests::mbe::matching::range_patterns ... ok
test macro_expansion_tests::mbe::matching::test_empty_comments ... ok
test macro_expansion_tests::mbe::matching::trailing_vis ... ok
test macro_expansion_tests::mbe::matching::stmt_boundaries ... ok
test find_path::tests::prefer_alloc_paths_over_std ... ok
test macro_expansion_tests::mbe::mbe_are_not_attributes ... ok
test macro_expansion_tests::mbe::matching::asi ... ok
test macro_expansion_tests::mbe::matching::test_expand_bad_literal ... ok
test find_path::tests::prefer_std_paths_over_alloc ... ok
test macro_expansion_tests::builtin_fn_macro::test_concat_idents_expand ... ok
test macro_expansion_tests::mbe::matching::unary_minus_is_a_literal ... ok
test macro_expansion_tests::mbe::match_by_separator_token ... ok
test macro_expansion_tests::mbe::mbe_smoke_test ... ok
test macro_expansion_tests::mbe::meta_syntax::malformed_macro_rules ... ok
test macro_expansion_tests::mbe::regression::test_generate_pattern_iterators ... ok
test macro_expansion_tests::mbe::meta_syntax::test_rustc_issue_57597 ... ok
test find_path::tests::partially_imported ... ok
test macro_expansion_tests::mbe::regression::test_impl_nonzero_fmt ... ok
test macro_expansion_tests::mbe::regression::test_empty_repeat_vars_in_empty_repeat_vars ... ok
test macro_expansion_tests::mbe::regression::test_cfg_if_main ... ok
test macro_expansion_tests::mbe::regression::test_issue_2520 ... ok
test macro_expansion_tests::mbe::regression::test_cfg_if_items ... ok
test macro_expansion_tests::mbe::regression::test_no_space_after_semi_colon ... ok
test macro_expansion_tests::mbe::regression::test_issue_3861 ... ok
test macro_expansion_tests::mbe::regression::test_repeat_bad_var ... ok
test macro_expansion_tests::mbe::regression::test_old_ridl ... ok
test macro_expansion_tests::mbe::regression::test_proptest_arbitrary ... ok
test macro_expansion_tests::mbe::regression::test_int_base ... ok
test macro_expansion_tests::mbe::regression::test_impl_fn_for_zst ... ok
test macro_expansion_tests::mbe::test_dollar_crate_lhs_is_not_meta ... ok
test macro_expansion_tests::mbe::test_boolean_is_ident ... ok
test macro_expansion_tests::mbe::test_expand_to_item_list ... ok
test macro_expansion_tests::mbe::test_expr_after_path_colons ... ok
test macro_expansion_tests::mbe::test_expr ... ok
test macro_expansion_tests::mbe::test_expr_order ... ok
test macro_expansion_tests::mbe::regression::test_winapi_struct ... ok
test macro_expansion_tests::mbe::test_dollar_dollar ... ok
test macro_expansion_tests::mbe::test_block ... ok
test import_map::tests::search_mode ... ok
test macro_expansion_tests::mbe::test_expr_with_attr ... ok
test macro_expansion_tests::mbe::test_all_items ... ok
test macro_expansion_tests::mbe::test_inner_macro_rules ... ok
test macro_expansion_tests::mbe::test_lifetime ... ok
test macro_expansion_tests::mbe::test_last_expr ... ok
test macro_expansion_tests::mbe::test_macro_2_0_panic_2015 ... ok
test macro_expansion_tests::mbe::test_literal ... ok
test macro_expansion_tests::mbe::test_match_group_in_group ... ok
test macro_expansion_tests::mbe::test_match_group_pattern_with_multiple_defs ... ok
test macro_expansion_tests::mbe::test_match_group_pattern_with_multiple_statement ... ok
test macro_expansion_tests::mbe::test_match_group_pattern_with_multiple_statement_without_semi ... ok
test macro_expansion_tests::mbe::test_match_group_zero_match ... ok
test macro_expansion_tests::mbe::test_match_group_empty_fixed_token ... ok
test macro_expansion_tests::mbe::test_match_literal ... ok
test macro_expansion_tests::mbe::test_match_group_with_multichar_sep ... ok
test macro_expansion_tests::mbe::test_match_is_not_greedy ... ok
test macro_expansion_tests::mbe::test_meta ... ok
test macro_expansion_tests::mbe::test_match_group_in_subtree ... ok
test macro_expansion_tests::mbe::test_meta_doc_comments ... ok
test macro_expansion_tests::mbe::test_meta_doc_comments_escaped_characters ... ok
test macro_expansion_tests::mbe::test_meta_extended_key_value_attributes ... ok
test macro_expansion_tests::mbe::test_parse_macro_def_rules ... ok
test macro_expansion_tests::mbe::test_meta_doc_comments_non_latin ... ok
test macro_expansion_tests::mbe::test_metavar_exprs ... ok
test macro_expansion_tests::mbe::test_single_item ... ok
test macro_expansion_tests::mbe::test_tt_composite2 ... ok
test macro_expansion_tests::mbe::test_path_with_path ... ok
test macro_expansion_tests::mbe::test_path ... ok
test macro_expansion_tests::mbe::test_parse_macro_def_simple ... ok
test macro_expansion_tests::mbe::test_tt_composite ... ok
test macro_expansion_tests::mbe::test_tt_to_stmts ... ok
test macro_expansion_tests::mbe::test_tt_block ... ok
test macro_expansion_tests::mbe::test_stmt ... ok
test macro_expansion_tests::mbe::test_tt_with_composite_without_space ... ok
test macro_expansion_tests::mbe::test_pat_ ... ok
test macro_expansion_tests::mbe::test_tt_group ... ok
test macro_expansion_tests::mbe::test_two_idents ... ok
test macro_expansion_tests::mbe::test_ty ... ok
test macro_expansion_tests::mbe::test_two_paths ... ok
test macro_expansion_tests::mbe::test_ty_with_complex_type ... ok
test macro_expansion_tests::mbe::tt_conversion::broken_parenthesis_sequence ... ok
test macro_expansion_tests::mbe::token_mapping_smoke_test ... ok
test macro_expansion_tests::mbe::test_underscore_flavors ... ok
test macro_expansion_tests::mbe::tt_conversion::broken_pat ... ok
test macro_expansion_tests::mbe::test_underscore ... ok
test macro_expansion_tests::mbe::token_mapping_floats ... ok
test macro_expansion_tests::mbe::test_vis ... ok
test macro_expansion_tests::mbe::test_vertical_bar_with_pat ... ok
test macro_expansion_tests::mbe::tt_conversion::float_literal_in_output ... ok
test macro_expansion_tests::mbe::tt_conversion::float_literal_in_tt ... ok
test macro_expansion_tests::mbe::tt_conversion::round_trips_compound_tokens ... ok
test macro_expansion_tests::mbe::tt_conversion::roundtrip_lifetime ... ok
test nameres::collector::tests::test_macro_expand_will_stop_2 ... ignored
test macro_expansion_tests::mbe::tt_conversion::round_trips_literals ... ok
test macro_expansion_tests::proc_macros::attribute_macro_syntax_completion_1 ... ok
test nameres::tests::bogus_paths ... ok
test macro_expansion_tests::mbe::tt_conversion::expansion_does_not_parse_as_expression ... ok
test macro_expansion_tests::mbe::wrong_nesting_level ... ok
test macro_expansion_tests::proc_macros::attribute_macro_attr_censoring ... ok
test macro_expansion_tests::proc_macros::attribute_macro_syntax_completion_2 ... ok
test nameres::tests::braced_supers_in_use_tree ... ok
test nameres::tests::can_import_enum_variant ... ok
test nameres::tests::cfg_the_entire_crate ... ok
test nameres::tests::cfg_test ... ok
test nameres::tests::crate_def_map_super_super ... ok
test nameres::tests::edition_2015_imports ... ok
test nameres::tests::crate_def_map_fn_mod_same_name ... ok
test macro_expansion_tests::proc_macros::float_parsing_panic ... ok
test macro_expansion_tests::proc_macros::derive_censoring ... ok
test nameres::tests::edition_specific_preludes ... ok
test nameres::tests::extern_crate_rename ... ok
test nameres::tests::extern_crate_rename_2015_edition ... ok
test nameres::tests::globs::glob_across_crates ... ok
test nameres::tests::cfg_not_test ... ok
test find_path::tests::prefer_core_paths_over_std ... ok
test nameres::tests::crate_def_map_smoke_test ... ok
test nameres::tests::globs::glob_1 ... ok
test nameres::tests::globs::glob_2 ... ok
test nameres::tests::globs::glob_privacy_across_crates ... ok
test nameres::tests::globs::glob_shadowed_def ... ok
test nameres::tests::globs::glob_shadowed_def_dependencies ... ok
test macro_expansion_tests::mbe::regression::test_vec ... ok
test nameres::tests::globs::glob_shadowed_def_reversed ... ok
test nameres::tests::globs::glob_privacy_1 ... ok
test nameres::tests::globs::glob_enum_group ... ok
test nameres::tests::import_from_extern_crate_only_imports_public_items ... ok
test nameres::tests::globs::glob_privacy_2 ... ok
test macro_expansion_tests::mbe::test_underscore_not_greedily ... ok
test nameres::tests::macro_use_extern_crate_self ... ok
test macro_expansion_tests::mbe::match_by_first_token_literally ... ok
test nameres::tests::infer_multiple_namespace ... ok
test nameres::tests::incremental::item_tree_prevents_reparsing ... ok
test nameres::tests::item_map_across_crates ... ok
test nameres::tests::globs::glob_enum ... ok
test nameres::tests::item_map_using_self ... ok
test nameres::tests::macros::collects_derive_helpers ... ok
test nameres::tests::incremental::typing_inside_a_function_should_not_invalidate_expansions ... ok
test nameres::tests::incremental::typing_inside_a_function_should_not_invalidate_def_map ... ok
test nameres::tests::macros::builtin_derive_with_unresolved_attributes_fall_back ... ok
test nameres::tests::incremental::typing_inside_a_macro_should_not_invalidate_def_map ... ok
test nameres::tests::macros::eager_macro_correctly_resolves_contents ... ok
test nameres::tests::macros::issue9358_bad_macro_stack_overflow ... ok
test nameres::tests::macros::legacy_macro_use_before_def ... ok
test macro_expansion_tests::mbe::meta_syntax::well_formed_macro_rules ... ok
test nameres::tests::macros::eager_macro_correctly_resolves_dollar_crate ... ok
test nameres::tests::macros::expand_derive ... ok
test nameres::tests::macros::macro_dollar_crate_is_correct_in_indirect_deps ... ok
test nameres::tests::macros::macro_in_prelude ... ok
test nameres::tests::macros::local_inner_macros_makes_local_macros_usable ... ok
test nameres::tests::macros::macro_rules_are_globally_visible ... ok
test nameres::tests::macros::macro_rules_from_other_crates_are_visible ... ok
test nameres::tests::macros::macros_in_extern_block ... ok
test nameres::tests::macros::macro_use_imports_all_macro_types ... ok
test nameres::tests::macros::macro_use_can_be_aliased ... ok
test nameres::tests::macros::macro_rules_export_with_local_inner_macros_are_visible ... ok
test nameres::tests::macros::macro_dollar_crate_is_correct_in_item ... ok
test nameres::tests::macros::macro_rules_from_other_crates_are_visible_with_macro_use ... ok
test nameres::tests::macros::macro_rules_can_define_modules ... ok
test nameres::tests::macros::prelude_cycle ... ok
test nameres::tests::macros::path_qualified_macros ... ok
test nameres::tests::macros::resolve_builtin_derive ... ok
test nameres::tests::macros::resolve_macro_def ... ok
test nameres::tests::macros::proc_macro_censoring ... ok
test nameres::tests::macros::macros_defining_macros ... ok
test nameres::tests::macros::prelude_is_macro_use ... ok
test nameres::tests::macros::unresolved_attr_with_cfg_attr_hang ... ok
test nameres::tests::macros::resolves_proc_macros ... ok
test nameres::tests::macros::type_value_macro_live_in_different_scopes ... ok
test nameres::tests::macros::resolves_derive_helper ... ok
test nameres::tests::macros::unresolved_attributes_fall_back_track_per_file_moditems ... ok
test nameres::tests::macros::unresolved_attrs_extern_block_hang ... ok
test nameres::tests::macros::unexpanded_macro_should_expand_by_fixedpoint_loop ... ok
test nameres::tests::mod_resolution::abs_path_ignores_local ... ok
test nameres::tests::mod_resolution::cfg_in_module_file ... ok
test nameres::tests::mod_resolution::module_resolution_decl_inside_inline_module ... ok
test nameres::tests::macros::plain_macros_are_legacy_textual_scoped ... ok
test nameres::tests::mod_resolution::module_resolution_decl_empty_path ... ok
test nameres::tests::mod_resolution::module_resolution_decl_inside_inline_module_empty_path ... ok
test nameres::tests::mod_resolution::module_resolution_decl_inside_inline_module_2_with_path_attribute ... ok
test nameres::tests::mod_resolution::module_resolution_decl_inside_inline_module_in_non_crate_root ... ok
test nameres::tests::mod_resolution::module_resolution_decl_inside_inline_module_in_crate_root ... ok
test nameres::tests::mod_resolution::module_resolution_decl_inside_module_in_non_crate_root_2 ... ok
test nameres::tests::mod_resolution::module_resolution_decl_inside_inline_module_with_path_attribute ... ok
test nameres::tests::mod_resolution::circular_mods ... ok
test nameres::tests::mod_resolution::module_resolution_decl_inside_inline_module_relative_path ... ok
test nameres::tests::mod_resolution::module_resolution_decl_inside_inline_module_in_non_crate_root_2 ... ok
test nameres::tests::mod_resolution::module_resolution_decl_inside_inline_module_3 ... ok
test nameres::tests::mod_resolution::module_resolution_explicit_path_mod_rs_2 ... ok
test nameres::tests::mod_resolution::module_resolution_explicit_path_mod_rs ... ok
test nameres::tests::mod_resolution::module_resolution_explicit_path_mod_rs_with_win_separator ... ok
test nameres::tests::mod_resolution::module_resolution_decl_path ... ok
test nameres::tests::mod_resolution::module_resolution_module_decl_path_super ... ok
test nameres::tests::mod_resolution::module_resolution_module_with_path_non_crate_root ... ok
test nameres::tests::mod_resolution::module_resolution_relative_path_outside_root ... ok
test nameres::tests::mod_resolution::module_resolution_works_for_non_standard_filenames ... ok
test nameres::tests::mod_resolution::module_resolution_relative_path_2 ... ok
test nameres::tests::mod_resolution::name_res_works_for_broken_modules ... ok
test nameres::tests::mod_resolution::module_resolution_works_for_raw_modules ... ok
test nameres::tests::mod_resolution::nested_out_of_line_module ... ok
test nameres::tests::mod_resolution::nested_module_resolution ... ok
test nameres::tests::mod_resolution::nested_module_resolution_2 ... ok
test nameres::tests::mod_resolution::module_resolution_module_with_path_in_mod_rs ... ok
test nameres::tests::mod_resolution::nested_out_of_line_module_with_path ... ok
test nameres::tests::primitives::primitive_reexport ... ok
test nameres::tests::no_std_prelude ... ok
test nameres::tests::mod_resolution::module_resolution_relative_path ... ok
test nameres::tests::reexport_across_crates ... ok
test nameres::tests::non_prelude_deps ... ok
test nameres::tests::self_imports_only_types ... ok
test nameres::tests::underscore_import ... ok
test nameres::tests::underscore_name_conflict ... ok
test nameres::tests::re_exports ... ok
test nameres::tests::underscore_nontrait ... ok
test nameres::tests::std_prelude_takes_precedence_above_core_prelude ... ok
test nameres::tests::underscore_pub_crate_reexport ... ok
test nameres::tests::use_as ... ok
test nameres::tests::use_crate_as ... ok
test nameres::tests::underscore_reexport ... ok
test nameres::tests::std_prelude ... ok
test nameres::tests::values_dont_shadow_extern_crates ... ok
test nameres::tests::use_trees ... ok
test nameres::tests::mod_resolution::module_resolution_decl_inside_inline_module_in_mod_rs ... ok
test nameres::tests::macros::macro_expansion_overflow ... ok
test macro_expansion_tests::mbe::regression::test_quick_error ... ok
test nameres::collector::tests::test_macro_expand_will_stop_1 ... ok
test result: ok. 331 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.18s

     Running unittests src/lib.rs (build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/hir_expand-afa6b307aac5eeb8)


running 16 tests
test fixup::tests::extraneous_comma ... ok
test fixup::tests::fixup_if_3 ... ok
test fixup::tests::field_expr_before_call ... ok
test fixup::tests::fixup_if_1 ... ok
test fixup::tests::fixup_if_2 ... ok
test fixup::tests::incomplete_field_expr_1 ... ok
test fixup::tests::incomplete_field_expr_2 ... ok
test fixup::tests::incomplete_field_expr_3 ... ok
test fixup::tests::incomplete_field_expr_in_let ... ok
test quote::tests::test_quote_delimiters ... ok
test fixup::tests::incomplete_let ... ok
test quote::tests::test_quote_hash_simple_literal ... ok
test quote::tests::test_quote_derive_copy_hack ... ok
test quote::tests::test_quote_hash_token_tree ... ok
test quote::tests::test_quote_idents ... ok
     Running unittests src/lib.rs (build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/hir_ty-d3a9e5396f94c6ef)
test quote::tests::test_quote_simple_derive_copy ... ok
test result: ok. 16 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 506 tests
running 506 tests
test db::hir_database_is_object_safe ... ok
test diagnostics::decl_check::case_conv::tests::test_to_lower_snake_case ... ok
test diagnostics::decl_check::case_conv::tests::test_to_camel_case ... ok
test diagnostics::decl_check::case_conv::tests::test_to_upper_snake_case ... ok
test consteval::tests::locals ... ok
test consteval::tests::locals ... ok
test tests::coercion::block_expr_type_mismatch ... ok
test consteval::tests::const_impl_assoc ... ok
test consteval::tests::consts ... ok
test consteval::tests::const_trait_assoc ... ok
test tests::coercion::closure_return_coerce ... ok
test consteval::tests::const_generic_subst ... ok
test consteval::tests::const_generic_subst ... ok
test consteval::tests::bit_op ... ok
test tests::coercion::coerce_array_elems_lub ... ok
test tests::coercion::coerce_closure_to_fn_ptr ... ok
test tests::coercion::coerce_autoderef ... ok
test tests::coercion::coerce_autoderef_generic ... ok
test tests::coercion::coerce_placeholder_ref ... ok
test tests::coercion::coerce_merge_one_by_one1 ... ok
test tests::coercion::coerce_fn_item_to_fn_ptr ... ok
test tests::coercion::coerce_fn_items_in_match_arms ... ok
test tests::coercion::coerce_autoderef_implication_2 ... ok
test tests::coercion::coerce_autoderef_implication_1 ... ok
test tests::coercion::coerce_autoderef_block ... ok
test tests::coercion::assign_coerce ... ok
test tests::coercion::coerce_overloaded_binary_op_rhs ... ok
test tests::coercion::coerce_unsize_array ... ok
test tests::coercion::destructuring_assign_coerce ... ok
test tests::coercion::assign_coerce_struct_fields ... ok
test tests::coercion::coerce_unsize_apit ... ok
test tests::coercion::coerce_unsize_expected_type_1 ... ok
test tests::coercion::coerce_unsize_super_trait_cycle ... ok
test tests::coercion::coerce_unsize_expected_type_3 ... ok
test tests::coercion::coerce_type_var ... ok
test tests::coercion::coerce_unsize_expected_type_4 ... ok
test tests::coercion::destructuring_assign_coerce_struct_fields ... ok
test tests::coercion::coerce_unsize_generic ... ok
test tests::coercion::return_coerce_unknown ... ok
test tests::coercion::if_coerce ... ok
test tests::coercion::let_stmt_coerce ... ok
test tests::coercion::coerce_unsize_expected_type_2 ... ok
test tests::coercion::two_closures_lub ... ok
test tests::coercion::panic_macro ... ok
test tests::diagnostics::function_return_type_mismatch_3 ... ok
test tests::coercion::if_else_coerce ... ok
test tests::coercion::custom_coerce_unsized ... ok
test tests::diagnostics::function_return_type_mismatch_4 ... ok
test tests::coercion::coerce_places ... ok
test tests::diagnostics::function_return_type_mismatch_5 ... ok
test tests::coercion::match_diverging_branch_2 ... ok
test tests::diagnostics::function_return_type_mismatch_1 ... ok
test tests::coercion::match_diverging_branch_1 ... ok
test tests::coercion::match_first_coerce ... ok
test tests::macros::benchmark_include_macro ... FAILED
test tests::diagnostics::function_return_type_mismatch_2 ... ok
test tests::display_source_code::qualify_path_to_submodule ... ok
test tests::display_source_code::render_dyn_for_ty ... ok
test tests::coercion::coerce_unsize_trait_object_simple ... ok
test tests::incremental::typing_whitespace_inside_a_function_should_not_invalidate_types ... ok
test tests::display_source_code::omit_default_type_parameters ... ok
test tests::macros::cfg_tails ... ok
test tests::display_source_code::render_raw_ptr_impl_ty ... ok
test tests::coercion::match_second_coerce ... ok
test tests::macros::expr_macro_expanded_in_stmts ... ok
test tests::display_source_code::sized_bounds_impl_traits_in_fn_signature ... ok
test tests::display_source_code::sized_bounds_apit ... ok
test tests::display_source_code::sized_bounds_rpit ... ok
test tests::macros::infer_assoc_items_generated_by_macros ... ok
test tests::macros::infer_builtin_macros_env ... ok
test tests::macros::infer_builtin_macros_file ... ok
test tests::macros::infer_builtin_macros_concat ... ok
test tests::macros::infer_builtin_macros_concat_with_lazy ... ok
test tests::display_source_code::parenthesize_ptr_rpit_sized_bounds ... ok
test tests::macros::infer_builtin_macros_include_child_mod ... ok
test tests::macros::infer_builtin_macros_include_expression ... ok
test tests::macros::infer_assoc_items_generated_by_macros_chain ... ok
test tests::macros::infer_builtin_macros_include_str ... ok
test tests::macros::infer_builtin_macros_include_concat ... ok
test tests::macros::infer_builtin_macros_include_itself_should_failed ... ok
test tests::macros::infer_builtin_macros_line ... ok
---
test tests::macros::infer_in_unexpandable_attr_proc_macro_in_trait ... ok
test tests::macros::infer_builtin_macros_column ... ok
test tests::macros::infer_local_macro ... ok
test tests::macros::infer_local_inner_macros ... ok
test tests::macros::expr_macro_rules_expanded_in_various_places ... ok
test tests::macros::infer_builtin_macros_include_concat_with_bad_env_should_failed ... ok
test tests::macros::infer_legacy_textual_scoped_macros_expanded ... ok
test tests::macros::infer_macros_expanded ... ok
test tests::macros::infer_macro_defining_block_with_items ... ok
test tests::macros::infer_macro_with_dollar_crate_in_def_site ... ok
test tests::macros::infer_path_qualified_macros_expanded ... ok
test tests::macros::infer_type_value_non_legacy_macro_use_as ... ok
test tests::macros::macro_in_arm ... ok
test tests::macros::infer_type_value_macro_having_same_name ... ok
test tests::macros::macro_in_type_alias_position ... ok
test tests::macros::macros_in_type_position ... ok
test tests::macros::recursive_inner_item_macro_rules ... ok
test tests::macros::processes_impls_generated_by_macros ... ok
test tests::macros::processes_impls_generated_by_macros ... ok
test tests::macros::recurisve_macro_expanded_in_stmts ... ok
test tests::macros::infer_macro_with_dollar_crate_is_correct_in_expr ... ok
test tests::macros::nested_macro_in_type_alias_position ... ok
test tests::method_resolution::cross_crate_associated_method_call ... ok
test tests::macros::macros_in_type_alias_position_generics ... ok
test tests::method_resolution::cross_crate_primitive_method ... ok
test tests::macros::infer_macro_with_dollar_crate_is_correct_in_trait_associate_type ... ok
test tests::macros::infer_macro_with_dollar_crate_is_correct_in_trait_associate_type ... ok
test tests::macros::macros_in_type_generics ... ok
test tests::method_resolution::infer_array_inherent_impl ... ok
test tests::method_resolution::infer_associated_method_enum ... ok
test tests::method_resolution::autoderef_visibility_field ... ok
test tests::method_resolution::infer_associated_method_generics ... ok
test tests::method_resolution::const_generic_type_alias ... ok
test tests::method_resolution::infer_associated_method_generics_without_args ... ok
test tests::method_resolution::dyn_trait_super_trait_not_in_scope ... ok
test tests::method_resolution::autoderef_visibility_method ... ok
test tests::method_resolution::infer_associated_method_generics_2_type_params_without_args ... ok
test tests::method_resolution::bad_inferred_reference_2 ... ok
test tests::method_resolution::bad_inferred_reference_1 ... ok
test tests::method_resolution::infer_associated_method_with_modules ... ok
test tests::method_resolution::infer_associated_method_with_modules ... ok
test tests::method_resolution::infer_call_trait_method_on_generic_param_2 ... ok
test tests::method_resolution::infer_associated_method_struct ... ok
test tests::method_resolution::infer_call_trait_method_on_generic_param_1 ... ok
test tests::method_resolution::infer_trait_assoc_method ... ok
test tests::method_resolution::infer_associated_method_struct_in_local_scope ... ok
test tests::method_resolution::infer_trait_assoc_method_generics_1 ... ok
test tests::method_resolution::infer_trait_method_generic_2 ... ok
test tests::method_resolution::infer_trait_assoc_method_generics_5 ... ok
test tests::method_resolution::infer_trait_method_generic_1 ... ok
test tests::method_resolution::infer_trait_assoc_method_generics_3 ... ok
test tests::method_resolution::infer_trait_method_scoped ... ok
test tests::method_resolution::infer_trait_method_scoped ... ok
test tests::method_resolution::infer_trait_assoc_method_generics_4 ... ok
test tests::method_resolution::infer_trait_method_generic_more_params ... ok
test tests::method_resolution::deref_fun_1 ... ok
test tests::method_resolution::infer_with_multiple_trait_impls ... ok
test tests::method_resolution::infer_with_multiple_trait_impls ... ok
test tests::method_resolution::infer_trait_assoc_method_generics_2 ... ok
test tests::method_resolution::method_resolution_non_parameter_type ... ok
test tests::method_resolution::inherent_impl_in_unnamed_const ... ok
test tests::method_resolution::method_resolution_impl_before_trait ... ok
test tests::method_resolution::local_impl ... ok
---
test tests::method_resolution::super_trait_impl_return_trait_method_resolution ... ok
test tests::method_resolution::sized_blanket_impl ... ok
test tests::never_type::match_second_arm_never ... ok
test tests::never_type::issue_11837 ... ok
test tests::never_type::match_unknown_arm ... ok
test tests::never_type::match_no_never_arms ... ok
test tests::never_type::never_type_can_be_reinferred1 ... ok
test tests::patterns::if_let_guards ... ok
test tests::never_type::never_type_can_be_reinferred3 ... ok
test tests::never_type::never_type_can_be_reinferred2 ... ok
test tests::patterns::enum_variant_through_self_in_pattern ... ok
test tests::method_resolution::skip_array_during_method_dispatch ... ok
test tests::patterns::infer_const_pattern ... ok
test tests::patterns::box_pattern ... ok
test tests::patterns::infer_adt_pattern ... ok
test tests::patterns::infer_generics_in_patterns ... ok
test tests::patterns::infer_literal_pattern ... ok
test tests::patterns::const_block_pattern ... ok
test tests::patterns::infer_guard ... ok
test tests::patterns::infer_guard ... ok
test tests::patterns::infer_pattern_match_ergonomics_ref ... ok
test tests::patterns::infer_pattern_match_or ... ok
test tests::patterns::infer_range_pattern ... ok
test tests::patterns::infer_pattern_match_slice ... ok
test tests::patterns::slice_pattern_correctly_handles_array_length ... ok
test tests::patterns::slice_tail_pattern ... ok
test tests::patterns::macro_pat ... ok
test tests::patterns::infer_pattern_match_arr ... ok
test tests::patterns::infer_pattern_match_string_literal ... ok
test tests::patterns::tuple_ellipsis_pattern ... ok
test tests::patterns::type_mismatch_in_or_pattern ... ok
test tests::patterns::pattern_lookup_in_value_ns ... ok
test tests::patterns::tuple_struct_ellipsis_pattern ... ok
test tests::patterns::infer_pattern ... ok
test tests::regression::array_elements_expected_type ... ok
test tests::patterns::infer_pattern_match_ergonomics ... ok
test tests::patterns::tuple_wildcard ... ok
test tests::regression::bug_585 ... ok
test tests::regression::bug_484 ... ok
test tests::regression::cfg_tail ... ok
test tests::regression::bug_651 ... ok
test tests::regression::cfgd_out_self_param ... ok
test tests::regression::bug_1030 ... ok
test tests::regression::gat_crash_1 ... ok
test tests::regression::coerce_diesel_panic ... ok
test tests::regression::for_loop_block_expr_iterable ... ok
test tests::regression::bug_11659 ... ok
test tests::regression::const_generic_impl_trait ... ok
test tests::regression::infer_array_macro_call ... ok
test tests::regression::gat_crash_2 ... ok
test tests::regression::impl_trait_in_option_9530 ... ok
test tests::regression::infer_std_crash_2 ... ok
test tests::regression::infer_std_crash_1 ... ok
test tests::regression::infer_paren_macro_call ... ok
test tests::regression::bare_dyn_trait_binders_9639 ... ok
test tests::regression::infer_nested_generics_crash ... ok
test tests::regression::bug_11242 ... ok
test tests::regression::infer_std_crash_3 ... ok
test tests::method_resolution::resolve_minicore_iterator ... ok
test tests::regression::infer_std_crash_4 ... ok
test tests::regression::bitslice_panic ... ok
test tests::regression::issue_2705 ... ok
test tests::regression::issue_3999_slice ... ok
test tests::regression::infer_std_crash_5 ... ok
test tests::regression::issue_3999_struct ... ok
test tests::regression::issue_2669 ... ok
test tests::regression::issue_4235_name_conflicts ... ok
test tests::regression::issue_4465_dollar_crate_at_type ... ok
test tests::regression::issue_6811 ... ok
test tests::regression::issue_4953 ... ok
test tests::regression::call_expected_type_closure ... ok
test tests::regression::issue_4931 ... ok
test tests::regression::const_generic_error_tolerance ... ok
test tests::regression::no_panic_on_field_of_enum ... ok
test tests::regression::nested_macro_in_fn_params ... ok
test tests::regression::param_overrides_fn ... ok
test tests::regression::issue_4053_diesel_where_clauses ... ok
test tests::regression::nalgebra_factorial ... ok
test tests::regression::issue_8686 ... ok
test tests::regression::issue_6852 ... ok
test tests::regression::recursive_vars ... ok
test tests::macros::infinitely_recursive_macro_type ... ok
test tests::patterns::match_ergonomics_in_closure_params ... ok
test tests::regression::issue_4966 ... ok
test tests::regression::recursive_vars_2 ... ok
test tests::regression::regression_11688_2 ... ok
test tests::regression::macro_expands_to_impl_trait ... ok
test tests::regression::while_loop_block_expr_iterable ... ok
test tests::regression::issue_2683_chars_impl ... ok
test tests::regression::regression_11688_1 ... ok
test tests::regression::issue_6628 ... ok
test tests::regression::tuple_struct_pattern_with_unmatched_args_crash ... ok
test tests::simple::cfgd_out_assoc_items ... ok
test tests::simple::closure_return ... ok
test tests::regression::regression_11688_4 ... ok
test tests::simple::const_eval_array_repeat_expr ... ok
test tests::salsa_bug ... ok
---
test tests::simple::block_modifiers_smoke_test ... ok
test tests::simple::generic_default_depending_on_other_type_arg_forward ... ok
test tests::simple::destructuring_assignment_struct ... ok
test tests::simple::generic_default ... ok
test tests::regression::issue_4885 ... ok
test tests::simple::infer_adt_self ... ok
test tests::simple::async_block_early_return ... ok
test tests::simple::infer_backwards ... ok
test tests::simple::box_into_vec ... ok
test tests::simple::infer_basics ... ok
test tests::simple::infer_array ... ok
---
test tests::traits::associated_type_placeholder ... ok
test tests::traits::associated_type_placeholder_2 ... ok
test tests::traits::associated_type_shorthand_from_self_issue_12484 ... ok
test tests::traits::array_length ... ok
test tests::traits::associated_type_shorthand_from_method_bound ... ok
test tests::traits::argument_impl_trait_type_args_1 ... ok
test tests::traits::bin_op_adt_with_rhs_primitive ... ok
test tests::traits::assoc_types_from_bounds ... ok
test tests::traits::argument_impl_trait_type_args_2 ... ok
test tests::traits::associated_type_sized_bounds ... ok
test tests::traits::argument_impl_trait ... ok
test tests::traits::deref_trait ... ok
---
test tests::traits::error_bound_chalk ... ok
test tests::traits::dyn_trait_bare ... ok
test tests::traits::builtin_sized ... ok
test tests::traits::builtin_copy ... ok
test tests::traits::dyn_trait_in_impl ... ok
test tests::traits::bin_op_with_rhs_is_self_for_assoc_bound ... ok
test tests::traits::dyn_trait_through_chalk ... ok
test tests::traits::dyn_map ... ok
test tests::traits::closure_2 ... ok
test tests::traits::closure_2 ... ok
test tests::traits::dyn_fn_param_informs_call_site_closure_signature ... ok
test tests::traits::fn_item_fn_trait ... ok
test tests::traits::generic_param_env_1 ... ok
test tests::traits::generic_param_env_2_not_met ... ok
test tests::traits::fn_ptr_and_item ... ok
test tests::traits::generic_param_env_1_not_met ... ok
test tests::traits::fn_returning_unit ... ok
test tests::traits::indexing_arrays ... ok
test tests::traits::infer_associated_type_bound ... ok
test tests::traits::generic_param_env_deref ... ok
test tests::traits::generic_param_env_deref ... ok
test tests::traits::fn_trait_deref_with_ty_default ... ok
test tests::traits::assoc_type_bindings ... ok
test tests::traits::closure_as_argument_inference_order ... ok
test tests::traits::infer_async ... ok
test tests::traits::fn_trait ... ok
test tests::traits::infer_const_body ... ok
test tests::traits::generic_param_env_2 ... ok
test tests::traits::infer_await ... ok
test tests::traits::infer_from_bound_1 ... ok
test tests::traits::infer_async_ret_type ... ok
test tests::traits::infer_async_ret_type ... ok
test tests::traits::impl_trait ... ok
test tests::traits::infer_default_trait_type_parameter ... ok
test tests::traits::infer_from_bound_2 ... ok
test tests::traits::dyn_trait ... ok
test tests::traits::infer_async_block ... ok
test tests::traits::infer_for_loop ... ok
test tests::traits::infer_desugar_async ... ok
test tests::traits::infer_dyn_fn_once_output ... ok
test tests::traits::infer_ops_index_field ... ok
test tests::traits::infer_box_fn_arg ... ok
test tests::traits::infer_ops_index ... ok
test tests::traits::infer_ops_neg ... ok
test tests::traits::impl_trait_assoc_binding_projection_bug ... ok
test tests::traits::infer_try ... ok
test tests::traits::infer_dyn_fn_output ... ok
test tests::traits::infer_ops_index_field_autoderef ... ok
test tests::traits::infer_project_associated_type ... ok
test tests::traits::infer_fn_trait_arg ... ok
test tests::traits::infer_ops_index_int ... ok
test tests::traits::infer_ops_index_autoderef ... ok
test tests::traits::infer_ops_not ... ok
test tests::traits::infer_return_associated_type ... ok
test tests::traits::inner_use ... ok
test tests::traits::infer_from_return_pos_impl_trait ... ok
---
test tests::traits::local_impl_1 ... ok
test tests::traits::super_trait_cycle ... ok
test tests::traits::integer_range_iterate ... ok
test tests::traits::string_to_owned ... ok
test tests::traits::simple_return_pos_impl_trait ... ok
test tests::traits::obligation_from_method_clause ... ok
test tests::traits::local_impl_3 ... ok
test tests::traits::super_trait_method_resolution ... ok
test tests::traits::trait_default_method_self_bound_implements_super_trait ... ok
test tests::traits::qualified_path_as_qualified_trait ... ok
test tests::traits::projection_eq_within_chalk ... ok
test tests::traits::super_trait_assoc_type_bounds ... ok
test tests::traits::super_trait_impl_trait_method_resolution ... ok
test tests::traits::renamed_extern_crate_in_block ... ok
test tests::traits::renamed_extern_crate_in_block ... ok
test tests::traits::nested_assoc ... ok
test tests::traits::obligation_from_impl_clause ... ok
test tests::traits::trait_in_scope_of_trait_impl ... ok
test tests::traits::trait_impl_self_ty ... ok
test tests::traits::more_return_pos_impl_trait ... ok
test tests::traits::tuple_struct_fields ... ok
test tests::traits::trait_object_no_coercion ... ok
test tests::traits::trait_default_method_self_bound_implements_trait ... ok
test tests::traits::trait_impl_self_ty_cycle ... ok
test tests::traits::tuple_struct_with_fn ... ok
test tests::traits::underscore_import ... ok
test tests::traits::unselected_projection_in_trait_env_cycle_1 ... ok
test tests::traits::unselected_projection_in_trait_env_cycle_2 ... ok
test tests::traits::unselected_projection_in_trait_env_cycle_3 ... ok
test tests::traits::unselected_projection_in_trait_env_1 ... ok
test tests::traits::trait_in_scope_with_inner_item ... ok
test tests::traits::variable_kinds_2 ... ok
test tests::traits::unselected_projection_in_trait_env_2 ... ok
test tests::traits::where_clause_trait_in_scope_for_method_resolution ... ok
test tests::traits::variable_kinds_1 ... ok
test tests::traits::unselected_projection_on_impl_self ... ok
test tests::traits::unselected_projection_chalk_fold ... ok
test tests::traits::unselected_projection_in_trait_env_no_cycle ... ok
test tests::traits::weird_bounds ... ok
test tests::traits::unify_impl_trait ... ok
test tests::traits::unselected_projection_on_trait_self ... ok

failures:

---- tests::macros::benchmark_include_macro stdout ----
---- tests::macros::benchmark_include_macro stdout ----
thread 'tests::macros::benchmark_include_macro' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/test-utils/src/lib.rs:399:31


failures:
    tests::macros::benchmark_include_macro
    tests::macros::benchmark_include_macro

test result: FAILED. 505 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.11s

error: test failed, to rerun pass '-p hir-ty --lib'
