text
Adding src/tools/rust-analyzer/xtask/src/release/changelog.rs
Adding src/tools/rust-analyzer/xtask/src/release.rs
Adding src/tools/rust-analyzer/xtask/src/metrics.rs
Adding src/tools/rust-analyzer/xtask/src/main.rs
Adding src/tools/rust-analyzer/xtask/src/install.rs
Adding src/tools/rust-analyzer/xtask/src/flags.rs
Adding src/tools/rust-analyzer/xtask/src/dist.rs
Adding src/tools/rust-analyzer/xtask/Cargo.toml
Adding src/tools/rust-analyzer/triagebot.toml
Adding src/tools/rust-analyzer/rustfmt.toml
Adding src/tools/rust-analyzer/lib/lsp-server/src/stdio.rs
Adding src/tools/rust-analyzer/lib/lsp-server/src/socket.rs
Adding src/tools/rust-analyzer/lib/lsp-server/src/req_queue.rs
Adding src/tools/rust-analyzer/lib/lsp-server/src/msg.rs
Adding src/tools/rust-analyzer/lib/lsp-server/src/lib.rs
Adding src/tools/rust-analyzer/lib/lsp-server/src/error.rs
Adding src/tools/rust-analyzer/lib/lsp-server/examples/goto_def.rs
Adding src/tools/rust-analyzer/lib/lsp-server/Cargo.toml
Adding src/tools/rust-analyzer/lib/la-arena/src/map.rs
Adding src/tools/rust-analyzer/lib/la-arena/src/lib.rs
Adding src/tools/rust-analyzer/lib/la-arena/Cargo.toml
Adding src/tools/rust-analyzer/lib/README.md
Adding src/tools/rust-analyzer/editors/code/tsconfig.json
Adding src/tools/rust-analyzer/editors/code/tsconfig.eslint.json
Adding src/tools/rust-analyzer/editors/code/tests/unit/settings.test.ts
Adding src/tools/rust-analyzer/editors/code/tests/unit/runnable_env.test.ts
Adding src/tools/rust-analyzer/editors/code/tests/unit/launch_config.test.ts
Adding src/tools/rust-analyzer/editors/code/tests/unit/index.ts
Adding src/tools/rust-analyzer/editors/code/tests/runTests.ts
Adding src/tools/rust-analyzer/editors/code/src/util.ts
Adding src/tools/rust-analyzer/editors/code/src/toolchain.ts
Adding src/tools/rust-analyzer/editors/code/src/tasks.ts
Adding src/tools/rust-analyzer/editors/code/src/snippets.ts
Adding src/tools/rust-analyzer/editors/code/src/run.ts
Adding src/tools/rust-analyzer/editors/code/src/persistent_state.ts
Adding src/tools/rust-analyzer/editors/code/src/main.ts
Adding src/tools/rust-analyzer/editors/code/src/lsp_ext.ts
Adding src/tools/rust-analyzer/editors/code/src/debug.ts
Adding src/tools/rust-analyzer/editors/code/src/ctx.ts
Adding src/tools/rust-analyzer/editors/code/src/config.ts
Adding src/tools/rust-analyzer/editors/code/src/commands.ts
Adding src/tools/rust-analyzer/editors/code/src/client.ts
Adding src/tools/rust-analyzer/editors/code/src/ast_inspector.ts
Adding src/tools/rust-analyzer/editors/code/ra_syntax_tree.tmGrammar.json
Adding src/tools/rust-analyzer/editors/code/package.json
Adding src/tools/rust-analyzer/editors/code/package-lock.json
Adding src/tools/rust-analyzer/editors/code/language-configuration.json
Adding src/tools/rust-analyzer/editors/code/icon.png
Adding src/tools/rust-analyzer/editors/code/README.md
Adding src/tools/rust-analyzer/editors/code/LICENSE
Adding src/tools/rust-analyzer/editors/code/.vscodeignore
Adding src/tools/rust-analyzer/editors/code/.prettierrc.js
Adding src/tools/rust-analyzer/editors/code/.prettierignore
Adding src/tools/rust-analyzer/editors/code/.gitignore
Adding src/tools/rust-analyzer/editors/code/.eslintrc.js
Adding src/tools/rust-analyzer/editors/code/.eslintignore
Adding src/tools/rust-analyzer/docs/user/manual.adoc
Adding src/tools/rust-analyzer/docs/user/generated_config.adoc
Adding src/tools/rust-analyzer/docs/user/.gitignore
Adding src/tools/rust-analyzer/docs/dev/syntax.md
Adding src/tools/rust-analyzer/docs/dev/style.md
Adding src/tools/rust-analyzer/docs/dev/lsp-extensions.md
Adding src/tools/rust-analyzer/docs/dev/guide.md
Adding src/tools/rust-analyzer/docs/dev/debugging.md
Adding src/tools/rust-analyzer/docs/dev/architecture.md
Adding src/tools/rust-analyzer/docs/dev/README.md
Adding src/tools/rust-analyzer/crates/vfs/src/vfs_path/tests.rs
Adding src/tools/rust-analyzer/crates/vfs/src/vfs_path.rs
Adding src/tools/rust-analyzer/crates/vfs/src/path_interner.rs
Adding src/tools/rust-analyzer/crates/vfs/src/loader.rs
Adding src/tools/rust-analyzer/crates/vfs/src/lib.rs
Addingerror: add_cacheinfo failed to refresh for path 'src/tools/rust-analyzer/crates/syntax/test_data/parser/validation/0046_mutable_const_item.rs'; merge aborting.
 src/tools/rust-analyzer/crates/vfs/src/file_set/tests.rs
Adding src/tools/rust-analyzer/crates/vfs/src/file_set.rs
Adding src/tools/rust-analyzer/crates/vfs/src/anchored_path.rs
Adding src/tools/rust-analyzer/crates/vfs/Cargo.toml
Adding src/tools/rust-analyzer/crates/vfs-notify/src/lib.rs
Adding src/tools/rust-analyzer/crates/vfs-notify/Cargo.toml
Adding src/tools/rust-analyzer/crates/tt/src/lib.rs
Adding src/tools/rust-analyzer/crates/tt/src/buffer.rs
Adding src/tools/rust-analyzer/crates/tt/Cargo.toml
Adding src/tools/rust-analyzer/crates/toolchain/src/lib.rs
Adding src/tools/rust-analyzer/crates/toolchain/Cargo.toml
Adding src/tools/rust-analyzer/crates/text-edit/src/lib.rs
Adding src/tools/rust-analyzer/crates/text-edit/Cargo.toml
Adding src/tools/rust-analyzer/crates/test-utils/src/minicore.rs
Adding src/tools/rust-analyzer/crates/test-utils/src/lib.rs
Adding src/tools/rust-analyzer/crates/test-utils/src/fixture.rs
Adding src/tools/rust-analyzer/crates/test-utils/src/bench_fixture.rs
Adding src/tools/rust-analyzer/crates/test-utils/src/assert_linear.rs
Adding src/tools/rust-analyzer/crates/test-utils/Cargo.toml
Adding src/tools/rust-analyzer/crates/syntax/test_data/reparse/fuzz-failures/0005.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/reparse/fuzz-failures/0004.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/reparse/fuzz-failures/0003.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/reparse/fuzz-failures/0002.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/reparse/fuzz-failures/0001.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/reparse/fuzz-failures/0000.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/validation/invalid_let_expr.rs
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/validation/invalid_let_expr.rast
Adding src/tools/rust-analyzer/crates/syntax/test_data/parser/validation/0046_mutable_const_item.rs

